### ISSUE TITLE
Floodgate skins conflict with SkinsRestorer

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1000]
tested with current latest dev builds.
`/sr apply` command does resolve the issue.
Issue is when the player joins and floodgate is applying the skin.

==== setup ===
auth type: floodgate (in geyser config)
offline mode

**Comment by xknat** [comment]
1000 Th issue / PR 🎊

**Comment by AceSardonyx** [comment]
gwa

**Comment by xknat** [comment]
I did some testing.
1. floodgate / gesyer is NOT canceling our applyEvent
2. SkinsRestorer does correctly apply the skin
3. Floodgate / Geyser is Slower then SkinsRestorer, this means that floodgate / geyser will override the skin as it will be applyed later due to mineskin delay.

Steps to be taken:
Check out on floodgate / geyser side for any skin event we can cancel if the player has set a skin when joining.
No event found? --> contact Camotoy on our own server

**Comment by Sayrix** [comment]
How can we prevent the bug ? Wait an update from floodgate ?

**Comment by xknat** [comment]
> How can we prevent the bug ? Wait an update from floodgate ?

Wait for a update from us or floodgate.
Will also shoot in a issue on floodgate.
Help me remember if i don't

**Comment by Sayrix** [comment]
I opened it for you https://github.com/GeyserMC/Floodgate/issues/403

**Comment by Sayrix** [comment]
Hey @xknat Floodgate added the event SkinApplyEvent so i think you can fix the bug

**Comment by kolderz** [comment]
@xknat I'm having this issue as well. Where SkinsRestorer conflict with Floodgate and Geyser.
https://controlc.com/50cf88a0

**Comment by xknat** [comment]
> Hey @xknat Floodgate added the event SkinApplyEvent so i think you can fix the bug

Should be working better in v15 as we moved over to UUID.
