### ISSUE TITLE
applying skin does interrupt potion effect's 

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1001]
Works on 1.18+
==================
applying skin can have a bad / positive effect on the potion.
sometimes positive as negative

Effect & effect of refreshing the skin
| Effect name          | Normal behaviour                      | SkinsRestorer applying skin     |
|----------------------|---------------------------------------|---------------------------------|
| Darkness & blindness | Player can't see                        | Player can see again            |
| Levetation           | Player goes up in the air             | Player falls down (no fall dmg) |
| Nightvision          | Player can see at night               | Effect end                      |
| water_breathing      | breath under water, bubles stay still | Player start's lozing bubles    |

This is a noticeable on client side effect

**Comment by xknat** [comment]
@AlexProgrammerDE it seems to be that paper is using this code:
```java
ServerGamePacketListenerImpl connection = handle.connection;
connection.send(new net.minecraft.network.protocol.game.ClientboundSetExperiencePacket(handle.experienceProgress, handle.totalExperience, handle.experienceLevel));
for (net.minecraft.world.effect.MobEffectInstance mobEffect : handle.getActiveEffects()) {
    connection.send(new net.minecraft.network.protocol.game.ClientboundUpdateMobEffectPacket(handle.getId(), mobEffect));
}
```


https://github.com/PaperMC/Paper/blob/e8bec64217064476784a5c65a5060cfc0145fa98/patches/server/0182-Player.setPlayerProfile-API.patch#L169-L173

**Comment by AlexProgrammerDE** [comment]
Yes, I contributed this to them during 1.19.
