### ISSUE TITLE
Leaving `EnableProtocolListener` on the default value of `false` causes legacy clients connecting through ViaRewind to be unable to update their position on the server.

### ISSUE THREAD

**Issue by akemin-dayo** [SkinsRestorer/SkinsRestorerX#1013]
## Describe the bug
Leaving `EnableProtocolListener` on the default value of `false` causes legacy clients connecting through ViaRewind to be unable to update their position on the server.

When `EnableProtocolListener` is set to `true`, everything works as expected.

---

## How can we reproduce what you got?
1. Set up a [Paper 1.17.1](https://api.papermc.io/v2/projects/paper/versions/1.17.1/builds/411/downloads/paper-1.17.1-411.jar) server (or newer — this most likely occurs with newer versions, too) containing this minimal set of plugins:
    * [ViaVersion 4.4.0](https://github.com/ViaVersion/ViaVersion/releases/tag/4.4.0)
    * [ViaBackwards 4.4.0](https://github.com/ViaVersion/ViaBackwards/releases/tag/4.4.0)
    * [ViaRewind 2.0.2 Stable](https://www.spigotmc.org/resources/52109) (or [the latest development CI build](https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/) which is what I use — both exhibit this behaviour, anyway)
    * [SkinsRestorerX 14.2.1](https://github.com/SkinsRestorer/SkinsRestorerX/releases/tag/14.2.1)
    * [ProtocolLib 4.8.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0)
    * [EssentialsX 2.19.4 Stable](https://github.com/EssentialsX/Essentials/releases/tag/2.19.4) (※ This is only so we can have the `/getpos` command that allows us to see where the server thinks a player's position is.)
2. Leave SkinsRestorerX's `EnableProtocolListener` config value at the default of `false`.
3. Join the server using a legacy client (1.8.9 or 1.7.10).
4. Set a custom SkinsRestorerX skin, if you don't already have one set.
5. Run `/getpos` to see your current position on the server.
6. Move somewhere else.
7. Run `/getpos` again, and see that your current position on the server has not changed. If you move far enough, the world will stop loading because the server isn't sending you chunks anymore (since it thinks your position has not changed).
    * This behaviour sometimes does not occur when you join a server for the first time. If this occurs, simply disconnect and re-join, and this issue will begin occurring.
8. Stop the server, and change SkinsRestorerX's `EnableProtocolListener` to `true`.
9. Do the above again, and notice how everything works as expected.

**Expected behavior**
`EnableProtocolListener: false` behaviour should match `EnableProtocolListener: true`.

---

## Workaround
Set `EnableProtocolListener: true` in your SkinsRestorerX configuration file.

---

## Server information
* Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
* SkinsRestorerX 14.2.1
* Java 17.0.1

---

## Logs
* [Server log, `EnableProtocolListener: true`](https://gist.github.com/akemin-dayo/b37301ab6cfa4d663122337b914aebeb)
* [Server log, `EnableProtocolListener: false`, default behaviour](https://gist.github.com/akemin-dayo/68fac25151a3383654f9abd992e457fe)

---

## Additional context
* This issue occurs with both `online-mode=true` (where I first noticed it), as well as `online-mode=false`.

**Comment by xknat** [comment]
is this issue reproducible on viaversion [4.3.1](https://github.com/ViaVersion/ViaVersion/releases/tag/4.3.1)? as 4.4.0 has been released a view hours ago

**Comment by akemin-dayo** [comment]
Yes, it happens on the older versions, too.

**Comment by akemin-dayo** [comment]
Closing as the `EnableProtocolListener` preference itself has been removed at some point, and the issue no longer occurs as of SkinsRestorerX 15.0.13.
