### ISSUE TITLE
Plugin skinsrestorer.bungee.SkinsRestorer@5b1f5fcc has not registered intent for event LoginEvent

### ISSUE THREAD

**Issue by minecraft7net** [SkinsRestorer/SkinsRestorerX#102]
https://pastebin.com/rEfrmShd

i think it maybe - potential FastLogin (?) i have server offline with FastLogin premium autologin 

### Describe the problem in a few short sentences
errors in log (bungeecord)

### How can we reproduce the problem?
not yet - just errors in log in some login

### What version of SkinsRestorerX are you using?
[22:28:02] [main/INFO]: Loaded plugin SkinsRestorer version 13.5.1-SNAPSHOT by Th3Tr0LLeR, DoNotSpamPls, Blackfire62

### What is your Spigot/BungeeCord/Sponge version?
Travertine - b66

**Comment by xknat** [comment]
yeah there is a setting in fastlogin that does not work to well with skinsrestorer skins. check the config

**Comment by xknat** [comment]
already resolved

**Comment by Leymooo** [comment]
I think there is missed `return`. https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/listeners/LoginListener.java#L74

when error occurred plugin trigger completeIntern two times in line 74 and in line 79

**Comment by McLive** [comment]
Nah, you are most likely using an outdated version of SR or an incompatible plugin when you see this error.

**Comment by Leymooo** [comment]
??? Wtf
https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/listeners/LoginListener.java#L55
getUuid can throw an Exeption.

This means that completeIntern will be execute twice and IllegalStateException will be throw by bungee
