### ISSUE TITLE
sr stopped working for dev builds of velocity (3.1.2+)

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1026]
edit:
resolved by https://github.com/SkinsRestorer/SkinsRestorerX/commit/b5b79bc6b9a87271962bc59e8c56f304eaaa566e
use dev builds from https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/

-----
ticket:
![image](https://user-images.githubusercontent.com/10220139/182886566-2d7e6bd4-a921-4a7b-8345-7ea57dafd578.png)

works on 14.2.1
works on stable velocity but not their dev builds (3.1.2 and up)

**Comment by AVuTuVA** [comment]
I wrote to you this morning that it doesn't work...

**Comment by DonnyDev-FS** [comment]
Same for me

**Comment by KungfuEpt** [comment]
Same

**Comment by xknat** [comment]
no need to bump this ty

**Comment by xknat** [comment]
resolved by https://github.com/SkinsRestorer/SkinsRestorerX/commit/b5b79bc6b9a87271962bc59e8c56f304eaaa566e
use dev builds from https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/
