### ISSUE TITLE
Doesn't work on Velocity

### ISSUE THREAD

**Issue by Decakeee** [SkinsRestorer/SkinsRestorerX#1031]
## Describe the bug

Latest version Skinrestorer doesn't work on latest version Velocity

## How can we reproduce what you got?

Run Skinrestorer on Velocity

**Expected behavior**
Skinrestorer will work

## Server information

Pufferfish & Velocity

* SkinsRestorer: 14.2.2
* Spigot version: git-Pufferfish-24 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37f936f on HEAD)
* Bungeecord version: 3.1.2-SNAPSHOT (git-6be344d9-b162)
* IF bungee, did you put the plugin on all servers: YES
* Java: 17
* plugin list bungee & spigot: Velocity: limboapi, limboauth, limbofilter. Pufferfish: AntiPluginLookUp*, AuthMe, ChatBubbles, Chatty, CoreProtect, CoreProtectTNT, DeathCoordinates, DecentHolograms, DiscordSRV, EasyWhitelist*, F3Name, floodgate, GSit, Harbor, InventoryRollbackPlus, LastLoginAPI, LuckPerms, OpenInv, OreAnnouncer, PlaceholderAPI, PlasmoVoice, PlayTime*, ServerListMotdSpigot, SkinsRestorer, squaremap, SurvivalInvisiframes, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion
* MinecraftLauncher?: MultiMC

## Logs

Error log: https://hastebin.app/62ee4f85d5c6ab001c626c71
Startup Pufferfish: https://hastebin.app/62ee507bd5c6ab001c626c72
Startup: Velocity https://hastebin.app/62ee50a8d5c6ab001c626c73

**Comment by xknat** [comment]
We just released the fix man cmon update update update

**Comment by Decakeee** [comment]
what timings bro :)



> We just released the fix man cmon update update update

**Comment by xknat** [comment]
> what timings bro :)
> 
> > We just released the fix man cmon update update update

next time look at https://github.com/SkinsRestorer/SkinsRestorerX/issues before creating a issue
you would have seen that it was already resolved on dev build
