### ISSUE TITLE
not working on mohist servers

### ISSUE THREAD

**Issue by Zhou-Shilin** [SkinsRestorer/SkinsRestorerX#1036]
(sorry but i speak chinese instead of english so my grammar may not right)
this plugin is not working on mohist server (forge + bukkit)
someone has skin but someone (includes somebody who buys minecraft from mojang _（这里指包括正版玩家在内，可能我写的有点问题qwq）_) only have steve or alex

can u make a plugin (or a mod just like for sponge) for mohist and other forge + bukkit server) ?

**Comment by xknat** [comment]
mohist is not yet supported, see https://github.com/SkinsRestorer/SkinsRestorerX#telescope-compatibility

**Comment by Zhou-Shilin** [comment]
> mohist is not yet supported, see https://github.com/SkinsRestorer/SkinsRestorerX#telescope-compatibility

ok
