### ISSUE TITLE
Skin doesn't change

### ISSUE THREAD

**Issue by WhatUsd** [SkinsRestorer/SkinsRestorerX#1045]
## Describe the bug

I'm trying to use skinsrestorer, when I do /skin set ..., it says my skin has been changed but I'm still left with the Alex Skin, a few seconds after that, I get a message saying "an internal error occurred while attempting to tab-complete this command"
## How can we reproduce what you got?
Basically, I'm on a shockbyte hosting server, and using Mohist 1.18.2, and I'm using the correct version of SkinsRestorers
1. do /skin set "skinname" (I did not put the skin name blank)
2. It will say "Your skin has been changed" but it's still Alex
3. A few seconds later it says "An internal error occurred while attempting to tab-complete this command"
**Expected behavior**
I was going to expect it to work properly, I once had an Aternos server and it worked perfectly fine, but in this situation it doesn't.
**Screenshots**
## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)** 
Mohist, using Shockbyte

**What version? Do NOT answer LATEST**
1.18.2
* SkinsRestorer: 14.2.3
* Spigot version:
* Java: 1.18.2
* plugin list bungee & spigot: SkinsRestorer (Basically it)
* MinecraftLauncher?: CurseForge

**Comment by xknat** [comment]
Mohist is not a supported implementation
