### ISSUE TITLE
Duplicate player images

### ISSUE THREAD

**Issue by Chypik** [SkinsRestorer/SkinsRestorerX#105]
Images of players are duplicated when entering and leaving the server. There is no player on the server, and his image is present.

[SkinsRestorer] Enabling SkinsRestorer v13.5.1-SNAPSHOT
[SkinsRestorer] Detected Minecraft v1_13_R2, using UniversalSkin Factors

[ProtocolLib] Enabling ProtocolLib v4.4.0-SNAPSHOT-b419 *

This server is running Paper version git-Paper-453 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Chypik** [comment]
I understand that ignoring this problem?

**Comment by xknat** [comment]
sorry man, if you asked on discord it would be awesome...
anyways, its prob your vps geo location, your anti cheat plugins, and other connection factors that are making this problem happen. 

As i am never ever able to reproduce this, its not smth we can fix local...

**Comment by Angel-0** [comment]
@Chypik may we know in what country your host is?

**Comment by xknat** [comment]
@Chypik kindly let us know if any support is still needed

**Comment by xknat** [comment]
no response
