### ISSUE TITLE
After installing the skin, chunks disappear.

### ISSUE THREAD

**Issue by yuankun1** [SkinsRestorer/SkinsRestorerX#1052]
1. Skinsrestor works with CMI plug-ins
2. Turn on the "spawnonjoin" option of CMI
3. Enter the server and switch to another world
4. When you re-enter the server, it will be forced to switch, and the world block will disappear
5. And authme's "forcespanloconjoin" option/It will also lead to the problem that blocks disappear
6. No errors
![1](https://user-images.githubusercontent.com/19505154/188333645-9203055c-3ada-47c2-a818-614f16ba2f2e.png)

SkinsRestorer:  Latest version 14.2.3
Spigot version: 1.12.2/catserver
Bungeecord version: NO
Java: 8 
plugin list bungee & spigot: spigot
if multiverse, (censored) worlds file: Multiverse-Core 2.5.0

**Comment by xknat** [comment]
Invalid: catserver is not supported
