### ISSUE TITLE
Skinsgui & velocity, is it a thing?

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1054]
Ticket ticket-1660401033 report's that skinsgui is not working for velocity.
Need to check and confirm its working under default installation
"`When I set "disableProxyMode.txt" on the backend server and remove the proxy plugin the command works correctly again`" 
![ZaGqSkG](https://user-images.githubusercontent.com/10220139/188443777-cbb1871c-89e8-427d-828d-7682cc036452.png)

**Comment by Luciusred** [comment]
really need it

**Comment by AlexProgrammerDE** [comment]
yes it is
