### ISSUE TITLE
DefaultSkin not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SkinsRestorer/SkinsRestorerX#106]
### Describe the problem in a few short sentences
Its just not working, nothing else. All cracked players have steve or alex skin

### What version of SkinsRestorerX are you using?
13.5.1

### What is your Spigot/BungeeCord/Sponge version?
1.13

**Comment by aljaxus** [comment]
Do you have any errors? If so, paste them here: https://hastebin.com and provide the URL of the paste

Are you using bungeecord? 
    What version?
    Do you have FastLogin? 

Are you using default skins option?
Are the .skin files even being downloaded ?

**Comment by Kryniowesegryderiusz** [comment]
Only error i have is
```18:08:22 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@70f02c32, id=55787, owner=skinsrestorer.bungee.SkinsRestorer@30ea8c23, task=skinsrestorer.bungee.listeners.LoginListener$1@5757bcf4, delay=0, period=0, running=true) encountered an exception
java.lang.IllegalStateException: Plugin skinsrestorer.bungee.SkinsRestorer@30ea8c23 has not registered intent for event LoginEvent(cancelled=false, cancelReasonComponents=null, connection=[igoruni123] <-> InitialHandler)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
	at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:68)
	at skinsrestorer.bungee.listeners.LoginListener$1.run(LoginListener.java:79)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

Im using bungee 1.13 with fastlogin (games647 b848) and mysql, so all .skin infos are there.

**Comment by Kryniowesegryderiusz** [comment]
@aljaxus is it possible to fix? Christmas are comeing and people want to have our dedicated server skin to have, but we cant give them it :c

**Comment by xknat** [comment]
@Kryniowesegryderiusz are you able the set the skin (not by default but just set it like /skin)

**Comment by Kryniowesegryderiusz** [comment]
Yes I can set this skin by /skin or /sr

I cant set time high, because premium players will have old skins then :c

**Comment by McLive** [comment]
Please try again with the most recent build on [Jenkins ](https://ci.freecraft.eu/v2/job/SkinsRestorerX/) and if the error still exists, send new error messages.

**Comment by Kryniowesegryderiusz** [comment]
I tried with SkinsRestorer from last stable spigot.org build and still nothing. Skin is beeing downloaded so i have skin file, but nonpremium players do not have it

**Comment by xknat** [comment]
issue is in  code DEFAULT_SKINS_PREMIUM: [link](https://github.com/SkinsRestorer/SkinsRestorerX/commit/4149fc5894e990beafa829cbbc1589c63ecea29f#diff-514af8b7f53db282876511b5d79e3d33)
when DEFAULT_SKINS_PREMIUM = false it will skip applying default skin for NONE uuid players and apply my own skin when uuid != null 

when  DEFAULT_SKINS_PREMIUM = true
both will use DEFAULT_SKINS list
@McLive think the code for applying the default skins for uuid = null is missing

**Comment by McLive** [comment]
Fixed
https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar
https://github.com/SkinsRestorer/SkinsRestorerX/commit/70a01b3a2d7b0bba6573150b17aab81acadc4dff
