### ISSUE TITLE
/skins error (paper 1.8.8)

### ISSUE THREAD

**Issue by DevNatan** [SkinsRestorer/SkinsRestorerX#107]
### Describe the problem in a few short sentences
Using the **/skins** command displays an internal error

### How can we reproduce the problem?
A player (with or without command permission) use / kins.

### What version of SkinsRestorerX are you using?
from **/sr** in console
SkinsRestorer - v13.5.1-SNAPSHOT

### What is your Spigot/BungeeCord/Sponge version?
from **/ver**
CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by DevNatan** [comment]
Console:
![image](https://user-images.githubusercontent.com/24600258/49658457-413e3880-fa29-11e8-8d3b-70d16b5095cf.png)

**Comment by xknat** [comment]
We already know
