### ISSUE TITLE
Suggestion: Tab-completion for commands?

### ISSUE THREAD

**Issue by Arrian220** [SkinsRestorer/SkinsRestorerX#108]
Add tab-completion for commands.

Example:

Current version:

/sr set [ < args > ]

It would show:
/sr set < targets > < skin >

Similarly to: https://i.imgur.com/R3J13tT.png

**Comment by xknat** [comment]
tag: Suggestion, enchantment

**Comment by xknat** [comment]
@Arrian220 tab-completion for commands is now being realized on github!
https://github.com/SkinsRestorer/SkinsRestorerX/commit/3d5b58e0bcbe5ef962924e8376c8dbb2fe8aca09

**Comment by McLive** [comment]
Added in the newest build. :)

https://ci.freecraft.eu/v2/job/SkinsRestorerX/28/artifact/target/SkinsRestorer.jar
