### ISSUE TITLE
[Security Vendor] Malware detected while adding skinsrestorer to the server

### ISSUE THREAD

**Issue by ghost** [SkinsRestorer/SkinsRestorerX#1090]
I found a malware in SkinsRestorer while scanning the plugins folder. I downloaded the jar from spigotmc.org (I also freshly installed SkinsRestorer on a test server it also found a malware)\
I scanned my OS with an antivirus and none malware found.\
Please do something with this\
![obraz_2022-10-29_192159192](https://user-images.githubusercontent.com/76450526/198844931-57057028-d744-48e5-acd8-22e792447253.png)

**Comment by xknat** [comment]
> I found a malware in SkinsRestorer while scanning the plugins folder. I downloaded the jar from spigotmc.org (I also freshly installed SkinsRestorer on a test server it also found a malware) I scanned my OS with an antivirus and none malware found. Please do something with this ![obraz_2022-10-29_192159192](https://user-images.githubusercontent.com/76450526/198844931-57057028-d744-48e5-acd8-22e792447253.png)

Thanks for creating a issue.
We use os info to determine environment versions on which the plugin is run on.
I don't see how this could be resulting malware for your server.
Maybe @AlexProgrammerDE could add more information on this matter.

**Comment by xknat** [comment]
@SuperGDev the file OSINFO can be found here: https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java

**Comment by ghost** [comment]
> @SuperGDev the file OSINFO can be found here: https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java

By OS i mean my PC's Operating System (Winodws 10)\
I scanned my PC with Malwarebytes

**Comment by xknat** [comment]
> > @SuperGDev the file OSINFO can be found here: https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java
> 
> By OS i mean my PC's Operating System (Winodws 10) I scanned my PC with Malwarebytes

i think you misunderstood, the mentioned file that your scanner thinks is malware is likely not malware and the sourcecode can be find on  <https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java>

**Comment by ghost** [comment]
> > > @SuperGDev the file OSINFO can be found here: https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java
> > 
> > By OS i mean my PC's Operating System (Winodws 10) I scanned my PC with Malwarebytes
> 
> i think you misunderstood, the mentioned file that your scanner thinks is malware is likely not malware and the sourcecode can be find on  <https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/internal/OSInfo.java>

Then how did the whole minecraft proxy got infected with spigot MALWARE.Systemaccess.exec? Ive got a screenshot of the whole server getting infected

**Comment by xknat** [comment]
@SuperGDev read carefully.
the word "[MIGHT](https://www.oxfordlearnersdictionaries.com/definition/english/might_1)" definition: used when showing that something is or was possible.
In this case, it's likely a false positive, this means that your scanner is saying that it think it **might** be malware while it's not.

**Comment by xknat** [comment]
Keep in mind that our source is public, you can look at the code yourself to determine if we are releasing malware or not.
We are being used by over 30.000 servers, i think we would hit newspapers if we were hacking / having malicious intent.
As for why this happens? i don't know. i would need to check with AntiMalware plugin.

**Comment by ghost** [comment]
> @SuperGDev read carefully. the word "[MIGHT](https://www.oxfordlearnersdictionaries.com/definition/english/might_1)" definition: used when showing that something is or was possible. In this case, it's likely a false positive, this means that your scanner is saying that it think it **might** be malware while it's not.

Alright thanks. I will check after a week if something bad happens again. Sorry I thought it was a malware 😂
