### ISSUE TITLE
Use onPlayerJoin instead of prePlayerLoginEvent

### ISSUE THREAD

**Issue by Zenya4** [SkinsRestorer/SkinsRestorerX#110]
SkinsRestorer currently uses prePlayerLoginEvent to supply skins to users. As such a plugin is commonly used on cracked minecraft servers, bot attacks are really an issue and using this event makes it impossible for any antibot to counter bot attacks as fetching skins for hundreds of bots (fake player joins) at once is extremely CPU intensive and will crash the server. 

Antibot plugins usually use prePlayerLoginEvent to determine if a user is fake (bot user) and kick the user from there, and any other plugin after that should only use onPlayerJoin to eliminate any bot users kicked by an antibot from wasting server resources like fetching skins. 

The competitor of SkinsRestorer, ChangeSkin, currently does that and that is the only part about it better than SkinsRestorer. I hope this change can be implemented as it will really help many cracked server owners, rather than force them to change to the ChangeSkin plugin.

**Comment by McLive** [comment]
Which one du you mean? Bungee or Bukkit plugin?

Bukkit currently uses the PlayerJoinEvent and Bungee uses the LoginEvent.

**Comment by Zenya4** [comment]
I am referring to the Bungeecord version. When I disable DisableOnJoinSkins (means get player skin on join), the server lags very hard during a bot attack and CPU is maxed out. When DisableOnJoinSkins is enabled (don't fetch skins on join), the plugin does not work at all on Bungeecord but there is no lag during a bot attack due to our antibot plugin. It is all really strange

**Comment by McLive** [comment]
Which AntiBot plugin to you use?

**Comment by McLive** [comment]
@Zenya4 Please try again if it still happens with the newest version.
