### ISSUE TITLE
unable to load the plugin on sponge

### ISSUE THREAD

**Issue by typicalsmc** [SkinsRestorer/SkinsRestorerX#1107]
## Describe the bug

SkinRestorer unable to load on sponge server

## How can we reproduce what you got?

install plugin on sponge 1.12.2
See error

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Forge
**What version? Do NOT answer LATEST**
forge-1.12.2-14.23.5.2860.jar
spongeforge-1.12.2-2838-7.4.7.jar

* SkinsRestorer: 14.2.3
* Spigot version: 
* Java: 8
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs
 
 debug: https://pastes.dev/xgHm2xPHV3
 log: https://pastes.dev/P4WNuVyKEz

**Comment by xknat** [comment]
Sppongeforge is not supported, see readme for list
