### ISSUE TITLE
Support pandaspigot

### ISSUE THREAD

**Issue by uRyanxD** [SkinsRestorer/SkinsRestorerX#1109]
See: https://github.com/hpfxd/PandaSpigot/issues/44

**Comment by xknat** [comment]
> Checking the SkinsRestorer code I realized that it checks through the getPaperConfig() method but this method is called getPaperSpigotConfig() in 1.8 and earlier versions, the strange thing is the code does not return exception when we use paperspigot 1.8 only in PandaSpigot
References: https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/multiver/paper/src/main/java/net/skinsrestorer/paper/PaperUtil.java#L28
https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0014-Timings-v2.patch#L2817

**Comment by xknat** [comment]
Resolved on pandaspigot side by merged pr https://github.com/hpfxd/PandaSpigot/pull/50
