### ISSUE TITLE
Exception in thread "MultiLib data save"

### ISSUE THREAD

**Issue by DimaSergeew** [SkinsRestorer/SkinsRestorerX#1126]
## Describe the bug
This error occurs every time I stop the server

## How can we reproduce what you got?
Install the latest build of Skinrestorer and stop the server
/stop
**Expected behavior**
-

**Screenshots**
-

## Server information

purpur 1.19.2

**What version? Do NOT answer LATEST**

* SkinsRestorer: SkinsRestorerX-DEV 512
* Spigot version: SkinsRestorerX-DEV 512
* Bungeecord version: SkinsRestorerX-DEV 512
* IF bungee, did you put the plugin on all servers: Yes
* Java: 18

## Logs
https://mclo.gs/5VHSzZE

**Comment by AlexProgrammerDE** [comment]
Hello! Could you send us your current SkinsRestorer jar file and your java version?

**Comment by AlexProgrammerDE** [comment]
Alright thanks for reporting! Will check myself soon.

**Comment by AlexProgrammerDE** [comment]
Could you for reference send your jar file here?

**Comment by xknat** [comment]
@DimaSergeew you did not respond to our last request:
> Could you for reference send your jar file here?

Please let us know if not possible, so we can handle this in a private channel on our discord server!

**Comment by xknat** [comment]
resolved by 2567895faeba863241fd50d1cd9a0574c773a21b
will be fixed when we release hotfix or download our dev build
