### ISSUE TITLE
mc 1.19.3 spigot support

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1133]

**Comment by SuryaRajgor** [comment]
skins and commands (show but not do anything) do not work in spigot 1.19.3 and the plugin load without any issue or error
SR version Dev Build 14.2.4 and also try release 14.2.3

**Comment by xknat** [comment]
> skins and commands (show but not do anything) do not work in spigot 1.19.3 and the plugin load without any issue or error SR version Dev Build 14.2.4 and also try release 14.2.3

For support, join our discord.
our github issues is only for issue tracking
