### ISSUE TITLE
SkinsRestorer 13.5.1 error on DefaultSkins

### ISSUE THREAD

**Issue by LudnicaKiller** [SkinsRestorer/SkinsRestorerX#114]
I have installed latest version of SkinsRestorer on my BungeeCord (BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:a12bb4c:1388 by md_5) server and when I set 
DefaultSkins:
Enabled: true
I'm receiving this errors in console: https://pastebin.com/W5yw06KV
Config.yml: https://pastebin.com/PFqdaaJB

But when I set "Enabled: false" I'm no longer getting this error

**Comment by xknat** [comment]
@LudnicaKiller please try our dev build as we make regular changed that the public 13.5.1 still has problems with. let me know if this version: https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastBuild/artifact/target/SkinsRestorer.jar still has this problem

**Comment by LudnicaKiller** [comment]
And there is one more problem with 13.5.1, around 11AM noone can't join server, it only says "Connecting" and nothing happens. Yesterday I have updated this plugin and today I had that problem.

**Comment by McLive** [comment]
> @xknat And there is one more problem with 13.5.1, around 11AM noone can't join server, it only says "Connecting" and nothing happens. Yesterday I have updated this plugin and today I had that problem.

Can you please show your full serverlog containing the issue at 11AM?

**Comment by LudnicaKiller** [comment]
https://pastebin.com/HEYp82t8

**Comment by LudnicaKiller** [comment]
11.01 00:28:50 [Server] INFO [SkinsRestorer] Switching to Mojang to get UUID. (rangerv)
11.01 00:28:50 [Server] SEVERE skinsrestorer.shared.utils.MojangAPI$SkinRequestException: SkinsRestorer | Premium player with that name does not exist.
11.01 00:28:50 [Server] SEVERE at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:134)
11.01 00:28:50 [Server] SEVERE at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:145)
11.01 00:28:50 [Server] SEVERE at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:31)
11.01 00:28:50 [Server] SEVERE at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:75)
11.01 00:28:50 [Server] SEVERE at skinsrestorer.bungee.commands.AdminCommands.lambda$execute$0(AdminCommands.java:69)
11.01 00:28:50 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
11.01 00:28:50 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11.01 00:28:50 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11.01 00:28:50 [Server] SEVERE at java.lang.Thread.run(Thread.java:748)
11.01 00:28:52 [Server] INFO [SkinsRestorer] Switching to Mojang to get UUID. (bllk)
11.01 00:28:55 [Server] INFO [SkinsRestorer] Switching to Mojang to get UUID. (rangerv)
11.01 00:28:55 [Server] SEVERE skinsrestorer.shared.utils.MojangAPI$SkinRequestException: SkinsRestorer | Premium player with that name does not exist.
11.01 00:28:55 [Server] SEVERE at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:134)
11.01 00:28:55 [Server] SEVERE at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:145)
11.01 00:28:55 [Server] SEVERE at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:31)
11.01 00:28:55 [Server] SEVERE at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:75)
11.01 00:28:55 [Server] SEVERE at skinsrestorer.bungee.commands.AdminCommands.lambda$execute$0(AdminCommands.java:69)
11.01 00:28:55 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
11.01 00:28:55 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11.01 00:28:55 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11.01 00:28:55 [Server] SEVERE at java.lang.Thread.run(Thread.java:748)

**Comment by McLive** [comment]
And you can't join the server when that happens?

**Comment by LudnicaKiller** [comment]
No, this is the error when player with no premium set some skin (premium)

**Comment by xknat** [comment]
Just remove rangerv from your default skims and problem solved. rangerv is not premium ofc it will show up an error.. 

Also if your using default skins you can set the skin to never expire on the 3th line so it still works if the playername is already gone

**Comment by LudnicaKiller** [comment]
rangerv is not on my default skins..

**Comment by McLive** [comment]
All the errors posted here are fixed in the most recent version. You can downlaod it from [Jenkins](https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar).

If not, please open another issue.
