### ISSUE TITLE
SkinsRestorer stopped working after latest update

### ISSUE THREAD

**Issue by benjathje** [SkinsRestorer/SkinsRestorerX#1156]
The previous version of SkinsRestorer I was using stopped showing up on the /plugins list. Restarted the server and still not working. So I updated to the latest version and now the plugin does show up but commands return no output and the plugin is unusable.

![image](https://user-images.githubusercontent.com/26327698/209021716-f4f6fd2e-0597-44f0-939c-502fae2250bc.png)

Bukkit

* SkinsRestorer: 14.2.4
* Spigot version: 1.12.2
* Bungeecord version:
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot: SkinsRestorer
* MinecraftLauncher?: Prism Launcher
* if multiverse, (censored) worlds file:

[latest.log](https://github.com/SkinsRestorer/SkinsRestorerX/files/10282419/latest.log)

**Comment by Ijdtm7** [comment]
yea the autoupdate broke for me, it downloaded a version of skinsrestorer that was only 1 KB in size that didn't work but it works now that i manually downloaded from spigot

**Comment by xknat** [comment]
Github is not for support.
Please join our discord or contact stream on spigotmc
