### ISSUE TITLE
My skin not updating in this plugin

### ISSUE THREAD

**Issue by MAGENDOT** [SkinsRestorer/SkinsRestorerX#1159]
I have a licensed microsoft account. And I play on the server where this plugin is. But I changed the skin a long time ago, but the plugin still thinks that I still have the old skin. Although the skin has changed on NameMC, there is no difference. I tried on my server, same effect. This is easy to check, because on Hypixel and other servers, everything is fine and my skin is displayed correctly.

**Comment by xknat** [comment]
github is not for support, if you want support please join our discord or contact us on our spigot page
