### ISSUE TITLE
Server froze

### ISSUE THREAD

**Issue by Nishh** [SkinsRestorer/SkinsRestorerX#116]
### Describe the problem in a few short sentences
Server froze for 8 min
### How can we reproduce the problem?
Don't know
### What version of SkinsRestorerX are you using?
13.5.2
### What is your Spigot/BungeeCord/Sponge version?
Paper-1104 (1.11.2)

Stacktrace at froze:
https://textsaver.flap.tv/lists/2gas

**Comment by xknat** [comment]
If you dont know how to reproduce it, and you only give us a error, than how do we know if this "Server froze for 8 min" is even SkinsRestorer related? was it on the same time the error happend??

i know the Description should be short... not this short

**Comment by Nishh** [comment]
"Stacktrace at froze"

Full stacktraces for every quarter second at froze: http://217.182.196.143/log.txt

**Comment by xknat** [comment]
@Nishh what skinsrestorer version are you using?

**Comment by Nishh** [comment]
"### What version of SkinsRestorerX are you using?
13.5.2"

**Comment by xknat** [comment]
@Nishh can you check if this version resolved your problem? its the upcoming 13.6!
https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/

**Comment by xknat** [comment]
no response, user should update
