### ISSUE TITLE
Exception in task net.skinsrestorer.shared.commands.ISkinCommand$$Lambda by plugin SkinsRestorer

### ISSUE THREAD

**Issue by DimaSergeew** [SkinsRestorer/SkinsRestorerX#1166]
## Describe the bug

I downloaded the latest build of Skin Restorer from Jenkins today, and this bug keeps popping up in Velocity

## How can we reproduce what you got?

I don't know

**Expected behavior**

**Screenshots**
-

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
PurPur

**What version? Do NOT answer LATEST**

* SkinsRestorer:
* Spigot version: 1.19.2
* Velocity version: 1.19.2
* IF bungee, did you put the plugin on all servers: Yes
* Java: 19
* plugin list bungee & spigot:
![Screenshot_3](https://user-images.githubusercontent.com/75163645/209949284-0df2020b-350c-4b88-9ac8-a63330e056e8.png)
* MinecraftLauncher?: ?
* if multiverse, (censored) worlds file: -

## Logs
https://pastebin.com/81QJjX4b

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
[https://gist.github.com
https://hastebin.app](https://pastebin.com/81QJjX4b)

**Comment by AlexProgrammerDE** [comment]
Fixed by https://github.com/SkinsRestorer/SkinsRestorerX/commit/d8403746e24b308556587129dd38a172cad29bd8
