### ISSUE TITLE
The wiki points to an incorrect link

### ISSUE THREAD

**Issue by HowieHz** [SkinsRestorer/SkinsRestorerX#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

in https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Configuration#default-config

' https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/shared/src/main/resources/config.yml ' is the correct link

but here link to ' https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/src/main/resources/config.yml '  

### SkinsRestorer Version

14.2.4

### List of plugins

None

### Java Version

None

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Thanks, fixed
