### ISSUE TITLE
Validate if timestamp of skin is newer before updating / applying

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1202]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

example:
1. player runs /skin update to get new data from mojang
2. skin expires  (skinsexpreafter)
3. player rejoins --> skin is put back to old skin (if main api is not updating skins)

**Comment by AlexProgrammerDE** [comment]
done https://github.com/SkinsRestorer/SkinsRestorer/blob/0102d41cf9f42d970eb79269b7f4be39f17447b9/shared/src/main/java/net/skinsrestorer/shared/storage/SkinStorageImpl.java#L116
