### ISSUE TITLE
[Bug/Readme.md] Velocity

### ISSUE THREAD

**Issue by 8MiYile** [SkinsRestorer/SkinsRestorerX#1208]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/README.md?plain=1#L45
Velocity Link is error
because this link is forwarding forum.papermc.io

**Comment by AlexProgrammerDE** [comment]
Resolved by https://github.com/SkinsRestorer/SkinsRestorerX/commit/7754ca6b2441cac70ce47a8b50aa43afcae677b4
