### ISSUE TITLE
Add a option to prevent updating a skin.

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1211]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

.

**Comment by ghost** [comment]
YEEEEEEEEEES, FOR BUNGEECORD THIS IS GOOD FEATURE

**Comment by AlexProgrammerDE** [comment]
`/sr createcustom <playername> <playername>`
Makes it so when you run `/skin <playername>`, you get the skin that was custom stored when you ran createcustom. So if `<playername>` updates their skin on mojang, the old skin remains for users that explicitly set their skin after createcustom was done.
