### ISSUE TITLE
Velocity JVM Error

### ISSUE THREAD

**Issue by Lairon1** [SkinsRestorer/SkinsRestorerX#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

When installing the plugin on Velocity, an error occurs from the JVM. There is no error without the plugin.
At the same time, there is no error on the Paper server.

### How can we reproduce what you got?

Perhaps the problem is in the jvm, but at the same time everything is fine on the paper server.

### Server/Error Logs

https://gist.github.com/Lairon1/9ad4863bc526fffd1801be48d9fcbe70

### Minecraft implementation

```markdown
Velocity Version: 3.2.0-SNAPSHOT-230 (latest)
```

### What client are you using?

-

### SkinsRestorer Version

14.2.8

### List of plugins

ajQueuePlus-2.2.9.jar AuthMeVelocity-2.0.0-SNAPSHOT.jar  BotSentry-9.5.1-THANATOS-SpigotMC.jar  CommandSync-2.8.2-RELEASE.jar  limboapi-plugin-1.0.6-jdk17.jar LuckPerms-Velocity-5.4.25.jar  minimotd-universal-2.0.7.jar MySQLDependency.jar  servergui-1.0-jar-with-dependencies.jar SkinsRestorer.jar  velocity_tools-1.1.7.jar

### Java Version

JVM: Zing 64-Bit Tiered VM Zing22.07.1.0+1 (17.0.4-zing_22.07.1.0-b1-product-linux-X86_64, mixed mode)

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
The java programming language appears to restrict a functionality of the plugin. You should try using a different java version based on java 17. 
SkinsRestorer currently has the next major release (v15) in development, which already has this issue fixed by not accessing a specific java functionality. We will let you know once SkinsRestorer v15 is ready for public use.

**Comment by Lairon1** [comment]
Thank you, I'll wait for the new version
