### ISSUE TITLE
Enhancement for custom skins

### ISSUE THREAD

**Issue by i0xHeX** [SkinsRestorer/SkinsRestorerX#122]
Uploading custom .skin files is very nice and easy feature, but have several issues in common usage, some of them:
- Should be named only as premium nickname
- Can be updated / being reset by general users wih permission to update
- Limited amount, overlapping with real nicknames.

My suggestion is to add another command argument (or command flag for set argument) to flag that we set custom skin and not one of existing premium account. In that case we can add separate folder with custom named skin files and set skins by id (name). I imagine it as:
1. `/skin set-custom <name>`
2. `/skin custom <name>`
3. `/skin set -c <name> `

**Comment by xknat** [comment]
Hey there!
This is a follow up on this issue, did point out the following drawbacks that were on older vversions:
> Should be named only as premium nickname

Has been resolved
> Can be updated / being reset by general users with permission to update

having a skin with time 0 will now mark it as disable for update.

> Limited amount, overlapping with real nicknames.
i don't think this is going to be a possibility, and even if it overlaps, a workaround is using skinurl.
