### ISSUE TITLE
Suggestion: Export skins as PNG

### ISSUE THREAD

**Issue by Samuelva** [SkinsRestorer/SkinsRestorerX#124]
Hello,

It would be nice to have an option that could export the skins of all players to a specified location in PNG format (preferably `<playername>.png` formatted) , ideally whenever someone changes their skin and joins the server.

The reason for this is that dynmap has the option to set a custom skin-url from which it retrieves all the player skins. By setting up a simple webserver in a directory, and pointing the skin-url option to http://0.0.0.0:port/directory, one could host the skins themself without relying on other sites for retrieval and show skins on dynmap even in offline mode.

Unfortunately this isn't possible at the moment as SkinsRestorer doesn't have a (automatic) skin export option.

Cheers.

**Comment by xknat** [comment]
the thing is that the .png link is already in the .skin file (base64 -> mojang skins)
A script should do the work... i doubt a lot of owners want this. if they do they could make a script or get the stuff from skinsystem.

**Comment by xknat** [comment]
might be better to request at https://github.com/riflowth/SkinSystem

**Comment by ITZVGcGPmO** [comment]
as of SkinSystem 1.7 you can access raw skin data through `/resources/server/skinRender.php?format=raw&dl=true&user=<username>`

**Comment by aljaxus** [comment]
#142

**Comment by pyro000** [comment]
> as of SkinSystem 1.7 you can access raw skin data through `/resources/server/skinRender.php?format=raw&dl=true&user=<username>`

I tried that right now with my website and "/resources/server/skinRender.php?format=raw&dl=true&user=<username>" but It didn't appear anything in dynmap, I suppose that it's because dynmap searchs for a %player%.png. Help me

**Comment by pyro000** [comment]
>I suppose that it's because dynmap searchs for a %player%.png
I guess that the correct is 
`/resources/server/skinRender.php?format=raw&dl=true&user=<username>/%player%.png`
because when I go there throught my website It puts a save with a name like this `_username_-85a2624d.png`

**Comment by xknat** [comment]
https://github.com/webbukkit/dynmap/commit/578c66e2fe6de9e83f9e9ad1b8508a1def97aae1
Dynmap made a commit that should support skinsrestorer.
I hope this helps you out sufficient.
If not please let us know again.
