### ISSUE TITLE
PaperSpigot 1.12.2

### ISSUE THREAD

**Issue by Bonnie20402** [SkinsRestorer/SkinsRestorerX#125]
### Describe the problem in a few short sentences
The /skin set doesn't work. It just doesn't change. Cracked server, everyone is steve/alex

### How can we reproduce the problem?

Doing /skin set <name> or /skin clear
### What is your Spigot/BungeeCord/Sponge version?
PaperSpigot 1.12.2 (Using ProtocolSupport to allow 1.8.1.13.2)

**Comment by Bonnie20402** [comment]
Version is latest (forgot to mention)

**Comment by McLive** [comment]
Is this issue still a thing?

**Comment by xknat** [comment]
@Bonnie20402 ^

**Comment by McLive** [comment]
No response
