### ISSUE TITLE
Not working when running a multi-layer proxy?

### ISSUE THREAD

**Issue by DressyLemon** [SkinsRestorer/SkinsRestorerX#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### **Single Proxy**

When connecting with a single proxy in-front of my paper server it work amazingly! Without an issue this works! - I could not fault the performance and simplistic of this plugin.

### **Multiple Proxies**

I have a multi-proxy setup to move players between different regions without re-joining, running and REDIS environments and any DNS LoadBalancers. I want to incorporate and prove the ability of using Multi-layer proxies and show it is possible for anyone to do! - SO FAR it is 90% successful even whilst using other things like Geyser! My only let down now is SkinRestorerX :( 

**Running on First-Level Proxy:**

As soon as I add my first-layer proxy. Running on OSI Level 7 ( it is just a standard BungeeCord server ) all hell breaks loose! It wont even connect me to my second proxy unless the configuration is configured to prevent the skin from updating when joined! Now when I disable this nothing happens which we'd expect. I can run commands but nothing happens, which in this case, I did expect. I would prefer to run it here but I don't mind running it on the second level proxy.

**Running on Second-Level Proxy:**

 This setup just doesn't work. Commands work that is all.

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### SkinsRestorer Version

Latest

### List of plugins

SkinRestorerX

### Java Version

JDK 11

### Does your issue require a plugin in order to reproduce?

Yes

**Comment by xknat** [comment]
Hey there!
For support. Please join our discord!
Our github issue is for confirmed bug's only.
