### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by dinfyru** [SkinsRestorer/SkinsRestorerX#126]
Plugin v13.6.2
Spigot v1.13.2
Bungee #1402 (06.04.2019 8:54:54)
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

Error
```
18:23:23 [SEVERE] java.lang.NoSuchFieldException: modifiers
18:23:23 [SEVERE]     at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
18:23:23 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.setFieldAccessible(ReflectionUtil.java:169)
18:23:23 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.getField(ReflectionUtil.java:63)
18:23:23 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.setObject(ReflectionUtil.java:175)
18:23:23 [SEVERE]     at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:65)
18:23:23 [SEVERE]     at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:83)
18:23:23 [SEVERE]     at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:165)
18:23:23 [SEVERE]     at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:132)
18:23:23 [SEVERE]     at skinsrestorer.bungee.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:122)
18:23:23 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
18:23:23 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
18:23:23 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:23:23 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by dinfyru** [comment]
Any updates?

**Comment by xknat** [comment]
@McLive

**Comment by McLive** [comment]
No, we currently don't support Java 12.

It's planned

**Comment by ie900** [comment]
**You can use it:**
https://github.com/ie900/UnLoki

**Comment by McLive** [comment]
> **You can use it:**
> https://github.com/ie900/UnLoki

Can you elaborate or create a pull request maybe? :)

**Comment by ie900** [comment]
It's so easy. Like this:
```java
import li.cock.ie.reflect.*;

...

private static DuckBypass reflect;

static {
    reflect = new DuckBypass;
    ...
}

...

private static void setFieldAccessible(Field f) {
    reflect.setEditable(f);
}

...
```
But it is better to use setValue for a static final field instead of editing the modifier.
Like this:
```java
...
public static void setObject(Class<?> clazz, Object obj, String fname, Object value) throws Exception {
    reflect.setValue(clazz, fname, obj, value);
}
...
```
See DuckBypass for all required actions.

**Comment by ie900** [comment]
The efficiency of the library was proved by patching Minecraft Forge (for 1.5.2 and 1.12.2).
But patches are not laid out due to the fact that many mods themselves use the sun.reflect.* or Field.modifiers. (But not under 1.5.2).
My MC with 136 mods under 1.5.2 works fine with my library under OpenJDK 13-EA.

**Comment by McLive** [comment]
Tbh I never really used refelctions and haven't looked into this issue for now.

So using your library instead fixes minecraft 1.8 and newer with java 8 and newer?

**Comment by ie900** [comment]
> Tbh I never really used refelctions and haven't looked into this issue for now.
> 
> So using your library instead fixes minecraft 1.8 and newer with java 8 and newer?

And below.
![Screen](https://user-images.githubusercontent.com/48254041/57546989-bb734000-736e-11e9-9529-eb4e72ff5624.png)
Changed `cpw.mods.fml.relauncher.FMLRelauncher` (1.5.2) and `net.minecraftforge.common.EnumHelper` (`net.minecraftforge.common.util.EnumHelper` for versions above).

**Comment by McLive** [comment]
Ok cool, I'll try to take a look at it!

**Comment by McLive** [comment]
@ie900 Awesome, I implemented it and it works great :) Thanks for sharing!
