### ISSUE TITLE
Option for using a custom Minecraft skin API.

### ISSUE THREAD

**Issue by D3adPlays** [SkinsRestorer/SkinsRestorerX#1268]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Hello 👋,
I recently encountered a slight problem when configuring SkinsRestorerX as there was no option to configure SkinsRestorerX to use custom Minecraft skin API.
This feature would be helpful for advanced users, in case they want to use their infrastructure.

**Comment by xknat** [comment]
@D3adPlays build a custom fork of the project.
