### ISSUE TITLE
Custom Skins get Replaced

### ISSUE THREAD

**Issue by promorrom** [SkinsRestorer/SkinsRestorerX#127]
### what SkinsRestorer version are you using? (make sure its latest!)
13.6.2

### Describe the problem in a few short sentences
I upload custom skins with help of the SkinFile Generator.
I reload the plugin and it works.
But when the server restarts, the custom skins get replaced

### How can we reproduce the problem?
Just do what I said before.
Upload customskins and then restart the server. They get replaced.
Also, on Discord, the user [NL]knat tried to help me, you can ask her/him if she/he knows something more.
If you need more info you can ask me.

### What is your Spigot/BungeeCord/Sponge version?
I'm using PaperSpigot git-Paper-1597

**Comment by McLive** [comment]
I guess that's because custom skins get preloaded on server start. We might have to check for that skinsexpire config values there.

Even better would be to implement full custom skins support. That whould take a while, tho.

**Comment by promorrom** [comment]
Yes, I'm using them as default skins.

**Comment by promorrom** [comment]
# Time skins are stored in database before we request again (in minutes)
SkinExpiresAfter: 180

**Comment by xknat** [comment]
This issue seems to be since (or before) 13.3
The default skin setting ignores the epo (3rd line of .skin file) time given with the SkinExpiresAfter.
This means that the custom skins wont work if it started up with the defaultskins setting on at startup.

starting up without and using reload to turn it on is the current work around.

**Comment by xknat** [comment]
A lot more info is needed regarding this issue. It did work without a problem in the past and we were able to put in custom skins in the default skins back in the days.

It seems like we are also asking the api for every skin while for some skins skinsexpireafter is still not past the set time.
If we wish to:
- improve custom skins
- reduce api request
- improve redundancy by offering skins if they are cached that can not be requested again. 

More investigation needs to be done in the older versions of the plugin to see what changes lead to this issue.

**Comment by xknat** [comment]
Update:
3d1c3a512e682250e4bbe6bca640a9ff4c311413 works
it seems to be that we are now directly requesting skins (mojangapigen uuid & skin + setSkinData) without using skinstorage to check for excising nonoutdated skin.
Also,  the difrerence between `getSkinData` & `getOrCreateSkinForPlayer` is rather vage.

steps to take:
1. look which method takes which and why? -> diff between the 2??
2. make sure all methods use skinstorage and not mojang api. skinstorage should manage that!
3. add a way to "flag" custom skins in the database.

from there we can see what we do with custom skins.

**Comment by xknat** [comment]
Issue seems to come from here: https://github.com/SkinsRestorer/SkinsRestorerX/blob/002a4d41dd58cf2ad48f2c99d669aae5a3f9405a/src/main/java/skinsrestorer/bungee/commands/SkinCommand.java#L196
I would need to list and visualize all the command and flow of getting, setting and applying with non and forced update and silent and non silent.
as well as adding that "flag" like i did mention above

**Comment by xknat** [comment]
Fixed by https://github.com/SkinsRestorer/SkinsRestorerX/commit/80bec1908fbde93c40fe1488cb125a272b4c7d83
but Skin update & custom skins  is still issue (https://github.com/SkinsRestorer/SkinsRestorerX/issues/308)
