### ISSUE TITLE
The skin doesn't change when I enter the command.

### ISSUE THREAD

**Issue by DotTS365** [SkinsRestorer/SkinsRestorerX#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

I used this plugin in Minecraft 1.18 and typed the command [/skin set ~] and the skin did not change.
Furthermore, [/skins] opens a menu, but I can move items in that menu to my inventory.

### How can we reproduce what you got?

1. Plug-ins have been introduced.
2.[/plugins] confirmed that it is installed
3. confirmed the command at [/skin help
4. typed [/skin set "name of my favorite youtuber"].
5. the icon in the TAB list changed skin, but I myself did not.

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### SkinsRestorer Version

14.2.10

### List of plugins

NickNames,SkinsRestorerX

### Java Version

18

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Can you try our v15 branch?
