### ISSUE TITLE
BungeeCord was crashing while SkinRestorer plugin was using UnsafeImpl to setValue

### ISSUE THREAD

**Issue by KleeLoveLife** [SkinsRestorer/SkinsRestorerX#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

I always use Zing OpenJDK because the better performance,but it didn't support skinrestorer.It's a great pity.

### How can we reproduce what you got?

1. Install a openjdk named "Zing"
2. Make a BungeeCord Server
3. Put SkinRestorer into Plugin Folder
4. Start bungeeCord

### Server/Error Logs

https://bin.birdflop.com/raw/ipiciyagax

### Minecraft implementation

```markdown
- Proxy: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a17d8f8:1634
- Backend:
```

### SkinsRestorer Version

14.2.9

### List of plugins

Luckperm,SkinRestorer

### Java Version

OpenJDK 11 ZingVM

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
v15 fixes this issue by dropping all use of unsafe. v15 is right now not stable and some features are missing like the GUI and migration, but you can already download it from the jenkins ci: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer-v15/
