### ISSUE TITLE
Support for minecon/custom capes

### ISSUE THREAD

**Issue by n0grief** [SkinsRestorer/SkinsRestorerX#128]
If possible can support for capes be added? If this is possible would it also be possible to add support for custom capes that are uploaded to the server by the host? A permissions node for the command to apply a cape to yourself would also be quite useful, potentially for a donator perk?

**Comment by McLive** [comment]
It's not possible to add custom capes to a skin, however you can change your skin to one which already has a cape.

**Comment by xknat** [comment]
not possible to edit by plugin, you would need a mod for this, be it server or client side.
