### ISSUE TITLE
SkinsRestorer failing to get release info

### ISSUE THREAD

**Issue by MonstahGames** [SkinsRestorer/SkinsRestorerX#129]
### what SkinsRestorer version are you using? (make sure its latest!)
13.7.0-SNAPSHOT

### Describe the problem in a few short sentences
When letting the server run for a few hours, over time, warnings will appear in the console about SkinsRestorer.
`[WARNING] [SkinsRestorer] Failed to get release info from api.github.com.`
### How can we reproduce the problem?
Let the server run for a bit
### What is your Spigot/BungeeCord/Sponge version?
CraftBukkit version git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by aljaxus** [comment]
You're getting this message because SkinsRestorer can't access `api.github.com` address through ports `80` (http) and `443` (https).

There is an option in SkinsRestorer's config to disable update checking ( `Updater.Enabled` ), but it is currently ignored by the plugin.

- Reference conversation in SR's Discord support channel ~ [link](https://discordapp.com/channels/186794372468178944/186794372468178944/580103492375412770)

**Comment by MonstahGames** [comment]
I figured it had something to do with updating checking, but i'm guessing the warning itself would be an issue, right?

**Comment by aljaxus** [comment]
Well... did you change anything with SR or just update the server `.jar` ?

**Comment by MonstahGames** [comment]
I update my spigot on every dev build, but for SR I just used the 13.7.0-SNAPSHOT

**Comment by aljaxus** [comment]
Please try out the latest development build ([download](https://ci.freecraft.eu/v2/job/SkinsRestorerX/83/artifact/target/SkinsRestorer.jar))

**Comment by MonstahGames** [comment]
I was running this version before, still getting the same Warning

**Comment by aljaxus** [comment]
Well anyhow, the message is printed to console, because, as already mentioned, SR can not access `api.github.com`. This is probably caused because of firewall rules being set and blocking traffic over ports 80 and 443.

Are you using pterodactyl panel or Docker for your servers ?

**Comment by MonstahGames** [comment]
Nope, afaik port 80 and 443 should be good to go, But i could be wrong. I'll get back to you if i find a solution.

**Comment by xknat** [comment]
and 53? dns?

**Comment by MonstahGames** [comment]
I checked my ports, turned out both port 80 and 443 had been wiped it's settings. Weird
Closing, thanks for the help!

**Comment by aljaxus** [comment]
No. There's no way to disable update checking except for that boolean setting in config file
