### ISSUE TITLE
Add sound to SkinRestorerX

### ISSUE THREAD

**Issue by breezefps** [SkinsRestorer/SkinsRestorerX#1292]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Add sound to the GUI and when you change the skin, just a UX feature that can be useful for a couple of people that like sounds on their server,

GUI_CLICK_SOUND =
SKIN_CHANGE_SOUND=

**Comment by xknat** [comment]
Any proposed sound? @breezefps 
So we can set it as a default value

**Comment by AlexProgrammerDE** [comment]
Done
