### ISSUE TITLE
Skins not showing at all Spigot Paper 1.14.2

### ISSUE THREAD

**Issue by J-eremy** [SkinsRestorer/SkinsRestorerX#130]
### what SkinsRestorer version are you using? (make sure its latest!)
13.7.0-SNAPSHOT

### Describe the problem in a few short sentences
Skins aren't changing at all.  The plugin seems to be functioning behind the scenes and says the skin has been updated but doesn't show in game even after relog.

### How can we reproduce the problem?
use paper spigot git version 55 and install plugin

### What is your Spigot/BungeeCord/Sponge version?
Spigot Paper: git-Paper-55 (MC: 1.14.2)

**Comment by xknat** [comment]
can you try turning on the config option multibungee in the skinsrestorer config and RESTART your server?

**Comment by J-eremy** [comment]
> can you try turning on the config option multibungee in the skinsrestorer config and RESTART your server?

I actually fixed it, I am in fact behind a proxy and as soon as I installed it on the proxy along with it on the server it auto magically started working.  Now the question I have is do I have to have it installed on both the proxy and the server or will it work just being on the proxy?

**Comment by aljaxus** [comment]
By saying "proxy", do you mean an actual network-proxy or something like BungeeCord?

If you're talking about bungeecord - yes. You do need to have SkinsRestorer in both, Bungeecord and spigot `./plugins/` folder.
When you have it installed on both bungeecord and spigot the only config files that matter are the ones on bungeecord. Spigot will be in this case ignored.
