### ISSUE TITLE
Issue with skina

### ISSUE THREAD

**Issue by VulnPresence** [SkinsRestorer/SkinsRestorerX#1309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

So i downloaded the plugin and everything fantastic but when I have completed configuring server and go set up my skin etc. then i discovered that when i type /skin url <url of skin> CLASSIC its not seting the skin. When i type skin set <nick> its not seting the skin too btw i discovered another thing i have skin of joker i dont know where i got it and my test account have another skin in Game instead of the skin im looking at and its on me the same so i dont know if im doing something wrong or just im that stupid. Please answer cuz i want to know what is the problem. 

### Minecraft implementation

```markdown
Normal paperspigot 1.19.4 server.
```

### What client are you using?

T-launcher

### SkinsRestorer Version

14.2.10

### List of plugins

Like 35, a lot of plugins 

### Java Version

Java openjdk 17

### Does your issue require a plugin in order to reproduce?

None

**Comment by ZackLackinJava** [comment]
Firstly, don't leave "no response" to the questions, and I've noticed you added how to reproduce this bug to "Describe your issue", Secondly, you have blank fields, please send (Server Logs/Error Logs), Lastly, update to the latest version. https://www.spigotmc.org/resources/skinsrestorer.2124/update?update=504049 <----

**Comment by xknat** [comment]
^
