### ISSUE TITLE
java.lang.NoSuchFieldException: no such field: net.minecraft.server.level.EntityPlayer.b/net.minecraft.server.network.PlayerConnection/getField

### ISSUE THREAD

**Issue by DexterSK** [SkinsRestorer/SkinsRestorerX#1315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

After opening player warps /pw warning is thrown

### How can we reproduce what you got?

1. Open Player warps /pw

### Server/Error Logs

https://gist.github.com/DexterSK/a674a5fa24dddfc21459dc6e58b9e486

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### What client are you using?

TLauncher

### SkinsRestorer Version

14.2.12

### List of plugins

pwarps

### Java Version

can't execute command

### Does your issue require a plugin in order to reproduce?

Yes

**Comment by TadaClip** [comment]
i have the same issue, Its probably on the playerwarps side since no other plugin that uses heads sends that alert, also it only sends the warning once and not the other times, it seems that it does not affect anything in both plugins

**Comment by xknat** [comment]
We only provider support for latest dev build here.

**Comment by DexterSK** [comment]
> since no other plug

nah, its on skinsrestorer as you can see on callstack.
at SkinsRestorer.jar//net.skinsrestorer.shadow.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:133)

**Comment by DexterSK** [comment]
> We only provider support for latest dev build here.

i will try to use dev version thx.
