### ISSUE TITLE
Catch brackets that are shown in /skin help

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1317]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I hate to say this but, there are some people in v15 that will do 
![image](https://github.com/SkinsRestorer/SkinsRestorerX/assets/10220139/14481154-39b0-4865-ae2a-d65d3331d70c)

**Comment by AlexProgrammerDE** [comment]
Resolved by https://github.com/SkinsRestorer/SkinsRestorerX/commit/c081a14835c6dfd87af1afd4d8c3174dc93cec88
