### ISSUE TITLE
Wrong release title

### ISSUE THREAD

**Issue by Nymphxyz** [SkinsRestorer/SkinsRestorerX#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

Yes

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Should be 1.20.2.

![image](https://github.com/SkinsRestorer/SkinsRestorerX/assets/65056401/d893f8cb-3e13-43d6-a20d-42ffafd7103f)

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### SkinsRestorer Version

14.2.4

### List of plugins

None

### Java Version

17

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
Thanks, updated
