### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by daniel-skopek** [SkinsRestorer/SkinsRestorerX#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

https://pastebin.com/raw/bFKw7P8q

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### SkinsRestorer Version

14.2.13

### List of plugins

SkinsRestorer

### Java Version

OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Please use v15
Open a new ticket
