### ISSUE TITLE
Error occurred while enabling SkinsRestorer

### ISSUE THREAD

**Issue by Acult** [SkinsRestorer/SkinsRestorerX#137]
Error link:
https://pastebin.com/vhm0hQAv

Plugin version: SkinsRestorer v10.4.4 (latest build for my version)
Server: Thermos 1.7.10

**Comment by McLive** [comment]
Looks like you are using a newer Java version? Please try again with Java 8.

**Comment by Acult** [comment]
It's Java 8 with ASM5

**Comment by McLive** [comment]
Please try our latest version from Jenkins. We can't support custom builds.

**Comment by Acult** [comment]
>Please try our latest version from Jenkins

Where do i get it?

**Comment by McLive** [comment]
https://ci.freecraft.eu/v2/job/SkinsRestorerX/

**Comment by Acult** [comment]
@McLive 
The plugins is now enabled but no skins is changed and everyone is steve

**Comment by xknat** [comment]
@Acult we dont support 1.7

**Comment by Acult** [comment]
Damn can't an exception be made?

**Comment by xknat** [comment]
of course, feel free to fork and make it working on 1.7.10 (or just use a mod that is designed for 1.7 in the archives because 1.7.10 is older than my phone right now)

**Comment by Acult** [comment]
The plugin works, but skins won't load, here the cause:
https://pastebin.com/6PbeiVZX

If someone knowns how to fix, please help

**Comment by xknat** [comment]
[SkinsRestorer] Trying Mojang API to get skin property for cb6545e34f45488b8d0585b3abe53724.
it says it cant connect to mojang api, check port 80 443 and 53

**Comment by xknat** [comment]
thats like https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/tree/ad24b0a32fc4ddfc6e860f3361c1b1ec4a1b1c62
but we did support 1.7.x after that version. above is the link to the old github before we moved to this one. in there is the old source code. feel free to use that one and check for a commit we once did to fix the api changes. it should help if you know how to code. if not contact us on discord.

**Comment by Acult** [comment]
Well I don't really know how to code, anyways, is this the fix for the api?
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/9358d5727cfc7a1dce4e2af9412679999be5b519/src/main/java/skinsrestorer/shared/utils/MojangAPI.java

**Comment by xknat** [comment]
@Acult https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/pull/223/files
