### ISSUE TITLE
"SkinWithoutPerm" missing in config.yml

### ISSUE THREAD

**Issue by OverStyleFR** [SkinsRestorer/SkinsRestorerX#1388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Hi,

I would like to deactivate the fact of changing skin for all players and only authorized the "VIP" rank, so I looked for how to do it and you say (in the Wiki) that you have to put this value: SkinWithoutPerm
has "false"
But I can't find this value... The only one I find that comes close is "forceDefaultPermissions: false"

As you can see I have already set this value to "false" but this does not affect the use of this command by players with no permissions.

### How can we reproduce what you got?

1. set "false" on the "forceDefaultPermissions"
2. restart the server
3. See if you can change your skin (users with no permission)
4. Go to luckperms and edit the permissions of "default" set a value "skinsrestorer.command" to "false"
5. now if you do /skin you get a "Unknow command" 
![image](https://github.com/SkinsRestorer/SkinsRestorerX/assets/94577363/a88e39d7-4a3c-4012-9c7c-139ccee2cf0a)
(the command /sr works...)

### Server/Error Logs

https://bin.birdflop.com/ogopowiseg.makefile

### Minecraft implementation

```markdown
- Proxy: NO
- Backend: {"currentVersion":"git-Paper-388 (MC: 1.18.2)"} |
```

### What client are you using?

Prism Launcher

### SkinsRestorer Version

15.0.1

### List of plugins

BanManager, BetterPlayTime, CoreProtect, Essentials, HackedServer, LuckPerms, Maintenance, Orebfuscator, PluginManager, PrivateMessages, ProtocoLib, ServerListPlus, SkinsRestorer, Spark, TAB, UltraSetHome, Vault, ViaVersion, VoidWhitelist

### Java Version

java version "17.0.8" 2023-07-18 LTS Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211) Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
We moved from a config option to permissions based permissions.
You should use deny permission `-` to revoke them

**Comment by OverStyleFR** [comment]
> We moved from a config option to permissions based permissions. You should use deny permission `-` to revoke them

I don't really understand, what i should write for deny permission on the luckperms web interface ? 
Can you show me an example ?

**Comment by xknat** [comment]
> I don't really understand, what i should write for deny permission on the luckperms web interface ? Can you show me an example ?

What do you want to deny?
