### ISSUE TITLE
External plugins unable to use API v15

### ISSUE THREAD

**Issue by TwlghtDrgn** [SkinsRestorer/SkinsRestorerX#1392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

I've tried to use the v15 API. SkinsRestorer itself loads properly, but any plugin that depend on it is broken. Tested that issue with [SkinsRestorerAPIExample](https://github.com/SkinsRestorer/SkinsRestorerAPIExample), it gives the same error message. If `VersionProvider` is not used, API throws an error saying `SkinsRestorerAPI is not initialized yet! (Are you trying to access it without softDepends?)`.

### How can we reproduce what you got?

1. Download and install/update SkinsRestorer to v15 from the Github releases page
2. Compile SkinsRestorerAPIExample and install it too
3. Start the server
4. In the console you will see the message `Error occurred while enabling SkinsRestorerAPIExample v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/skinsrestorer/api/VersionProvider`

### Server/Error Logs

https://mclo.gs/FyRIbjG 

### Minecraft implementation

```markdown
- Proxy: n/a
- Backend: Purpur version git-Purpur-2084 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 85e34e5 on HEAD), Paper version git-Paper-260 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1865625)
```

### SkinsRestorer Version

15.0.2-SNAPSHOT (git-26f171e)

### List of plugins

SkinsRestorer, SkinsRestorerAPIExample, spark

### Java Version

OpenJDK 64-Bit Server VM 17.0.9+8

### Does your issue require a plugin in order to reproduce?

Yes

**Comment by AlexProgrammerDE** [comment]
Interesting, I'll immediately investigate.

**Comment by AlexProgrammerDE** [comment]
The class file is not present in the released jar, but is present on GitHub. Possibly the shadow plugin removed it. I'll look into it.

**Comment by AlexProgrammerDE** [comment]
Fixed by https://github.com/SkinsRestorer/SkinsRestorerX/commit/e5a7b1dfc0fe03f42462b4aacd9f45908f1463d2
