### ISSUE TITLE
SkinsRestorer: skin won't change

### ISSUE THREAD

**Issue by daniel-skopek** [SkinsRestorer/SkinsRestorerX#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

When I change skin using command: /skin set <skin_name> (skin won't change)

### How can we reproduce what you got?

1. Skin change using: /skin set

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### SkinsRestorer Version

v15.0.3

### List of plugins

[23:51:42 INFO]: Plugins (11): PlaceholderAPI, spark, ViaVersion, ProtocolLib, LuckPerms, SkinsRestorer, FastLogin, BungeeGuard, TAB, LPX, Vault

### Java Version

openjdk version "17.0.9" 2023-10-17

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Sounds like BungeeGuard issue, join our discord for support
