### ISSUE TITLE
API to get player's skin

### ISSUE THREAD

**Issue by Iwitrag** [SkinsRestorer/SkinsRestorerX#142]
Hi,

I'm using SkinsRestorer on my offline-mode server and I'm developing small plugin.

When I call method SkullMeta.setOwningPlayer - it works only when player is online (skin working).
But if that player gets offline it doesn't work at all (newly created heads are without skin).

Is there some kind of API to get player's skull from SkinsRestorer? So skin always works.

Thanks!

**Comment by ITZVGcGPmO** [comment]
as of [SkinSystem](https://github.com/riflowth/SkinSystem) 1.7 you can access raw skin data through `/resources/server/skinRender.php?format=raw&dl=true&user=<username>`

**Comment by aljaxus** [comment]
Though you could add a button to the UI when a user is viewing a skin which will open the raw skin in new tab.

**Comment by Iwitrag** [comment]
> as of [SkinSystem](https://github.com/riflowth/SkinSystem) 1.7 you can access raw skin data through `/resources/server/skinRender.php?format=raw&dl=true&user=<username>`

I'm asking rather for API for SkinsRestorer, I'm not user of SkinSystem.

**Comment by xknat** [comment]
And mysql?

**Comment by pyro000** [comment]
> as of [SkinSystem](https://github.com/riflowth/SkinSystem) 1.7 you can access raw skin data through `/resources/server/skinRender.php?format=raw&dl=true&user=<username>`

It doesnt work HELP

**Comment by xknat** [comment]
should be resolved in https://github.com/SkinsRestorer/SkinsRestorerX/commit/a021c5b4758334143a07a421bf2d172150da411e
