### ISSUE TITLE
Skins restorer API not working on proxy mode

### ISSUE THREAD

**Issue by PabloGirol** [SkinsRestorer/SkinsRestorerX#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

When using skinsrestorer-api, if the server is in proxy mode, the api throws an error showing that SkinsRestorerAPI is not initialized yet

### How can we reproduce what you got?

1. Compile SkinsRestorerAPIExample
2. Setup a server behind a proxy like Velocity
3. Error is shown

### Server/Error Logs

https://bin.birdflop.com/muzubizifo.md

### Minecraft implementation

```markdown
- Proxy: Velocity 3.2.0-SNAPSHOT (git-8dcc7ee3-b294)
- Backend: g Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
```

### What client are you using?

Vanilla

### SkinsRestorer Version

15.0.3

### List of plugins

LuckPerms, SkinsRestorer, DeathBan (custom version)

### Java Version

Java 17 (OpenJDK 64-Bit Server VM 17.0.9+9)

### Does your issue require a plugin in order to reproduce?

None

**Comment by PabloGirol** [comment]
Fixed by creating a file called `enableSkinStorageAPI.txt` mentioned at the readme on the backend

**Comment by Xinecraft** [comment]
> Fixed by creating a file called `enableSkinStorageAPI.txt` mentioned at the readme on the backend

Hi @PabloGirol , Can you plz give some reference of it how u got it fixed. 
Thanks.
