### ISSUE TITLE
Cherry Blossom cape support

### ISSUE THREAD

**Issue by kateanf** [SkinsRestorer/SkinsRestorerX#1446]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I play on my cracked server 1.20.2. I use the latest SkinRestorter version. I use an official minecraft account and my cape set to "Cherry Blossom", but on my server it dosent show up, I see the Migration cape instead of it. I don't really know if it's a bug or is it just not implemented.

**Comment by xknat** [comment]
There were some issues with delay on the api we were using. Should work fine now with the new custom API we have.
