### ISSUE TITLE
Consider uploading to Ore

### ISSUE THREAD

**Issue by feikname** [SkinsRestorer/SkinsRestorerX#146]
Please consider adding a page for this plugin in [Sponge's Ore](https://ore.spongepowered.org) repository.

**Comment by ITZVGcGPmO** [comment]
It is a good idea to get SkinsRestorer into Sponge's Ore repo, though [this](https://docs.spongepowered.org/stable/en/ore/guidelines.html?highlight=offline#cracked-offline-mode-online-mode-false-support) may hinder posting and will most likely need to be looked into further before posting.

**Comment by ITZVGcGPmO** [comment]
[ARE YOU HAPPY NOW??](https://ore.spongepowered.org/SRTeam/SkinsRestorer)
