### ISSUE TITLE
custom skins do not show up in gui 

### ISSUE THREAD

**Issue by ForcedComedy** [SkinsRestorer/SkinsRestorerX#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

running the plugin on an aternos server, .customskin files do not show up in the GUI

### How can we reproduce what you got?

1. make custom skin file using skinfile generator
2. upload it in the skins folder on aternos
3. reload
4. open gui
5. not there

### Server/Error Logs

https://mclo.gs/eyRauaD

### Minecraft implementation

```markdown
This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
```

### What client are you using?

Sklauncher

### SkinsRestorer Version

15.0.4

### List of plugins

Essentials, TreeCapitator, DiscordSRV, Minepacks, Geyser-Spigot, LuckPerms, SinglePlayerSleep,

### Java Version

21.0.1

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
@ForcedComedy sorry for the delay, can you show if customGUI is enabled?

**Comment by AlexProgrammerDE** [comment]
Should not be an issue anymore
