### ISSUE TITLE
SR incompatible with future versions of Paper

### ISSUE THREAD

**Issue by kennytv** [SkinsRestorer/SkinsRestorerX#1496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

SR errors on startup due to trying to directly parse the CB relocation version. See https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955 for more info

### How can we reproduce what you got?

https://github.com/PaperMC/testing/releases/tag/no-relocation

### Server/Error Logs

https://bin.birdflop.com/helinakeho.rb

### Minecraft implementation

```markdown
git-Paper-"35f8f3d" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)
```

### SkinsRestorer Version

15.0.4

### List of plugins

Just SR

### Java Version

openjdk 21.0.2 2024-01-16 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Hey there!
Thank you for taking your time to reach out to our project personally.
Due to person (team) time constraints, we have not be as active recently.
I pass this on to @AlexProgrammerDE, he will get back to you.

**Comment by AlexProgrammerDE** [comment]
Interesting, I've read about this in the Paper Discord before, but didn't know how to test it. I'll get onto this.
