### ISSUE TITLE
NullPointer on Skin

### ISSUE THREAD

**Issue by Moocow9m** [SkinsRestorer/SkinsRestorerX#150]
## Describe the bug
The plugin throws a null pointer on login and on and apply command. The skin does not change.

## How can we reproduce what you got?
1. Boot up paperclip.jar using 1.14.4
2. Login

**Expected behavior**
Skin to change and no exception thrown.

## Server information

Linux, PaperSpigot 1.14.4, offline mode.

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.1 and Jenkins build 105
* Spigot/Bukkit/Bungeecord: PaperSpigot
* Java: 11

## Logs
https://hastebin.app/1563607941837

**Comment by xknat** [comment]
We only support Java 8 (openjdk | Oracle Java)

**Comment by McLive** [comment]
Also please provide your full server log for us to look into things

**Comment by Moocow9m** [comment]
@xknat Changing the java version to 8 did the same thing of course( sorry if that sounded rude, just got annoyed)
@McLive Full log here: https://hastebin.app/1563639558422

**Comment by McLive** [comment]
`[SkinsRestorer] Detected Minecraft null`
Looks like it can't detect your minecraft version.. Can you upload it here so I can test with it?

**Comment by Moocow9m** [comment]
Download URL that my system uses: https://www.wav-productions.com:8443/job/Paper/lastSuccessfulBuild/artifact/paperclip.jar

**Comment by McLive** [comment]
![image](https://user-images.githubusercontent.com/5620071/61581309-08b52000-ab1d-11e9-840b-a8c3fb43e21e.png)
I can't really use that :/

**Comment by Moocow9m** [comment]
Oh, sorry lol, I forgot my system used a token login, let me fix that.

**Comment by Moocow9m** [comment]
https://drive.google.com/file/d/1xDjqwbmMRO3WnUo6bszMDbRCzbBN0e3i/view?usp=drivesdk that's the uploaded file since Jenkins doesn't like anonymous user right now.

**Comment by McLive** [comment]
I couldn't get your paperclip.jar to work. It already crashed while starting the server.

I compiled spigot-1.14.4 using BuildTools and SkinsRestorer just works fine there.

![image](https://user-images.githubusercontent.com/5620071/61582001-c04e3000-ab25-11e9-83f0-1ed8892519af.png)

Looks like paperspigot is doing something weird there!

**Comment by McLive** [comment]
Also, using paper-135.jar from https://papermc.io/downloads is also working.

![image](https://user-images.githubusercontent.com/5620071/61582110-e3c5aa80-ab26-11e9-8fde-33746eefade6.png)

Looks like your build is broken.

**Comment by Moocow9m** [comment]
That's odd considering it works perfectly for me. The build is not modified from their 1.14.4 version.

**Comment by Moocow9m** [comment]
@McLive could, you send me the crash report?

**Comment by McLive** [comment]
https://pastebin.com/CRJRqEWw

This build also looks more like 1.14.3.

**Comment by Moocow9m** [comment]
Hmmm, maybe my enviornment isn't clean, I'll look into my workspace and see if it is not cleaning properly

**Comment by Moocow9m** [comment]
It seems I somehow uploaded the wrong version(was an old 1.14.3 build I had), the link should now be updated. That being said the error for the version you had was about ByteBuffer.clear() not returning a proper value, which is not an MC problem, but a java problem... I'll look into that in a bit.

**Comment by Moocow9m** [comment]
It turns out it was a build problem. As I do not support versions below the latest LTS, the server was built in such an environment. While I could still run the build with the old 1.8 LTS release, it seems it broke skin-restorers version detector and reflections. I have made a fork so I could update this behaviour to work the current LTS for myself and anyone else that wants it.

**Comment by McLive** [comment]
Please try this build (https://ci.freecraft.eu/v2/job/SkinsRestorerX/106/), it works on Java 12.

**Comment by Moocow9m** [comment]
testing now

**Comment by Moocow9m** [comment]
Issue Resolved.
