### ISSUE TITLE
Sponge classloading and /skins menu issues

### ISSUE THREAD

**Issue by XXMA16** [SkinsRestorer/SkinsRestorerX#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Skin changing and the skin menu seem to be completely broken. I have tried using the SkinsRestorer-Sponge jar under `build/libs` and that doesn't seem to throw a `NoSuchMethodError`, however changing your skin won't update it automatically (you have to reconnect) and the /skins menu is still broken. The `SkinsRestorer-Sponge-15.0.4.jar` (also locally built) seems to work properly (both skin changing and the menu), however command autocomplete is still broken:

/skin and /skins expect `skin` `skins`  `skinsrestorer` or `sr` as an argument, the autocomplete works properly from there, but you'll end up with an extra `skin` (or whatever the first thing you put in the command was) and the command will have an incorrect syntax

### How can we reproduce what you got?

Barebones SpongeVanilla 1.16.5, 1.19.4 or 1.20.2 with SkinsRestorer 15.0.6

### Server/Error Logs

https://bin.birdflop.com/uyapohanid.csharp

### Minecraft implementation

```markdown
- Proxy: 
- Backend: 
spongevanilla-1.16.5-8.2.0-universal (or spongevanilla-1.19.4-10.0.0-RC1469-universal)
```

### What client are you using?

Vanilla 1.16.5

### SkinsRestorer Version

15.0.6

### List of plugins

SkinsRestorer

### Java Version

oracle jdk 17.0.8

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
> Sponge 
We dropped support for sponge.
