### ISSUE TITLE
Changing skins of offline players

### ISSUE THREAD

**Issue by Biseliss** [SkinsRestorer/SkinsRestorerX#1514]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I think it would be great if you added an opportunity to change skins of players' who are no online
![изображение](https://github.com/SkinsRestorer/SkinsRestorerX/assets/82822106/446ebc43-a67a-4e12-979f-7b5652523fc6)

**Comment by AlexProgrammerDE** [comment]
Hi, you can do that now by supplying a uuid.
