### ISSUE TITLE
Turn off this message prompt [SkinsRestorer] Failed to get release info from api.github.com.  If this message is repeated a lot, please see https://skinsrestorer.net/firewall

### ISSUE THREAD

**Issue by TOYBOXSM** [SkinsRestorer/SkinsRestorerX#1517]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Turn off this message prompt

**Comment by xknat** [comment]
Hey there! We still want people to update the plugin, this is because 90% of the bugs we encounter is from a version older then release.
Therefore, we will keep on sending these...
It is sadly something we have to do till we get more volunteers managing support.
