### ISSUE TITLE
Ashcon api stopped updating after player name change, and we need an option to set primary skin URL source

### ISSUE THREAD

**Issue by hugeBlack** [SkinsRestorer/SkinsRestorerX#1519]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I host a server to play with my friends, which has a poor connection to Mojang auth server, so I disabled online mode while using SkinRestorer as a way to keep skins on. However, after one of my friends changed his name, his skin never updates. So I have to change the skin file everytime he changes his skin.

As the title says, I recently found that, the Ashcon api, which SkinRestorer uses as primary skin URL source, has a bug that player profile stops (or has a huge delay?) to change after the player changed their name.
Consequently, since SkinRestorer queries the Ashcon api with player UUIDs, which won't change after a name change, all skin changes after that won't be tracked by the Ashcon api, thus being unable to sync ingame.

Since the Mojang API (api.mojang.com) is always the one that works correctly, can we have an option to set that as the primary skin URL source?

If you want to reproduce this Ashcon api bug, I can send my friend's UUID and name to you.

**Comment by xknat** [comment]
@hugeBlack resolved with the new mojang api we use called "eclipse".
Use latest release to see the effect!
