### ISSUE TITLE
Forcebungeemode

### ISSUE THREAD

**Issue by McLive** [SkinsRestorer/SkinsRestorerX#153]

**Comment by xknat** [comment]
Could be done with https://github.com/SkinsRestorer/SkinsRestorerX/blob/d49eb25d5109046e258243b862bd7f0ceb901bd5/src/main/java/skinsrestorer/bukkit/SkinsRestorer.java#L336

**Comment by xknat** [comment]
#363 might be related when i add the function to have subservers ask for set config options.

**Comment by xknat** [comment]
Fixed by #420
