### ISSUE TITLE
Unable to disable proxy mode, even if I created disable Proxy Mode.txt

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [SkinsRestorer/SkinsRestorerX#1538]
### Is there an existing issue for this?
This issue was mentioned last year, but no one answered
https://github.com/SkinsRestorer/SkinsRestorerX/issues/1417
- [ ] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

How to turn off proxy mode: create a file called disableProxyMode.txt in SkinsRestorer folder (backend server -> ./plugins/SkinsRestorer/disableProxyMode.txt)
This will force disable proxy mode on next restart.

But I created this TXT according to the instructions and it did not take effect successfully. After restarting the server, it still remains in proxy mode
<img width="375" alt="image" src="https://github.com/SkinsRestorer/SkinsRestorerX/assets/141799770/99a2f2ac-205c-4559-a22d-87070c8b3dc3">
It causes my players to be unable to use the skin button in Chest commands (indicating unknown commands), and they can only manually input commands to use the SkinsRestorer themselves
In other words, the backend server cannot access any instructions for SkinsRestorer (the instruction usage obtained by entering “/help SkinsRestorer” or“? SkinsRestorer” on the backend server is empty), only Water Fall can use the instruction
<img width="271" alt="image" src="https://github.com/SkinsRestorer/SkinsRestorerX/assets/141799770/0e73b4de-998f-4aa3-900c-2065d2072d14">
<img width="327" alt="image" src="https://github.com/SkinsRestorer/SkinsRestorerX/assets/141799770/8e8dd60f-53dc-4515-bee3-10270d9d667e">

### How can we reproduce what you got?

1. Waterfall 
2.Multiple interconnected servers
3.Install SkinRestorer on each server
4.Let's play

### Server/Error Logs

没有

### Minecraft implementation

```markdown
- Proxy: waterfall
- Backend: paper-1.20.2-298
```

### What client are you using?

PCL2

### SkinsRestorer Version

15.0.7

### List of plugins

 AnimatedScoreboard, AuthMe, BetterStructures, ChestCommands,  *ChineseNickName, Citizens, CMILib, *CommandNPC, ConsoleSpamFix, CoreProtect [21:18:22 INFO]:  *Shift_Menu, SkinsRestorer, *Stp, TabTPS, Vault, VeinMiner, Vi aBackwards, ViaVersion, WorldEdit

### Java Version

21

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Did you restart the server?

**Comment by MinecraftEarthVillage** [comment]
> 是否重新启动了服务器？

Yes,I do

**Comment by xknat** [comment]
@Leoparking the file is called disable...txt.text remove duplicate` txt`

**Comment by MinecraftEarthVillage** [comment]
> @Leoparking the file is called disable...txt.text remove duplicate` txt`

But...
<img width="255" alt="image" src="https://github.com/SkinsRestorer/SkinsRestorerX/assets/141799770/5b67347f-6f9b-4443-85a4-4c092053ea33">
Still the same, I might have placed the wrong screenshot

**Comment by xknat** [comment]
> disableProxyMode.txt

It is disableProxyMode.txt
Use copy paste.
You have it still wrong.

**Comment by MinecraftEarthVillage** [comment]
> > disableProxyMode.txt
> 
> It is disableProxyMode.txt Use copy paste. You have it still wrong.

Oh，Sorry I forgot the confusing l, I used the correct file name, there is no problem now, However, this causes the player to use the command, although the prompt skin has changed, but in fact the appearance remains the same.
——————
Close this problem
