### ISSUE TITLE
The skin from the cache is not updated

### ISSUE THREAD

**Issue by VanyaNexus** [SkinsRestorer/SkinsRestorerX#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

If I install a skin by nickname from a license, say test1, then the license skin will be displayed and saved in the cache. Next, if I change the skin on the license to another one, then after 20 minutes if I try to re-login, I still have the same skin as it was, that is, the cache has not been updated, but this is not so important. The important thing is that even if I change the skin to another nickname and then install the test1 skin again, then the old skin from the cache is installed for me. If I log in from another account and also install the test1 skin, then it will also be the old skin, not the new one. If you write /skin update while the test1 skin is applied, the skin is changed to a new one.
Config info:
storage.defaultSkins.enabled = true
storage.defaultSkins.applyForPremium = true
storage.disallowAutoUpdateSkin = true
storage.skinExpiresAfter = 15
storage.uuidExpiresAfter = 60

### How can we reproduce what you got?

1. Set skin by nickname for license, for example test1
2. Change skin on license test1 to another
3. Rejoin after 30 mins and skin not changed to new
4. You can connect from new account and set skin test1 and get old skin

### Minecraft implementation

```markdown
- Proxy: Velocity
- Backend: Paper
```

### What client are you using?

1.16.5

### SkinsRestorer Version

15.0.7

### List of plugins

SkinRestorer

### Java Version

java 17

### Does your issue require a plugin in order to reproduce?

None

**Comment by ytcalifax** [comment]
Facing the same issue, but just on PaperSpigot (Pufferfish), with premium accounts, even on the dev release.

**Comment by xknat** [comment]
There were some issues with delay on the api we were using. can you try again with the current release? 
@ytcalifax @VanyaNexus

**Comment by ytcalifax** [comment]
I already have and it is all working fine now with the new custom API you have. I think we can have this issue closed.
