### ISSUE TITLE
Config option to prevent MojangAPI output

### ISSUE THREAD

**Issue by McLive** [SkinsRestorer/SkinsRestorerX#155]
```14:02:58 [INFO] [SkinsRestorer] Switching to Mojang to get UUID. (xknat)```
spam: https://pastebin.com/CddWcsSY

**Comment by xknat** [comment]
partly done in https://github.com/SkinsRestorer/SkinsRestorerX/commit/7c620036b6971a7d141bda8c17973ea4a6e32cda
