### ISSUE TITLE
Unable to load UPxielanmao's skin

### ISSUE THREAD

**Issue by alazeprt** [SkinsRestorer/SkinsRestorerX#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Unable to load UPxielanmao's skin, it shows that a genuine player using this name does not exist.

### How can we reproduce what you got?

1. join the server
2. skin not loaded
3. using /skin set UPxielanmao, it shows that a genuine player using this name does not exist

### Minecraft implementation

```markdown
- Proxy: Velocity 3.3.0-SNAPSHOT (git-74c932e9-b363)
- Backend: This server is running Leaves version git-Leaves-"0f16c0c" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0f16c0c)
```

### What client are you using?

Hello Minecraft! Launcher v3.5.7.245

### SkinsRestorer Version

15.0.8

### List of plugins

[08:34:47 INFO]: Server Plugins: HuskHomes, Chunky, LiteSignIn, LuckPerms, Matrix, MiniMOTD, Multiverse-Core, PlaceholderAPI, ProtocolLib, SkinsRestorer, TAB, TrChat, Vulcan

### Java Version

docker image "openjdk:17"

### Does your issue require a plugin in order to reproduce?

None

**Comment by alazeprt** [comment]
The skin of "huang_gua_qwq" cannot be loaded too

**Comment by xknat** [comment]
Should now work with the new mojangapi called "eclipse".
When you use latest release of skinsrestorer it should get your skin.
