### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by daniel-skopek** [SkinsRestorer/SkinsRestorerX#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

/skin (set) <skin_name> can be used without permission.

Config: https://pastebin.com/raw/dFYE4617

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### SkinsRestorer Version

15.0.8

### List of plugins

[23:26:57 INFO]: Plugins (19): WDLCompanion, PlaceholderAPI, spark, ViaVersion, TabTPS, ProtocolLib, LuckPerms, DM-Credits, SkinsRestorer, DecentHolograms, BungeeGuard, LPX, Vault, TigerReports, DM-LobbySystem, Citizens, Plan, TAB, DM-SpigotCore

### Java Version

Temurin-17.0.10+7 (build 17.0.10+7)

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Hi there, you need to use negative permissions
for example skinsrestorer.command.set false in luckperms

**Comment by daniel-skopek** [comment]
![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/117641078/a44ffd36-8923-4811-86bc-4daed8e5ccec)
Setting skinsrestorer.command.set to false in LuckPerms didn't fixed the problem. Players without permissions can change skins using /skin <player_name>

Dump: https://bytebin.lucko.me/eed45akHAZ
Config: https://api.mclo.gs/1/raw/51o7c0R

**Comment by xknat** [comment]
> ![image](https://private-user-images.githubusercontent.com/117641078/327977322-a44ffd36-8923-4811-86bc-4daed8e5ccec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTQxODUsIm5iZiI6MTcxNDkxMzg4NSwicGF0aCI6Ii8xMTc2NDEwNzgvMzI3OTc3MzIyLWE0NGZmZDM2LTg5MjMtNDgxMS04NmJjLTRkYWVkOGU1Y2NlYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMTI1ODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAwZTM4YzA3ZTgzMDgwZmZlYzdiODA3MGQwMDhjZGI0NGUxNWM0YjQzYWIxZDRmY2FkN2RlNGM4YTFiNDhlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.720ZCGZhTjdHhkb_BGe4x9Vilr89AZ_b2IWqbmXgSeg) Setting skinsrestorer.command.set to false in LuckPerms didn't fixed the problem. Players without permissions can change skins using /skin <player_name>
> 
> Dump: https://bytebin.lucko.me/eed45akHAZ Config: https://api.mclo.gs/1/raw/51o7c0R

Yes but is luckperms sync to proxy?

**Comment by daniel-skopek** [comment]
Yes, Spigot and Velocity LuckPerms are on the same database (synced).
