### ISSUE TITLE
[Bug] SkinsRestorer reported as a virus by Windows Security Center

### ISSUE THREAD

**Issue by Yurinann** [SkinsRestorer/SkinsRestorerX#1572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/75569395/64afedd2-9f9b-458a-9881-68578bbc78ef)
as above.

### How can we reproduce what you got?

1. download the plugin
2. as above

### SkinsRestorer Version

15.0.8

### List of plugins

null

### Java Version

null

### Does your issue require a plugin in order to reproduce?

No

**Comment by ScratchyGamer314** [comment]
VirusTotal scan: 
![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/45255332/0af858ee-1c83-4ca8-9167-a0c821c7e175)

**Comment by xknat** [comment]
https://github.com/SkinsRestorer/SkinsRestorer/releases/tag/15.0.9
