### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by chelminski** [SkinsRestorer/SkinsRestorerX#1573]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Please add automatic plugin update. 
With the ability to auto download development and stable versions.

**Comment by xknat** [comment]
auto update is already a feature on backend.
#980 for dev build

**Comment by chelminski** [comment]
> auto update is already a feature on backend. #980 for dev build

What about stable versions? Is it possible for the plugin to update itself?

**Comment by xknat** [comment]
> > auto update is already a feature on backend. #980 for dev build
> 
> What about stable versions? Is it possible for the plugin to update itself?

For spigot and paper yes
