### ISSUE TITLE
nosuchmethod isflatworld paper 1.8.8 + viaversion

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/10220139/5b6851e1-1710-4022-868a-050ce5a7224e)

### How can we reproduce what you got?

use latest paper 1.8.8 with viaversion

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### SkinsRestorer Version

15.0.8

### List of plugins

skinsrestorer & viaversion

### Java Version

-

### Does your issue require a plugin in order to reproduce?

Yes

**Comment by katanya04** [comment]
This is the same problem I wrote about at [https://github.com/SkinsRestorer/SkinsRestorer/issues/1558](https://github.com/SkinsRestorer/SkinsRestorer/issues/1558), but you don't actually need to have viaversion installed in your server, it will happen eitherway (I don't have viaversion in my server)

**Comment by Tyranzx** [comment]
Do any of you know if these github threads (if they are threads) will be read and will be useful to fix these errors and warnings? (My question is when could they solve it? cause no one likes having a lot of errors in the console) Thanks you and sorry for the ignorance and insistence.

**Comment by xknat** [comment]
> Do any of you know if these github threads (if they are threads) will be read and will be useful to fix these errors and warnings? (My question is when could they solve it? cause no one likes having a lot of errors in the console) Thanks you and sorry for the ignorance and insistence.

Thanks for the feedback. I'll pick this up

**Comment by Tyranzx** [comment]
I just saw today's plugin update but when I downloaded it it gave me the same problem. I don't want to be insistent or seem so, but could you tell me if you have tried to solve it or still need to do it? Because I alwaus get that message on a Bedwars map.
![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/70720366/f7480592-77ac-4224-8d9f-a2c3da738172)


 - Sorry and thanks again ;D

**Comment by xknat** [comment]
Will be worked on this weekend

**Comment by Tyranzx** [comment]
Thanks again and good job :D! Keep growing

**Comment by xknat** [comment]
Thanks for reporting, i moved thee stack trace to debug, this seems to be a debug message, as the fallback method works, but this is something @AlexProgrammerDE needs to confirm :)

[ @Tyranzx @katanya04 @hexchain ]

**Comment by AlexProgrammerDE** [comment]
Fixed by https://github.com/SkinsRestorer/SkinsRestorer/commit/addc7888e48afc88b04b86670d04f2f2db50b214
