### ISSUE TITLE
Error getting Eclipse (UUID and Profile)

### ISSUE THREAD

**Issue by MaGikFixx** [SkinsRestorer/SkinsRestorerX#1586]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [x] I have read the installation guide and performed all steps

### Describe your issue

![изображение](https://github.com/SkinsRestorer/SkinsRestorer/assets/168145154/0ff9d06c-8b93-4dec-9bfb-f2f40dd5e914)

### How can we reproduce what you got?

1. Download latest version 15.0.11 in github.
2. Moved to the plugins folder via SFTP to the server with Velocity kernel.
3. Started Velocity server without configuring SkinsRestorer.
4. Next came two errors.
![изображение](https://github.com/SkinsRestorer/SkinsRestorer/assets/168145154/0ff9d06c-8b93-4dec-9bfb-f2f40dd5e914)

### Server/Error Logs

https://gist.github.com/MaGikFixx/89372823c3cb332aeb3328a7e505756a

### Minecraft implementation

```markdown
- Proxy: Velocity 3.3.0-SNAPSHOT
```

### What client are you using?

MultiMC

### SkinsRestorer Version

15.0.11

### List of plugins

Plugins: skinsrestorer, viaversion

### Java Version

OpenJDK 64-Bit Server VM Temurin-17.0.10+7

### Does your issue require a plugin in order to reproduce?

No

**Comment by Strovo** [comment]
Same error 

SkinsRestorer Version
15.0.12

Java Version
openjdk 21.0.2 2024-01-16

**Comment by xknat** [comment]
resolved, moved the messages to debug, please use dev build or wait till release
