### ISSUE TITLE
`/skin help` don't show help

### ISSUE THREAD

**Issue by Silvigarabis** [SkinsRestorer/SkinsRestorerX#1587]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

After I update Skinsrestorer to v15, command `/skin help` won't show a help message, instead it says `[SkinsRestorer] Your skin has been changed.`

### How can we reproduce what you got?

1. update to v15 (I'm using ` Version: 15.0.11` now)
2. execute command `/skin help` in game
3. bug appear

### Minecraft implementation

```markdown
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-538 (MC: 1.19.4)
```

### SkinsRestorer Version

15.0.11

### List of plugins

 Plugins (47): AntiPopup, AuthMe, CMILib, CommandWhitelist, DyedBackpacks, ESplitter, EcoPower, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, ExoticGarden, ExtraContexts, ExtraGear, FastAsyncWorldEdit, FastLogin, GSit, GuizhanLibPlugin, HolographicDisplays, Liquid, Logger, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NekoMaid, PlaceholderAPI, PlugManX, Prism, ProtocolLib, ProtocolStringReplacer, Residence, ServerUtils, SfChunkInfo, SkinsRestorer, SlimeHUDPlus, Slimefun, Uniporter, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, floodgate, grakkit and spark

### Java Version

openjdk version "17.0.8" 2023-07-18 LTS

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
resolved with 581fffff38a8a86ae6b0ae70b2df3b8b5c4fb663
Please use our dev builds or wait till next release
