### ISSUE TITLE
Multi languages

### ISSUE THREAD

**Issue by McLive** [SkinsRestorer/SkinsRestorerX#160]
xknat:
Using the source of crowdin and https://github.com/NyanGuyMF/SkinsRestorerX to work to a way where the default values with commands are kept and new ones are automatically added (format can change to without commends).

- [ ] Keep translation files inside the jar. (so they auto update)
- [ ] Be able to select langue from config.yml
- [ ] Revert back to the old way where on first install comments were still there and get removed when using new version with new locale (should not be happening often now)
- [ ] Automatic detecting from other plugins like essentials.

**Comment by xknat** [comment]
Has been done
