### ISSUE TITLE
velocity + paper 1.20.6

### ISSUE THREAD

**Issue by LucidAPs** [SkinsRestorer/SkinsRestorerX#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Skins dont work, nor does the commands , i am using build #1057
here are the logs
https://mclo.gs/fuAWKJo

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### SkinsRestorer Version

1057

### List of plugins

few velocity plugins not relevent

### Java Version

1.21

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Fixed with latest dev build
