### ISSUE TITLE
MySQL Error: Uknown colum "Nick" in "where clause"

### ISSUE THREAD

**Issue by Estarqui** [SkinsRestorer/SkinsRestorerX#164]
## Describe the bug
I get an error whenever i perform /skin set command

## How can we reproduce what you got?
1. Perform /skin set command

**Expected behavior**
Not getting an error, maybe... ?

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.1
* Spigot/Bukkit/Bungeecord: Paper 1.14.3
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://pastebin.com/ihB0HUKL

## Additional context
Changed this options from MySQL Config:

  SkinTable: 'players_skins'
  PlayerTable: 'authme_users'

**Comment by McLive** [comment]
You can't use an existing PlayerTable. Please change that config option back to an unique name.
