### ISSUE TITLE
url skin with /skin update

### ISSUE THREAD

**Issue by ITZVGcGPmO** [SkinsRestorer/SkinsRestorerX#165]
once a user sets their skin via SkinSystem or URL, and they execute `/skin update`, SkinsRestorer will throw this warning in the server logs: ```[pool-3-thread-1/WARN] []: skinsrestorer.shared.utils.MojangAPI$SkinRequestException: Server returned HTTP response code: 400 for URL: https://api.ashcon.app/mojang/v2/user/ username``` because their skin is not a valid mojang name to fetch. 

Their skin name should most likely be checked so it doesn't contain a whitespace before updating, so we abort the update and give some error like "cannot update skin, you will need to reupload and relog". I do not suggest resetting the player skin automatically, as they may be confused as to why their skin is not already applied via SkinSystem. (needs a relog) This error may come up too, if the skin expires. (which shouldn't happen unless you play minecraft for over 100 years)

**Comment by xknat** [comment]
fixed in #217
