### ISSUE TITLE
Skins GUI is broken

### ISSUE THREAD

**Issue by samanthafox504** [SkinsRestorer/SkinsRestorerX#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

All player heads in the skins GUI shows all skins as default skins (steve, alex and others)
it still works to apply the skin but in the gui it is impossible to know how it looks each skin
![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/173877912/be93062d-ca92-48fe-a240-c97240721ef2)

### How can we reproduce what you got?

1.- Setup Velocity 3.3.0 and Paper 1.21
2.- Start all the servers with their default settings
3.- Download some skins into the server
4.- Run /skins and all the skins shows up as default skins

### Server/Error Logs

No logs shows up :C

### Minecraft implementation

```markdown
- Proxy: Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400)
- Backend: Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
```

### What client are you using?

MultiMC, and also checked with Vanilla Launcher

### SkinsRestorer Version

15.0.15

### List of plugins

Plugins (14): DeathMessages, LuckPerms, NoChatReports, PlaceholderAPI, SimplePlayerFreeze, SixFursList, SkinsRestorer, DiscordSRV, ViaVersion, Vivecraft-Spigot-Extensions, voicechat, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Is this still happening with 15.3.1?

**Comment by AlexProgrammerDE** [comment]
A similar issue was fixed recently. Was XSeries breaking with reflection.
