### ISSUE TITLE
IDK What exactly is this :(

### ISSUE THREAD

**Issue by Tyranzx** [SkinsRestorer/SkinsRestorerX#1668]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/70720366/9370c66e-ce22-4fdf-897b-af9f78fa4171)

### Explain what you need this for

Is the server version? (1.12.2)

**Comment by xknat** [comment]
@Tyranzx We require viaversion v5 if your using viaversion.

**Comment by AlexProgrammerDE** [comment]
Please switch to ViaVersion v5.
