### ISSUE TITLE
BungeeCord and attached server

### ISSUE THREAD

**Issue by Kbarni2** [SkinsRestorer/SkinsRestorerX#167]
If I had a server connected to BungeeCord, and for example I would use Skin CommandNPC to set the skin broadcast, it writes: if there is no polugin on the server, it writes: No command! but if the plugin is on that server, the server will not respond.

**Comment by xknat** [comment]
For info on npc you need to contact your npc plugin.
For help on instalation make sure to check the wiki for bungeecord instalation

**Comment by Kbarni2** [comment]
But, when it's on the server, SkinsRestorer goes, but as soon as I connect to BungeeCord it doesn't go.

**Comment by xknat** [comment]
https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Installing-SkinsRestorer#installing-Bungee

**Comment by ITZVGcGPmO** [comment]
I can not comprehend how this is related to SkinsRestorer. May you please clarify? Is this a command conflict for `/skin` ?

**Comment by McLive** [comment]
What exactly is your problem now? I don't see any SkinsRestorer related question.

**Comment by xknat** [comment]
@Kbarni2 ^

**Comment by McLive** [comment]
No response, please reopen if the issue still exists.
