### ISSUE TITLE
Velocity Startup Issue

### ISSUE THREAD

**Issue by UnioDex** [SkinsRestorer/SkinsRestorerX#171]
## Describe the bug
Exception on startup.
Full latest log:
https://pastebin.com/k0rAsnEf

Also SkinsRestorer creates 2 folder in /plugins. One is skinsrestorer and the other is SkinsRestorer.

## How can we reproduce what you got?
Just put SkinsRestorer to your Velocity plugins folder and start the server.

## Server information
**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.2-SNAPSHOT
* Velocity: 1.0.2
* Java: 8

## Logs
https://pastebin.com/k0rAsnEf

**Comment by McLive** [comment]
Hi! Please try https://ci.freecraft.eu/v2/job/SkinsRestorerX/116/

Build 119 is currently broken. :/

**Comment by UnioDex** [comment]
It's also happening with latest stable release (13.7.1)

**Comment by McLive** [comment]
I'll look into it

**Comment by xknat** [comment]
Resolved in 7abecd2a11b82ef4ea8483b808319061a84eb823
