### ISSUE TITLE
Feature Request: /sr set <player> <texture> <signature>

### ISSUE THREAD

**Issue by UnioDex** [SkinsRestorer/SkinsRestorerX#172]
I have a custom skin upload system in my server's website. Players are uploading their skin files and my website uploads it to MineSkin.org and I get texture and values.

I was using BungeeCord and ChangeSkin (custom build) for this purpose but now I switched to Velocity and I want to use SkinsRestorer. If you can provide a command like this or just a simple API like setSkin(player, texture, signature) it would be great.

**Comment by McLive** [comment]
For now you can use /skin set <player> <url> which automatically uploads to mineskin and sets the texture.

The API will come back soon tho.

**Comment by ITZVGcGPmO** [comment]
soon:tm:

**Comment by xknat** [comment]
Bungee needs a different approach then spigot.
This can be done the same way as we use the url skin.

**Comment by xknat** [comment]
The command would be to long, a paster with raw source "might" be possible but i think your better off using skin url OR our api...
