### ISSUE TITLE
cannot use  "/skin url https:xxx" command 

### ISSUE THREAD

**Issue by Syerain** [SkinsRestorer/SkinsRestorerX#1722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

(paper1.21 server, no server mods)

When I try to upload a PNG file via URL , it appears failed to read.

1. when "/skin url https" , it works
2. when "/skin url https:" , it doesn't work
3. when "/skin url https://xxx.com" , it doesn't work

(the font of the content behind '/skin url' , become red)

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### What client are you using?

plain minecraft launcher

### SkinsRestorer Version

15.3.0

### List of plugins

SkinsRestorer, Geyser(DISABLED)

### Java Version

OpenJDK 64-bit server VM 21.0.1+12-29

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Yes, you must use quotes as explained here: https://github.com/SkinsRestorer/SkinsRestorer/releases/tag/15.3.1

**Comment by AlexProgrammerDE** [comment]
Also please update to 15.3.1
