### ISSUE TITLE
Page 2 not working

### ISSUE THREAD

**Issue by Treijim** [SkinsRestorer/SkinsRestorerX#173]
Using version 13.7.1 on Spigot 1.13.2-R0.1

Page 2 displays random heads from page 1, instead of the heads that should be on page 2.

**Comment by McLive** [comment]
Are you using MySQL or file storage?

**Comment by Treijim** [comment]
I'm using default settings, so it's still on file storage.

**Comment by McLive** [comment]
I just tried on my test server and it works just fine.

Can you maybe send me your zipped Skins folder so I can try with your skins? I only have a couple on page 2.

**Comment by McLive** [comment]
I just tried with more skins and page 2 and above works fine for me.

![image](https://user-images.githubusercontent.com/5620071/63365247-93d14200-c377-11e9-9110-8549c7bcb311.png)

**Comment by Treijim** [comment]
here's a zip with all my skins: https://www.dropbox.com/s/xtj9yy89so3ko34/treijim_skins.zip?dl=0

it will show two pages, but the skins on page 2 are the wrong ones, as you'll hopefully see.

**Comment by McLive** [comment]
I now tested with your skins and I still don't see the issue..
Your folder contains 41 skins, the first 36 are being shown on the first page, the last 5 ones on the second page.

![image](https://user-images.githubusercontent.com/5620071/63548095-d5a3e900-c52d-11e9-85ff-bf073ffec098.png)
![image](https://user-images.githubusercontent.com/5620071/63548107-dc326080-c52d-11e9-9aa4-4464703805ff.png)

**Comment by xknat** [comment]
@Treijim We (me and mclive) can't seem to reproduce this, it would be nice if you could upload a video showcasing this or document it step by step with the provided the zip.

**Comment by Treijim** [comment]
Here is what mine looks like: https://imgur.com/a/QNoXqJF

Here's my config: https://pastebin.com/DQVN2dZd

Given that you can't reproduce it, maybe it's a problem with my config settings? I don't recall changing anything, but maybe I did. Other than that, all I did was upload skins gradually over time, so I can't think of any steps to describe.

**Comment by McLive** [comment]
Can you please try with the latest version from Jenkins? That‘s the one I tested with.

**Comment by Treijim** [comment]
What's Jenkins?

I'm using Windows, same as you.

**Comment by ITZVGcGPmO** [comment]
Jenkins is a piece of software that automatically compiles java projects and allows them to be downloaded. You can visit SkinsRestorer's Jenkins build server here: https://ci.freecraft.eu/v2/job/SkinsRestorerX/

**Comment by Treijim** [comment]
Thanks. I just tried 13.7.2 (build 123) from that website and I unfortunately still have the same problem.

**Comment by McLive** [comment]
Please try [124](https://ci.freecraft.eu/v2/job/SkinsRestorerX/124/) now, it should fix your issue.

**Comment by Treijim** [comment]
That works. Thanks very much!
