### ISSUE TITLE
Add date/time formatting options to locale

### ISSUE THREAD

**Issue by AfkF24** [SkinsRestorer/SkinsRestorerX#1744]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Since there's now stuff like `/skin history`, having an option to format the [actual dates](https://github.com/SkinsRestorer/SkinsRestorer/blob/31f080c1ea4338dc48c1d99852fffc9c4a88bb8c/shared/src/main/java/net/skinsrestorer/shared/utils/SRHelpers.java#L46) yourself would be quite useful. Additionally, the newer updates add the option to modify the [time units](https://github.com/SkinsRestorer/SkinsRestorer/blob/31f080c1ea4338dc48c1d99852fffc9c4a88bb8c/shared/src/main/resources/locales/locale.json#L161-L168). 
While this is good, I prefer using shorthand notations (`s`, `m`, `h`, `d`) - which I can, but the `<time>` placeholder adds a [hardcoded space](https://github.com/SkinsRestorer/SkinsRestorer/blob/31f080c1ea4338dc48c1d99852fffc9c4a88bb8c/shared/src/main/java/net/skinsrestorer/shared/utils/SRHelpers.java#L253-L285) between the number and the time unit, which makes it look weird in such case, e.g.
```
1 h 20 m 35 s
 ^    ^    ^  
```
Ideally, there would be a way to modify the time format to eliminate this space (e.g. by having a locale entry to modify the time format in form of `<duration><unit>`). This would allow for a more concise display such as:
```
1h 20m 35s
```
 A quick (and dirty) solution would be eliminating the hardcoded spaces by adding a space before the time unit in the actual locale, e.g.
 ```json
  "skinsrestorer.duration_day": " day",
  "skinsrestorer.duration_days": " days",
  "skinsrestorer.duration_hour": " hour",
  "skinsrestorer.duration_hours": " hours",
  "skinsrestorer.duration_minute": " minute",
  "skinsrestorer.duration_minutes": " minutes",
  "skinsrestorer.duration_second": " second",
  "skinsrestorer.duration_seconds": " seconds"
  ```
  
  Thanks

### Explain what you need this for

Better configurability and full control over the date/time formatter

**Comment by AlexProgrammerDE** [comment]
Sounds doable.

**Comment by AfkF24** [comment]
Thanks, appreciate it!
