### ISSUE TITLE
Can't use any Commands

### ISSUE THREAD

**Issue by StarryCamile** [SkinsRestorer/SkinsRestorerX#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

The plugin loads successfully, but i can't use any commands like /skin 

### How can we reproduce what you got?

1.Install and put plugin in plugins folder
2.Launch server
3.Can't use /skin

### Minecraft implementation

```markdown
- Proxy: Waterfall
- Backend: Leaves 1.20.6
```

### What client are you using?

Cracked

### SkinsRestorer Version

1.5.31 (The last 1.5.40 has the problem either)

### List of plugins

Paper Plugins: [18:58:50 INFO]:  - BKCommonLib [18:58:50 INFO]: Bukkit Plugins: [18:58:50 INFO]:  - AllMusic3, CMILib, Essentials, FastAsyncWorldEdit, GSit, ItemEdit, LiteLottery, LuckPerms, Magic, QuickShop-Hikari [18:58:50 INFO]:  Residence, SkinsRestorer, TAB, TCCoasters, TCHangRail, TCTicketShop, Train_Carts, UltimateAutoRestart, Vault, ViaBackwards

### Java Version

openjdk version 21

### Does your issue require a plugin in order to reproduce?

None

**Comment by HassanElDessouki** [comment]
I am also facing the same problem! Could this be a problem with OpenJDK V21?
#1728 is also the same issue with the same Java version!

**Comment by xknat** [comment]
@StarryCamile zip file closed
Jar is corrupt. please download it again. let me know if resolved
