### ISSUE TITLE
GUI Main Thread Lag

### ISSUE THREAD

**Issue by Dinos3396** [SkinsRestorer/SkinsRestorerX#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

![image](https://github.com/user-attachments/assets/8646b3ba-8eeb-4486-9632-a06cd80d73aa)

### Minecraft implementation

```markdown
- Proxy: velocity 413
- Backend: paper 124
```

### SkinsRestorer Version

v15.4.0

### List of plugins

skinsrestorer

### Java Version

1.21

### Does your issue require a plugin in order to reproduce?

No

**Comment by Dinos3396** [comment]
https://spark.lucko.me/RCwH6Xejp7

**Comment by AlexProgrammerDE** [comment]
https://github.com/SkinsRestorer/SkinsRestorer/commit/c7ad3e696c7526945476124065e75e99208ed272

Should hopefully help
