### ISSUE TITLE
Typo on one of the skin names, making a bad word.

### ISSUE THREAD

**Issue by Illusioner2520** [SkinsRestorer/SkinsRestorerX#1755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

In the skins menu, there is a list of skins each with a different name. On the 3rd page of this menu, in the second row, the third skin over has a typo. Instead of being called "Person black shirt," the second r is missing.
It is the fifth skin in the list here: https://github.com/SkinsRestorer/cool-skins/blob/main/list.json

### How can we reproduce what you got?

1. Use the command `/skin gui`
2. Click on the bookshelf labeled Skins Menu
3. Click on the right arrow twice until you're on the third page
4. In the second row, the third skin is mislabeled

### Server/Error Logs

N/A

### Minecraft implementation

```markdown
- Backend: Purpur version 2280
```

### What client are you using?

Modrinth

### SkinsRestorer Version

15.4.0

### List of plugins

Plugins (80): AdvancedRegionMarket, AlwaysOnline, Arceon, ArmoredElytra, ArmorStandEditor, BanFromClaim, BannerMaker, BlockLocker, ChatFilter, ChatGames, ChestSort, Chunky, ChunkyBorder, ColorGradient, CoreProtect, CrisTreeCapitator, DecentHolograms, DeluxeTags, DiscordSRV, EconomyShopGUI, Essentials, EssentialsSpawn, EvenMoreFish, ExcellentCrates, ExcellentEnchants, FastAsyncWorldEdit, floodgate, FreeCoinFlip, Geyser-Spigot, goBrush, GPFlags, GriefPrevention, GSit, HeadDB, IllusioncraftDiscordbot, IllusioncraftPlugin, InteractiveChat, InvisibleItemFrames, ItemBox, ItemEdit, JakesRTP, LastLoginAPI, LuckPerms, Minepacks, Multiverse-Core, nightcore, packetevents, Parties, PetNameFix, PlaceholderAPI, PlayerReport, PlayerWarps, Playtimes, PlugManX, ProtocolLib, PurpurExtras, Shopkeepers, SilkSpawners, SkinsRestorer, SuperbVote, TAB, Tebex, Themis, TogglePvp, Trademarker, TradeShop, VanishNoPacket, Vault, VeinMiner, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, Vouchers, Warnings, WorldBorder, WorldGuard, WorldGuardExtraFlags, Quests

### Java Version

jre 21

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
ty, i am embarrassed... sorry 
Ty so much for reporting this!

https://github.com/SkinsRestorer/cool-skins/commit/e0c777dbad469ed06f5af8f0b2a9f9b93954ec70
