### ISSUE TITLE
Skin not applied

### ISSUE THREAD

**Issue by AKCEJIb** [SkinsRestorer/SkinsRestorerX#176]
## Describe the bug
Skin not applied when I join on my server or trying to set skin with /skin set (name).
In game chat says that my skin are applied, but it's not.

## How can we reproduce what you got?
1. Join on server - causing error in server console.
2. Trying to set skin manually - causing error in server console.
3. Skin does not apply ;(

**Expected behavior**
Skin should apply.

**Screenshots**
https://i.imgur.com/EifaOK1.jpg

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
[CatServer](https://github.com/CatServer/CatServer)
Spigot + Forge

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.1
* Spigot/Bukkit/Bungeecord: 1.12.2
* Java: 8

## Logs
[Only Error](https://gist.github.com/AKCEJIb/57d5afd0f368e8f544bedadb2f627638)
[Full Log](https://gist.github.com/AKCEJIb/e221e8ebb84197e129dca3940c645aba)

**Comment by McLive** [comment]
Hi,
Please try the most recent version from Jenkins (https://ci.freecraft.eu/v2/job/SkinsRestorerX/123/)

**Comment by AKCEJIb** [comment]
> 
> 
> Hi,
> Please try the most recent version from Jenkins (https://ci.freecraft.eu/v2/job/SkinsRestorerX/123/)

Nope, but line of error changed 107->106
[New Log Only Error](https://gist.github.com/AKCEJIb/ebb98a463bcbb9bcf1aaa56d6321f1d1)
[New Log Full Log](https://gist.github.com/AKCEJIb/1f483676903c50fa48e67bad7c146d23)

Seems it's a CatServer problem :(
But maybe you can fix it?

**Comment by McLive** [comment]
We only support Spigot, Bungee, Velocity and Sponge, sorry!

**Comment by AKCEJIb** [comment]
Ok, nevermind then, thanks for reply ;)

**Comment by xknat** [comment]
@AKCEJIb remember us saying we don't support it? well we should now with the last commit, it would be nice if you can test it for us out. you cna download it from https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar
