### ISSUE TITLE
API currently doesn't work

### ISSUE THREAD

**Issue by h14turkiye** [SkinsRestorer/SkinsRestorerX#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

```[09:57:04 ERROR]: Error occurred while enabling HeadsAnywhere v1.3 (Is it up to date?)                                  java.lang.IllegalStateException: SkinsRestorerAPI is not initialized yet! (Are you trying to access it without softDepends?)                                                                                                                            at SkinsRestorer.jar/net.skinsrestorer.api.SkinsRestorerProvider.get(SkinsRestorerProvider.java:35) ~[SkinsRestorer.jar:?]       ```  
I'm currently using version 15.4.2. I am trying to use HeadsAnywhere but unable to do so because of the error. I also use the proxy version along with bukkit version. There are no errors on proxy.

### Minecraft implementation

```markdown
- Proxy:Velocity 3.3.0
- Backend:This server is running Pufferfish version 1.21.1-11-HEAD@9a82b86 (2024-08-21T09:58:17Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are on the latest version!
```

### SkinsRestorer Version

15.4.2

### List of plugins

HeadsAnywhere, placeholderapi, skinsrestorer

### Java Version

Java(TM) SE Runtime Environment (build 22.0.2+9-70)                                                                     Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)    

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
SkinsRestorerAPI is not initialized yet!
you need to initialized it on the back end using the override to enable backendstorage
read proxy warning file

**Comment by h14turkiye** [comment]
Ah yes I saw it just now. Thank you.
