### ISSUE TITLE
Features for SkinsRestorer API

### ISSUE THREAD

**Issue by RobinDeBaets** [SkinsRestorer/SkinsRestorerX#182]
This is related to #152 

Because there doesn't seem to be one big compilation for this, I'm creating this as an issue for some of the features that I'd definitely like the new API to have.

- Applying a player skin to an itemstack, both by a player's name and a texture
  E.g. `setPlayerSkullItemStack(String playerName, ItemStack itemStack)` and `setTextureSkullItemStack(String texture, ItemStack itemStack)`

- Applying a player skin to a skull tile, both by a player's name and a texture
  E.g. `setPlayerSkullI(String playerName, Skull skull)` and `setTextureSkull(String texture, Skull skull)`

**Comment by RobinDeBaets** [comment]
Any updates on this? A lot of people are asking for this.

**Comment by McLive** [comment]
Planned for future releases

**Comment by RobinDeBaets** [comment]
I think this is highly requested and extremely useful for plugins that handle a lot of Itemstacks and block skulls

**Comment by xknat** [comment]
@RobinDeBaets its in the pipeline. we recently posted a google forum on our update in which we got a indication what server owners want on average.
I will try to implement things by following the order of that result.

**Comment by LichLord91** [comment]
Will any of these feature helps plugin devs possibly be able to grab players heads to add to their plugins needs for like simply displaying an image of it? Example would be Discordsrv , Pl3xmap, Dynmap etc. Would help offline servers and GeyserMC players where these plugins rely on mojang api and java uuid's to grab player heads. 

If they don't can i suggest adding a feature that would let this happen? :)

![image](https://user-images.githubusercontent.com/8435580/107636563-abfae800-6c21-11eb-85f3-35cb3f44a425.png)
![image](https://user-images.githubusercontent.com/8435580/107636629-c3d26c00-6c21-11eb-953f-deb4f00ec1d2.png)

**Comment by LichLord91** [comment]
Hey team speaking of improvements/api's I don't know if you can assist these devs in any way of trying to do a bit what dynmap has done by setting player avatar head in their plugin using skin restorer's help.

Dynmap's original commit : https://github.com/webbukkit/dynmap/commit/578c66e2fe6de9e83f9e9ad1b8508a1def97aae1

Two suggestions for integration with your plugin on these two great projects:

DiscordSrv:
https://github.com/DiscordSRV/DiscordSRV/issues/996

Pl3xmap:
https://github.com/pl3xgaming/Pl3xMap/issues/20

**Comment by xknat** [comment]
Hey there,
Thank you for your effort in integrating SkinsRestorer with other projects.
We did receive a lot of request in the past regarding images and url's.
https://github.com/riflowth/SkinSystem has allowed people to get skulls from a url to use in DiscordSRV (`yourwebsite.net/skinsystem_folder/resources/server/skinRender.php?headOnly=true&vr=0&hr=0&user={username}`)

Looking at SkinsRestorerSkinUrlProvider.java
I think we could also do the same in our code by providing http://textures.minecraft.net/

I am currently working on SkinsGUI to work with filters.
I might look into it with some other big api additions.

Keep in mind that we are working in the background on planning migration to v14 first and the breaking api changes are currently on a higher priority. I want the transition from v13 to v14 to be as smooth as possible.
Maybe join our discord so i can talk about this further.

If you need this "GetSkinUrl player" right away, then i recommend making a pr.
I can help out here and there.

**Comment by LichLord91** [comment]
Hey xknat ,

appreciate the feedback and the explanation on whats happening on your roadmap , appreciate it. Loving the plugin thusfar its been really helpful especially to my GeyserMC players. 

I  updated some info on Discord ticket if you wouldn't mind giving it a read and maybe clearing up any confusions or misdirection presented by us both or maybe even give some direction on what to do next. (if you have the time). Also I am in your discord so happy to either A) Open up a new ticket so not crowding this one or B) have a discussion on the discord. Feel free to DM me directly or ping me. I don't like pinging the dev's/moderators as im sure you guys get it a lot already. 

Also if its not too much of a bother or you think it'd help collaborate better maybe we can all jump into the respective discords of each of these projects and discuss it there as well

Discordsrv:
https://discord.com/invite/au3S5q3

Purpur/Pl3xmap:
https://discord.com/invite/mtAAnkk

**Comment by AlexProgrammerDE** [comment]
For convenience, we have added a BukkitHeadAPI class to the SkinsRestorer API. 
https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/api/src/main/java/net/skinsrestorer/api/bukkit/BukkitHeadAPI.java
I wasn't aware this was actually requested. I guess this issue can be closed now.
The base64 data of a property or player should be able to obtain using the API. We may add a direct method for that in the future.
