### ISSUE TITLE
/skins command does nothing, produces error

### ISSUE THREAD

**Issue by Treijim** [SkinsRestorer/SkinsRestorerX#183]
https://pastebin.com/ZdAEYpYD

The plugin worked earlier today but now it gives the above error when using /skins and I didn't change anything. 

This may be unrelated, but earlier today the entire game would crash when going to page 2 of the skins. I didn't get a chance to get any error details because now the plugin doesn't work at all. 

Using Spigot 1.13.2-R0.1

**Comment by McLive** [comment]
Can't reproduce, sorry

![image](https://user-images.githubusercontent.com/5620071/64542583-19fff900-d324-11e9-86cb-051f107468c7.png)

**Comment by Treijim** [comment]
It's working fine now and I did nothing. Some server somewhere must've been down.
