### ISSUE TITLE
Skinrestorer Mojang API problem.

### ISSUE THREAD

**Issue by OverBrave** [SkinsRestorer/SkinsRestorerX#188]
Hey, I'm using firewall. But i have problem. Look this.
![image](https://user-images.githubusercontent.com/47111280/67876270-aa9ace80-fb48-11e9-825e-752c4b79fd33.png)
What is this ip adress?

**Comment by xknat** [comment]
@OverBrave we use these websites to download and request skins, allow your server to connect tot hem over port 443 and 53
