### ISSUE TITLE
Skins are different for premium and no premium

### ISSUE THREAD

**Issue by IMKinano** [SkinsRestorer/SkinsRestorerX#189]
## I just joined with 2 acc, one premium and one no premium and they see each other different.

**Screenshots**
This is from a no premium player:
![image](https://user-images.githubusercontent.com/55762837/68074935-41e16b00-fd6f-11e9-9269-0e9a4db106ca.png)
and this is from a premium player:
![image](https://user-images.githubusercontent.com/55762837/68074940-51f94a80-fd6f-11e9-8da9-d1e7006335c8.png)

## Server information

* SkinsRestorer: 13.6.2
* Paper Spigot 1.14.4
* Java: 8

**Comment by McLive** [comment]
This isn't something that can happen serverside as you can only set one skin per player.

Most likely the non-premium player uses some launcher that sets another skin clientside. My best guess is T-Launcher, which overrides SkinsRestorer skins.

**Comment by IMKinano** [comment]
Thank you for your help!! :D
