### ISSUE TITLE
Error.  Premium player with that name does not exist.

### ISSUE THREAD

**Issue by comdarksider** [SkinsRestorer/SkinsRestorerX#191]
I use spongeforge-1.12.2-2838-7.1.8-RC3964 and SkinsRestorer-13.7.5 (latest version)

https://pastebin.com/98fNWbvt

**Comment by xknat** [comment]
We don't support forge....
try a skin mod since they work better for forge anyways.

**Comment by ddeepa61644-ui** [comment]
[Ski eriestor] Error Premium player with that name does not
