### ISSUE TITLE
Unable to disable update check

### ISSUE THREAD

**Issue by BoomEaro** [SkinsRestorer/SkinsRestorerX#199]
## Describe the bug
The Updater.Enabled option in the config does not work properly.
It looks like you run an update check before the config is initialized when the plugin loads. But since Config is not yet initialized properly, the default value is used and the update check cannot be turned off.
This issue is observed for both Bungee and Bukkit versions.

## How can we reproduce what you got?
https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/SkinsRestorer.java#L78
It is located before config initialization.
https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bungee/SkinsRestorer.java#L91

**Expected behavior**
First, config initialization, then check and run update check

## Server information
BungeeCord

**What version? Do NOT answer LATEST**
13.7.4 version

**Comment by McLive** [comment]
Thanks for letting us know, will be fixed on next release.

**Comment by sergservis** [comment]
This error occurs because of this problem?
https://pastebin.com/Un0ykRwk

**Comment by McLive** [comment]
> This error occurs because of this problem?
> https://pastebin.com/Un0ykRwk

No, please open a new issue and send all the required information.

**Comment by xknat** [comment]
disable the updater wont be a thing any more.
instead we work on delaying updates so you have time to test and update when you want within 3 delayed versions. 
https://github.com/SkinsRestorer/SkinsRestorerX/issues/298
