### ISSUE TITLE
[Feature request] Placeholder for player's skin name for PlaceholderAPI

### ISSUE THREAD

**Issue by vanduck241** [SkinsRestorer/SkinsRestorerX#201]
This very helpful for cracked server because some inventory GUI plugins support skull: '%player_name%' but it doesn't work for these. If we have the skin name, we can replace from skull: '%player_name%' to skull: '%skin_name%' so it will work because these skin name are mojang player's

sorry for my bad english T_T, i'm using google translate...

**Comment by McLive** [comment]
I don't really understand why you need this. Do you wan't to create a custom GUI? You can do that by using the SkinsRestorer API.

**Comment by xknat** [comment]
not all skins have a player name, for example url skins...

**Comment by Angel-0** [comment]
@xknat, you're right, however all skins, correct me if I'm mistaken, have signatures and properties; considering this, a placeholder returning either one, either the other or even an itemstack of the skin head, that could be used by others plugins would be a great idea.

**Comment by xknat** [comment]
@Angel-0 we cant detect if the username embedded in the skin file is a custom skin (skin bot) or a legit premium player skin. the only diff is within the .player file as for custom skins its set to empty (if i am not mistaken[need investigation])

**Comment by xknat** [comment]
@vanduck241 please give us some more insight on this.
Is this still wanted?

**Comment by vanduck241** [comment]
forget it, i think this is an unnecessary feature
