### ISSUE TITLE
Enhancement: Ability to change skin with the spigot SkinsRestorer API while in bungee mode.

### ISSUE THREAD

**Issue by ColaIan** [SkinsRestorer/SkinsRestorerX#205]
### Description
Add the ability to call spigot SkinsRestorer API to change skin for a player in bungee mode of skinsrestorer.

**Comment by McLive** [comment]
You have to do it through BungeeCord as the bungee plugin handles all the skins when running in bungee mode. 

The spigot plugin just updates the skin at this point.

**Comment by ColaIan** [comment]
@McLive Yeah I understand that it only updates the skin on the spigot side, so that's why this is a feature request to add bungeecord messaging channel to the plugin itself.

**Comment by xknat** [comment]
Well.. if we would implement this it would be the same way as we do now but it will just send the api to bungee...

I doubt that this is what you goal

**Comment by ColaIan** [comment]
Yes it is, it would be great to have!

**Comment by ITZVGcGPmO** [comment]
@ColaIan This would be a nice compatibility feature that allows plugins only made for spigot to work on bungee instances, but unfortunately there are more pressing features/fixes that are higher priority. Although, if you submit a pull request i'm sure it will be reviewed/accepted!
