### ISSUE TITLE
readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SkinsRestorer/SkinsRestorerX#207]
## Describe the bug
So it occures only when network have multiple connected proxies. Like one is connected to other and then to some server. I have like that network, which is not online-mode, so im using SkinsRestorer for a long time and I really appreciate that work.

The strange part is that mentioned in title error occures only for little amount of players. I have SR installed on my main proxy and sometimes player tries to connect to server, which is under another proxy and then the second proxy refuses connection. Even stranger is that changing internet provider solves problem (like changing from home internet to the phone one or vpn).

The fact is quite big amount of people acctually uses proxy-proxy connections, but they have to resign from SR, because it brokes some connections.

What does SR change in network connections? Why could it make connection reseted?

I'm using SR 13.7.5 on waterfall(s) b318 1.15.2 and the problem relates to them, no matter which version arem WFs or SRs.

I can contact with someone from your team on Discord to provide any information you want or if you will need normal conversation. I think its quite interesting issue from programmer's point of view

The only thing is displayed is in console of proxy, which has skinsrestorer installed:
```
[23:00:25] [Netty Worker IO Thread #1/INFO]: [DrakonSilver|/178.217.197.122:31048] <-> ServerConnector [Skyblock] has connected
[23:00:26] [Netty Worker IO Thread #1/WARN]: [DrakonSilver|/178.217.197.122:31048] <-> ServerConnector [Skyblock] - NativeIoException: readAddress(..) failed: Connection reset by peer
[23:00:26] [Netty Worker IO Thread #1/INFO]: [DrakonSilver|/178.217.197.122:31048] <-> ServerConnector [Skyblock] has disconnected
```
And fun fact is that problem doesn't occure if ip_forwarding is disabled

**Comment by xknat** [comment]
Not SR Related afaik
