### ISSUE TITLE
Jenkins SSL error

### ISSUE THREAD

**Issue by rautamiekka** [SkinsRestorer/SkinsRestorerX#210]
## Describe the bug
I've made a Bash script which uses wget to download the Jenkins last successful page (https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/) before downloading the file itself (https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar), ending up causing an SSL complaint that didn't come up before, preventing from downloading either thing. Web browsers don't mind this though.

## How can we reproduce what you got?
- Download the page:
```
wget --no-check-certificate 'https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/' -O -
```

or

- Download the file:
```
wget --no-check-certificate --no-glob 'https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar' -O SkinsRestorer.jar
```

**Expected behavior**
The page or the file would be normally downloaded, nothing special there.

**Script**
```bash
#!/usr/bin/env bash
##Download the DL page and pipe into §sed§ to look for the build number.
buil=$(echo "$(wget --no-check-certificate 'https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/' -O -)" | sed -rn -e 's|<title>[^#]++#([0-9]++)[^<]++</title>.++|\1|p')

##Remove the spaces from the build number if they are there
buil="${buil/    /}"

if [ "${buil}" != '' ]; then
    echo "The build number couldn't be found."
    exit 1
fi

##Move the old JAR away. If that fails, quit the script.
mv -v 'SkinsRestorer build '*'.jar' _old_/

##Download the archive ZIP.
wget --no-check-certificate --no-glob 'https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar' -O "SkinsRestorer build ${buil}.jar"

##Create symlink for the plugins.
ln -vsf "SkinsRestorer build ${buil}.jar" SkinsRestorer_latest.jar
```

## Logs
```
./update_SkinsRestorerX.sh
--2020-03-17 18:19:56--  https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/
Resolving ci.freecraft.eu (ci.freecraft.eu)... 2a05:bec0:20:1::9, 134.255.237.9
Connecting to ci.freecraft.eu (ci.freecraft.eu)|2a05:bec0:20:1::9|:443... connected.
OpenSSL: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
Unable to establish SSL connection.
--2020-03-17 18:19:56--  https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar
Resolving ci.freecraft.eu (ci.freecraft.eu)... 2a05:bec0:20:1::9, 134.255.237.9
Connecting to ci.freecraft.eu (ci.freecraft.eu)|2a05:bec0:20:1::9|:443... connected.
OpenSSL: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
Unable to establish SSL connection.
'SkinsRestorer_latest.jar' -> 'SkinsRestorer build .jar'
```

**Comment by aljaxus** [comment]
Have you bothered checking the CI page itself? https://ci.freecraft.eu/
![image](https://user-images.githubusercontent.com/24414483/79212029-472b0180-7e47-11ea-950a-03341f4f56d9.png)

**Comment by rautamiekka** [comment]
> Have you bothered checking the CI page itself? https://ci.freecraft.eu/
> ![image](https://user-images.githubusercontent.com/24414483/79212029-472b0180-7e47-11ea-950a-03341f4f56d9.png)

Back then it didn't say SERVICE TEMPORARILY UNAVAILABLE.

**Comment by xknat** [comment]
@rautamiekka Has your issue been resolved now?

**Comment by rautamiekka** [comment]
> @rautamiekka Has your issue been resolved now?

The file does download just fine but the website (https://ci.freecraft.eu/) still gives SERVICE TEMPORARILY UNAVAILABLE.

**Comment by McLive** [comment]
its https://ci.freecraft.eu/v2/

**Comment by rautamiekka** [comment]
> its https://ci.freecraft.eu/v2/

That worked.
