### ISSUE TITLE
java.lang.LinkageError with SLF4J

### ISSUE THREAD

**Issue by egg82** [SkinsRestorer/SkinsRestorerX#212]
## Describe the bug
SLF4J (and every other dependency) is shaded into the master jar, but not relocated. This pollutes the main namespace and prevents other plugins from working correctly.

In particular, SLF4J from other plugins (when loaded after SkinsRestorer) will complain and cause the plugin to keel over entirely.

## How can we reproduce what you got?
1. Install the plugin
2. Install another plugin that uses SLF4J (such as Anti-VPN)
3. Watch the other plugin fail to load due to SLF4J linkage exceptions

**Expected behavior**
No conflicts

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Bungeecord
Spigot
Bukkit

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.5
* Java: 8

## Logs
https://pastebin.com/L1A7HHEi

## Additional context

https://github.com/egg82/AntiVPN/issues/53

**Comment by egg82** [comment]
A fix for this would be taking advantage of the relocations section of the maven-shade-plugin, which you already do for some dependencies, but not all.

The rest of these should be relocated somewhere in your "skinsrestorer" package:
https://imgur.com/O1ECVT7

**Comment by SocketByte** [comment]
Until that commit is merged, the easiest solution seems to be just removing the slf4j from SkinsRestorer if you have other plugin that has it. Works pretty well for me, but yeah, that should be fixed immediately.

**Comment by xknat** [comment]
hey there @egg82 @SocketByte , 
i will check out @Eoghanmc22 fix and see if that resolves things without creating issues on our side. 
ty for adding the commit and sorry for late response. 
see reply upcoming 35 hours.

**Comment by xknat** [comment]
Done in #214 ty for helping us out <3
