### ISSUE TITLE
Bungee API in spigot

### ISSUE THREAD

**Issue by etysoftware** [SkinsRestorer/SkinsRestorerX#216]
I have a spigot plugin and I need to execute /skin set command on player. Can you explain me how can I do this? I can't find any information about API in Wiki. Thanks ;)

**Comment by xknat** [comment]
You would need to connect the api to bungee side

**Comment by xknat** [comment]
https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/
