### ISSUE TITLE
skin update calls api 3x

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#222]
could be an issue with the try nexst that on success it keeps going for the other api's
![image](https://user-images.githubusercontent.com/10220139/79639269-16bace80-818b-11ea-852a-035a10f4b034.png)

**Comment by McLive** [comment]
996bd27da8b651ba7f196f563264fb471b8415ec
dd6f331ec569bb31f8f8f26062192e26310b65bf
