### ISSUE TITLE
Skins not shown for not registered on Mojang players

### ISSUE THREAD

**Issue by zertex** [SkinsRestorer/SkinsRestorerX#225]
Skins not shown for not registered on Mojang players

Version: 13.7.5
Spigot: 1.15.2

Installed only in plugin folder of last version BungeeCord

Java8/64bit

For unregistered users
![alt text](http://kano3.ru/github/skin-error.png "title")

For registered users
![alt text](http://kano3.ru/github/skin-ok.png "title")

Why?

**Comment by xknat** [comment]
@zertex your launcher does prob override our skins. 
Try it on another launcher like shinigami
