### ISSUE TITLE
Specifying an unknown username sometimes works weirdly

### ISSUE THREAD

**Issue by AfkF24** [SkinsRestorer/SkinsRestorerX#228]
Basically, doing something like `/skin abcdefghijkl000` drops the following URL, instead of a message: https://api.ashcon.app/mojang/v2/user/abcdefghijkl000

**Comment by xknat** [comment]
Can confirm.
Was already working on a fix in combination with #222 which is close or related to the issue.
This issue came up with the backup uuid api i implemented as a faillback uuid checking.

planned for 13.7.6

**Comment by xknat** [comment]
This is the same as #221
