### ISSUE TITLE
Server Crash. OutOfMemoryError

### ISSUE THREAD

**Issue by MostRush** [SkinsRestorer/SkinsRestorerX#229]
## Describe the bug
Server has been crashed after player entry.

## How can we reproduce what you got?
1. I think its hard to reproduce because its rare out of memory error.

**Expected behavior**
Stable server operation.

**Screenshots**
nope. just logs

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Spigot

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.5
* Spigot version: 1.15.2
* Java: 11

## Logs
https://drive.google.com/drive/folders/1prbf3LHScSCC5RkdujrYB-Fy65xCFHew?usp=sharing

**Comment by xknat** [comment]
Are you using bungeecord?
also are you getting ssl errors? 

A timings report at that time would have been nice...

**Comment by MostRush** [comment]
Nope. bungeecord isn't used.
SSL: i don't think so.
Timings: Unfortunately, I did not write logs at this time.

**Comment by McLive** [comment]
This is unkliely related to SkinsRestorer. Your server just ran out of memory and SR couldn't use any free memory to perform tasks.

**Comment by MostRush** [comment]
Sorry for the time taken. I figured out the problem and forgot about this thread. I should have notified you about this.

**Comment by McLive** [comment]
No problem :)
