### ISSUE TITLE
fix / skins

### ISSUE THREAD

**Issue by sergservis** [SkinsRestorer/SkinsRestorerX#231]
## How can we reproduce what you got?
1. Install the following skins - /skin 02q /skin 003 /skin 4bby
2. Skins folder must have more than 40 (non.skin)
3. Run the / skins command and you will get a player crash
 21:33:33 [INFO] [Nikita] disconnected with: IOException : An existing connection was forcibly closed by the remote host @ sun.nio.ch.SocketDispatcher:-2

## Server information

On what platform does your server run? Bungeecord/Spigot

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.5 (#1​85 Jenkins)
* Spigot version: 1.8-1.15
* Bungeecord version: Last
* IF bungee, did you put the plugin on all servers: Yes 
* Java: 8

**Comment by xknat** [comment]
Not an issue, we only support legit names.

**Comment by sergservis** [comment]
These names break the menu / skins
Players install these skins with the / skin command and they themselves fall into the Skins folder

**Comment by sergservis** [comment]
You do not see this as a problem?

**Comment by xknat** [comment]
- The username must be between 3 and 16 characters (inclusive).

The characters permitted are :
`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_`

**Comment by xknat** [comment]
But if you want to help us out and tell us more about the issue. we dont rly got all info from you yet. if you can create a support ticket we can keep asking questions there and not spam this ticket.

**Comment by sergservis** [comment]
I ask you to help. I will give my skins folder. Put her on a Bungeecord. After that, start the Bungee server and Spigot. Now write the command / skins
Is the player still on the server after these steps?
https://drive.google.com/open?id=1bvdHXFGYZV4pPc2AwPG6Ps67cYjykorT

**Comment by sergservis** [comment]
I found out that this is due to such skins: /skin 02q /skin 003 /skin 4bby
I first had such a problem. There are more than 25,000 files in my skins folder and there were no problems with them before.

**Comment by xknat** [comment]
https://api.minetools.eu/profile/545ad854787f438c99ac21aa424f2da3
^ user 02q has null skin and still got created. 
A warning should be given that there is no skin.

**Comment by sergservis** [comment]
Do you want to get my full skins base? Which folder do you need?

**Comment by sergservis** [comment]
Bug fixed. Thanks so much for a great plugin.
