### ISSUE TITLE
MS Error: Failed to determine file size

### ISSUE THREAD

**Issue by Benedict1225** [SkinsRestorer/SkinsRestorerX#232]
## Describe the bug
When im trying to set my skin (with url to .png file) it return "[SkinsRestorer] MS Error: Failed to determine file size"
## How can we reproduce what you got?
1. Type /skin set https://fr.namemc.com/texture/af84c27734c12852.png (its an exemple it doesnt work with any url)
2. Press enter
3. Wait while it says "Uploading Skin"

**Expected behavior**
I expected that it would change my skin without error
**Screenshots**
## Server information
Server is hosted on a VPS (Ubuntu 18.04 LTS Server)
**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Spigot
**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.5
* Spigot version: CraftBukkit version git-Spigot-2040c4c-94cb030 (MC: 1.15.2)
* Bungeecord version: 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8 (openjdk version "1.8.0_252")
## Logs
start log https://pastebin.com/21ELG9Tv

**Comment by xknat** [comment]
Has been resolved local 
I already added more info in it when they try to use a url without a skin format
