### ISSUE TITLE
Url doesn't works correctly

### ISSUE THREAD

**Issue by etysoftware** [SkinsRestorer/SkinsRestorerX#233]
If I use url http://novask.in/3751853271.png (and some other on this site skin gallery) on first try skin doesn't changes, but when I do it twice my skin changes, but to not skin from url and after it some another url doesn't work corretly.

Sorry for my English, I use spigot 1.15.2 with bungeecord (BotFilter included)

**Comment by xknat** [comment]
@etysoftware This is because that link redirects to http://lh3.googleusercontent.com/ouQ3IcUvq_u_c3-RJS5ZIruWMgeXMg54t2EMk1-SKWpru8KmQT_yqCUwmMNFHgKDNlOhSnfp0uOFDIrRAmLkIA
And we cant catch a image from a redirect
you would need to upload it to imgur

**Comment by etysoftware** [comment]
but some skins work on this url! and can another urls broke after this operation, i think it can

> @etysoftware This is because that link redirects to http://lh3.googleusercontent.com/ouQ3IcUvq_u_c3-RJS5ZIruWMgeXMg54t2EMk1-SKWpru8KmQT_yqCUwmMNFHgKDNlOhSnfp0uOFDIrRAmLkIA
> And we cant catch a image from a redirect
> you would need to upload it to imgur

**Comment by xknat** [comment]
> but some skins work 
Yeah, working links work, redirect links break

**Comment by etysoftware** [comment]
after bad link i try to change skin with https://pearth.site/karlov.png and my skin changes for wrong

**Comment by xknat** [comment]
https://github.com/SkinsRestorer/SkinsRestorerX/wiki/SkinURL

**Comment by etysoftware** [comment]
my url works without trying bad link. Can "bad link" broke all skin system?

**Comment by etysoftware** [comment]
my problem is that after using a bad link, working links stop changing the skin to the correct one

**Comment by etysoftware** [comment]
but sometimes old working links work again

**Comment by xknat** [comment]
@etysoftware We use github for code issues. this is a user issue.

For support, join our discord https://discord.gg/sAhVsyU

**Comment by etysoftware** [comment]
![image](https://user-images.githubusercontent.com/51130679/80199739-57529600-862a-11ea-8763-09c4cd4fef46.png)
WORKING:
https://www.minecraftskins.com/uploads/skins/2020/04/04/personal-skin-14059721.png
