### ISSUE TITLE
Ghosts on the server

### ISSUE THREAD

**Issue by sergservis** [SkinsRestorer/SkinsRestorerX#234]
## How can we reproduce what you got?
1. Ghosts on the server

**Screenshots**
https://cdn.discordapp.com/attachments/186794372468178944/704044614893699082/unknown.png

## Server information

**On what platform does your server run? (Bungeecord/Spigot)

**What version? Do NOT answer LATEST**
* SkinsRestorer: Jenkins #1​85 (in all modes)
* Spigot version: PaperSpigot 1.12.2 
* Bungeecord version: Latest version
* IF bungee, did you put the plugin on all servers: Yes 
* Java: 8

**Comment by xknat** [comment]
Has been a issue since day 1
prob nothing we can do about... unless we do a total rewrite or we figure out what the hack actually is causing this.

**Comment by sergservis** [comment]
I can share my observations. 1. I noticed that in the latest version they became much more. 2. I noticed that they are visible only to those players who were not near the player who left the server. 3. If you reconnect to the server, they disappear 4. If you fly out of the chunk, they go.

**Comment by xknat** [comment]
Its client side, so has something to do with packets we send

**Comment by sergservis** [comment]
Maybe this is due to where the player is looking? All ghosts look one way. On keyboard F3 
"facing south Towards positive Z) 0.0 / 17" 
Look at 0.0 / **

**Comment by AfkF24** [comment]
Oh, didn't know this was a SkinsRestorer thing. Had this issue going on for several years now, but has thankfully gotten much better as of recently...

**Comment by xknat** [comment]
> Had this issue going on for several years now, but has thankfully gotten much better as of recently

I monitored it on a few versions when it was a big hit.
We got it down and down to a place where nothing was effective any more....

**Comment by Kongolan** [comment]
Besides of that, i'll open a new bug report as well. But updating the whole server on skin setting gives you a permanent tracer to that player, making everyone raidable, since they can freecam over 100k blocks and find the player. (Version: 13.7.6-SNAPSHOT).

How to replicate:
1. have a offline-mode server
2. have SkinsRestorer
3. use Aristois hacked client and enable tracers
4. login with 1 account with tracers active
5. login with another account
6. tracer will appear
7. freecam to the tracer, find the "ghost player" and note down coords

**Comment by McLive** [comment]
@sergservis 
@AfkF24 
@Kongolan 
Can you guys please test the latest dev build from Jenkins? It should fix those issues.

https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

**Comment by AfkF24** [comment]
> @sergservis
> @AfkF24
> @Kongolan
> Can you guys please test the latest dev build from Jenkins? It should fix those issues.
> 
> https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

Will do, although I wasn't experiencing these issues in a while!

**Comment by sergservis** [comment]
This problem has been resolved in the latest version. Thank you so much for the wonderful plugin.

**Comment by Kongolan** [comment]
The problem is resolved for the tracer bugs, Ghost players i can't tell yet. But when you enable it all my 20 players online lost their experience values... Should i create a new bug report?

**Comment by McLive** [comment]
> The problem is resolved for the tracer bugs, Ghost players i can't tell yet. But when you enable it all my 20 players online lost their experience values... Should i create a new bug report?

Fixed some minutes ago :D 

https://github.com/SkinsRestorer/SkinsRestorerX/commit/5175917186870d2b16284cdd8d010913254baf99
