### ISSUE TITLE
command block not longer working

### ISSUE THREAD

**Issue by JulesdeCube** [SkinsRestorer/SkinsRestorerX#241]
## Describe the bug
can't open/edit command block command.
Existing comand block no longer execute their command
UI didn't open and block make no sound on place and when i break it
(no error in the console)

## How can we reproduce what you got?
1. create a basic bukkit server
2. op user
3. `/give user minecraft:command_block `
4. pace a command block with a command (ex : `/say hello`)
5. stop the the server 
6. add the `SkinsRestorer` plugin
7. reopen the server
8. try to run the command block => not working
9. place a other command block => no sound
10. try to right click on it  => no ui
11. break it  => no sound

**Expected behavior**
- can run command block,
- play sound on place and break
- can enter a command on it

## Server information

- **platform**: Bukkit

**What version? Spigot 1.15,2 (git-Spigot-2040c4c-893ad93)**
* SkinsRestorer: 13.7.6
* Java: 8

## Logs
https://hastebin.app/5ead46a5abcdc0001dd459f4

**Comment by xknat** [comment]
resolved on 763eea66fd04e473798ed1bc32c36dba65a4aa67
