### ISSUE TITLE
Server crash when server is attacked with bots

### ISSUE THREAD

**Issue by SaF3rC** [SkinsRestorer/SkinsRestorerX#242]
## Describe the bug
The server crashes because of bots spamming **/skin update** command.

## How can we reproduce what you got?
Bot a server using SkinRestorer and make the bots run /skin update

**Expected behavior**
The /skin update command's cooldown stops from bots spam.

**Screenshots**
![image](https://user-images.githubusercontent.com/20015713/80861261-b6895980-8c6d-11ea-90df-c3d9069fbeef.png)

## Server information

**On what platform does your server run? BungeeCord (Aegis Folk)

**What version? 
* SkinsRestorer: 13.7.6
* Spigot version: 1.12.2
* Bungeecord version: 1.15.x
* IF bungee, did you put the plugin on all servers: No
* Java: 8

## Logs
The same thing shown in screenshot section

## Additional context
Probably the problem comes with the blocking command system. The command is blocked correctly but plugin is still making a request to Mojang Skins API

**Comment by xknat** [comment]
@SaF3rC is this 13.7.6 or 13.7.6 snapshot?

**Comment by xknat** [comment]
@SaF3rC I looked things up. this was only inside a test build. Make sure to upgrade to 13.7.6

**Comment by xknat** [comment]
like stated, fixed in 13.7.6 final release
