### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

### ISSUE THREAD

**Issue by YellowZaki** [SkinsRestorer/SkinsRestorerX#244]
## Describe the bug
Today I found a lot users were being kicked with a strange message. I discovered SkinsRestorer had been auto updated to 13.7.7. I reverted back to 13.7.6, and the issue was solved.

## How can we reproduce what you got?
1. Use 13.7.7

## Server information

**On what platform does your server run? PaperSpigot**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.7
* Spigot version: PaperSpigot 1.13.2
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 11

## Logs
https://hastebin.app/5eaed1d5abcdc0001dd459ff

**Comment by xknat** [comment]
@YellowZaki update both spigot and bungee to 13.7.8

**Comment by xknat** [comment]
or better, use last dev build: https://ci.freecraft.eu/v2/job/SkinsRestorerX/203/artifact/target/SkinsRestorer.jar

**Comment by YellowZaki** [comment]
Still happening on the latest build. I want to stay at 13.7.6 which doesn't have the issue, but the autouptdater updates it althought I tell it not to do it.

**Comment by xknat** [comment]
@YellowZaki staying on the same version might fail in the future, we also want the new versions to not contain your issue.
Please give us more info regarding your issue.
Also are you using bungeecord?
It would be nice if you join our discord so we don't pollute the issue!

**Comment by YellowZaki** [comment]
I'm not running bungeecord, just skinsrestorer. I joined discord, but I think this issue is better to track the problem.

**Comment by xknat** [comment]
Okey, then please give me the following information needed:

1. your full latest logg containing the error with exception trace if any.
2. A copy of your skinsrestorer config
3. a screenshot of doing /sr status
4. a screenshot of /version
5. Is the server online or offline mode?
6. Are you using any multiverse or multi world plugin? if yes which one?
7. Are you using the legit launcher? if not which one?
8. Did you edit any skin file or add custom skins?
9. Are you using any scripting plugin?

**Comment by YellowZaki** [comment]
1. There is no more exception, just what I posted. https://hastebin.app/5eaed1d5abcdc0001dd459ff
2. https://hastebin.com/visopemuba.shell
3.
![image](https://user-images.githubusercontent.com/13599841/80959996-3e0ad000-8e08-11ea-9efa-ea0719de63e1.png)
4.
![image](https://user-images.githubusercontent.com/13599841/80960022-4bc05580-8e08-11ea-8d9f-77b79c53e065.png)
5. Offline mode
6. No, I just I have BentoBox which automatically load 2 worlds.
7. No, using Tlauncher
8. No
9. Yes, skript, but I just use it for a few thing, just I draft before exporting it to java.

**Comment by xknat** [comment]
1. Please provide us the full logg including at least 10 rows of information before the error that maybe does lead to encountering the error. Does the error random occur? does the error occur on startup without any one joining? does the error occur when some one performs a command or joins?
6. can you provide us the link to BentoBox ? This might cause some dimension issues...
7. if your using tlauncher, did you disable skin mod? 
To disable it, go under "Accounts settings" and uncheck the box as shown on the screenshot!
https://cdn.discordapp.com/attachments/645351110244171816/645351218197299201/Tlauncher.png
9. skript plugins can interfere with skinsrestorer as they might hook into skins or packets we use.
Try without the skript plugin and see if that resolves it for you. IF SO, you know its related to a issue between skript and skinsrestorer

**Comment by ray27890** [comment]
This issue is with ViaVersion and SkinsRestorer conflicting, ViaVersion devs are aware of this issue.

**Comment by xknat** [comment]
> This issue is with ViaVersion and SkinsRestorer conflicting, ViaVersion devs are aware of this issue.
link please?

**Comment by YellowZaki** [comment]
> > This issue is with ViaVersion and SkinsRestorer conflicting, ViaVersion devs are aware of this issue.
> 
> link please?

https://github.com/ViaVersion/ViaVersion/issues/1757

**Comment by McLive** [comment]
Can you please try the latest build from jenkins?

https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

**Comment by YellowZaki** [comment]
I was meant to say 13.7.6 sorry, I'll try the new build on next restart.

**Comment by McLive** [comment]
Then I'm not too sure it would fix your issue since that change was introduced with 13.7.6.

**Comment by YellowZaki** [comment]
It it was reverted from 13.7.6, I don't think it will work, since 13.7.6 works fine.
Maybe you could test by running ViaVersion and SkinsRestorer. Since it is happening to all users running both plugin. And considering ViaVersion and SkinsRestorer is a must have for every server...
I'm sure there are a lot of servers having the issue, but don't know what plugin is causing it

**Comment by xknat** [comment]
Can you send a list of your plugins?

**Comment by SaltyPotata** [comment]
I am having the same problem, and I don't know how to solve this issue. I am running Viaversion 2.2.3 with SkinRestorer 13.7.7 and  I always get this message: Unknown dimension network id 11. I will contain the full log if needed.

**Comment by xknat** [comment]
>  I will contain the full log if needed.

Yes please, it seems that OP is not providing this.

**Comment by McLive** [comment]
> Maybe you could test by running ViaVersion and SkinsRestorer.

![image](https://user-images.githubusercontent.com/5620071/81049399-6c4ae700-8ebe-11ea-9be0-d2e47a86dc63.png)

Works fine for me

**Comment by McLive** [comment]
![image](https://user-images.githubusercontent.com/5620071/81049499-9c928580-8ebe-11ea-8407-a5d8ef06e409.png)

**Comment by YellowZaki** [comment]
> > Maybe you could test by running ViaVersion and SkinsRestorer.
> 
> ![image](https://user-images.githubusercontent.com/5620071/81049399-6c4ae700-8ebe-11ea-9be0-d2e47a86dc63.png)
> 
> Works fine for me

Take into account that it only happens to some users, like 30 out of 100

**Comment by xknat** [comment]
@YellowZaki can you give us maybe more info that we can use? or work with to resolve your issue?
like ViaVersion build? 
ViaVersion config?

We can't reproduce your issue...
and since we are not getting the full server logg. we dont know what might trigger it...

**Comment by SaltyPotata** [comment]
> > I will contain the full log if needed.
> 
> Yes please, it seems that OP is not providing this.
> PS @SaltyPotata can you try our dev build? https://ci.freecraft.eu/v2/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

It seems to be working.

**Comment by ray27890** [comment]
ViaVersion 2.2.3 on 1.13.2 with latest SkinsRestorer should reproduce the issue.

**Comment by McLive** [comment]
> ViaVersion 2.2.3 on 1.13.2 with latest SkinsRestorer should reproduce the issue.

Please try again with SR 13.7.9

**Comment by xknat** [comment]
@ray27890 @YellowZaki please try with sr13.7.9

also... ![image](https://user-images.githubusercontent.com/10220139/81222947-71ef1c80-8fe5-11ea-8290-acb9d0b92607.png)

**Comment by YellowZaki** [comment]
I confirm SR 13.7.9 doesn't have the issue. Thank you!

**Comment by McLive** [comment]
👍
