### ISSUE TITLE
/skin update and custom skins

### ISSUE THREAD

**Issue by En0tS** [SkinsRestorer/SkinsRestorerX#246]
First of all:
![image](https://user-images.githubusercontent.com/36606833/80967198-9ea50780-8e1e-11ea-8f9f-9c7cd9ed6aaf.png)
![image](https://user-images.githubusercontent.com/36606833/80967233-abc1f680-8e1e-11ea-957d-b8a757b60759.png)
Second: Please disable updating skins via **/skin update** if skin have too high timestamp (10 after current date, for example). I use custom skins with mysql and my skins got replaced by original after /skin update even when I set timestamp to **2554408800000**.

**Comment by xknat** [comment]
updated wiki to real year 2050

**Comment by En0tS** [comment]
> updated wiki to real year 2050

But how about /skin update and custom skins?

**Comment by xknat** [comment]
We disabled skin update if the name of <name>.skin containce a blank space first.
example: `" skin4.skin"`
This way the skin update should not be possible but players can also not set the skin themselves i believe.

**Comment by En0tS** [comment]
> We disabled skin update if the name of .skin containce a blank space first.
> example: `" skin4.skin"`
> This way the skin update should not be possible but players can also not set the skin themselves i believe.

But what I should do with mysql? Add " " to skin name or what?

**Comment by En0tS** [comment]
> We disabled skin update if the name of .skin containce a blank space first.
> example: `" skin4.skin"`
> This way the skin update should not be possible but players can also not set the skin themselves i believe.

And how I can use that skin? After /skin aaa - plugin will create "aaa.skin" file and my " aaa.skin" will not be used.
![image](https://user-images.githubusercontent.com/36606833/81122839-74486c80-8f3a-11ea-9d7f-9b6e563acd50.png)

**Comment by xknat** [comment]
you would need to edit it into the player file
I think your ticket is related to #127 & #122 ?
then this ticket can be closed as duplicate.

**Comment by En0tS** [comment]
> then this ticket can b

Yeah, my ticket just more up to date. I use latest plugin version (13.7.9) and I still able break custom skin by _/skin update_ command. And really it will be good if custom skins will none require premium name. Maybe you could add to config some editable prefix like 'sr_'? So if skin name starts with that prefix: that skin not require premium name and will not update in any case.

**Comment by En0tS** [comment]
(sorry for my english)

**Comment by xknat** [comment]
there should be a way to disable it with a new `iscustom` flag in each skin file.

**Comment by xknat** [comment]
@En0tS has been done in 4ad7fa4c1f49b7e5f7bdcffd85ea55a044705a0f
Sorry for taking so long!

When you set the timestamp to "`0`", it will prevent /skin update.
