### ISSUE TITLE
Experience reset on join

### ISSUE THREAD

**Issue by ULTUX** [SkinsRestorer/SkinsRestorerX#247]
## Describe the bug
When joining player's experience level and progress is reset to 0.

## How can we reproduce what you got?
1. Add experience
2. Leave the game
3. Join the game

**Expected behavior**
A player's experience is the same as when he left the game.
**Screenshots**
## Server information
This server is running Paper version git-Paper-87 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper
**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.8
* Java: 1.8.0_251

**Comment by McLive** [comment]
Fixed by 5175917186870d2b16284cdd8d010913254baf99
