### ISSUE TITLE
handle mineskin JsonSyntaxException

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#248]
from spigotmc by LordRamma [[link](https://www.spigotmc.org/threads/skinsrestorer.37225/page-182#post-3791697)]

Expected behavior: handle as error for user to try again later

[SkinsRestorer] [ERROR] could not generate skin url:
04.05 09:55:18 [Server] WARN com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
04.05 09:55:18 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:65)
04.05 09:55:18 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:45)
04.05 09:55:18 [Server] WARN at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:76)
04.05 09:55:18 [Server] WARN at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:50)
04.05 09:55:18 [Server] WARN at skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:202)
04.05 09:55:18 [Server] WARN at skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:147)
04.05 09:55:18 [Server] WARN at skinsrestorer.bukkit.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:139)
04.05 09:55:18 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
04.05 09:55:18 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
04.05 09:55:18 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
04.05 09:55:18 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
04.05 09:55:18 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
04.05 09:55:18 [Server] WARN at java.lang.Thread.run(Thread.java:748)
04.05 09:55:18 [Server] WARN Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
04.05 09:55:18 [Server] WARN at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
04.05 09:55:18 [Server] WARN at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
04.05 09:55:18 [Server] WARN at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
04.05 09:55:18 [Server] WARN at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
04.05 09:55:18 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:60)
04.05 09:55:18 [Server] WARN ... 12 more

**Comment by McLive** [comment]
https://github.com/SkinsRestorer/SkinsRestorerX/commit/f0ce7cd4617c39ce9a41bd487c2d04ffafb5f343
