### ISSUE TITLE
Tries To Name A File With a *

### ISSUE THREAD

**Issue by Loganh4005** [SkinsRestorer/SkinsRestorerX#252]
## Describe the bug
I Use an auth plugin that adds a * to the name and on windows, you cannot name something with * so 15:18:19 [SEVERE] java.io.IOException: The filename, directory name, or volume label syntax is incorrect on bungeecord. Some Ways to fix it would be 1. To replace the * with the Unicode Format or something like that, or 2. Do what essentials does and replace it with _ I use Floodgate https://github.com/GeyserMC/Floodgate

## How can we reproduce what you got?
1. Run /skin set [Username]
2. See error

**Expected behavior**
Names With * Should Be Accepted

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

Bungeecord, Paper

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.
* Spigot version:
* Bungeecord version: 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8

 Current version: 13.7.5

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app
https://hastebin.app/5eb49793abcdc0001dd45a0b

**Comment by DoctorMacc** [comment]
I'm a representative of Geyser/Floodgate if there's anything I can do.

**Comment by Heath123** [comment]
To be precise this auth plugin is https://github.com/GeyserMC/Floodgate
Another potential fix is to use the UUID instead of the name. Using a name for storing data causes problems when changing your name and isn't good practice

**Comment by xknat** [comment]
Replace it to a !

**Comment by McLive** [comment]
A username with an '*" is not what you expect since its not a valid minecraft username.

**Comment by Heath123** [comment]
Using a UUID would be better

**Comment by xknat** [comment]
@Loganh4005 Has your issue been resolved? can this ticket be closed?

**Comment by Loganh4005** [comment]
It Still Happens :| Plz change 2 UUID
Isn't it SUPOST to be for offline servers? You can have that in your name using offline mode and I am not changing it from *

**Comment by xknat** [comment]
I Use an auth plugin that adds a * to the name and on windows, you cannot name something with *
Like i did mention. you can use ! without any issue as we already resolved a ticket this way. 

We gave you the solution to your issue. This is not a work around but a real solution to your issue.
hence ticket can be closed. 

THIS is also a user problem. something we dont use github for!

**Comment by Heath123** [comment]
> 
> 
> I Use an auth plugin that adds a * to the name and on windows, you cannot name something with *
> Like i did mention. you can use ! without any issue as we already resolved a ticket this way.
> 
> We gave you the solution to your issue. This is not a work around but a real solution to your issue.
> hence ticket can be closed.
> 
> THIS is also a user problem. something we dont use github for!

This isn't a proper solution, it's a workaround. Naming things based on usernames isn't generally a good idea. Thats what UUIDs are for.

**Comment by Heath123** [comment]
I think this should be reopened

**Comment by McLive** [comment]
`[a-zA-Z0-9_]{1,16}` are valid minecraft usernames. I really don't see the need to support anything else. Any other name can't even have a skin stores on Mojang servers.

**Comment by Loganh4005** [comment]
I don't want to use an ! because ! is noticeable and * isn't it supost to be for offline offline supports * on the name change to uuid

**Comment by xknat** [comment]
I don't want to use an ! because ! is noticeable
a ' would be less less noticeable... 
so your not rly making sense....

**Comment by Loganh4005** [comment]
But it would reset all bedrock's progress
