### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DenisJ9798** [SkinsRestorer/SkinsRestorerX#253]
10:51:43 [INFO] [SkinsRestorer] [ERROR] could not generate skin url:
10:51:43 [SEVERE] java.lang.NullPointerException
10:51:43 [SEVERE] 	at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:96)
10:51:43 [SEVERE] 	at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:58)
10:51:43 [SEVERE] 	at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:203)
10:51:43 [SEVERE] 	at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:145)
10:51:43 [SEVERE] 	at skinsrestorer.bungee.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:135)
10:51:43 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
10:51:43 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:51:43 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:51:43 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)

**Comment by xknat** [comment]
@DenisJ9798 please try out our devbuild: https://ci.freecraft.eu/v2/job/SkinsRestorerX/

**Comment by xknat** [comment]
This commit should have solved your issue: 
https://github.com/SkinsRestorer/SkinsRestorerX/commit/cd7083e89b34e8f92a9ddee2ee66197126ce0927#
WIll be released on nexst version
