### ISSUE TITLE
Biome mods issue

### ISSUE THREAD

**Issue by Bob74** [SkinsRestorer/SkinsRestorerX#255]
## Describe the bug
The plugin doesn't work using biomes mods (for hybrid server Mods+Plugins).
Someone posted a detailed report of this bug [here](https://github.com/magmafoundation/Magma/issues/108). I can confirm this occurs using Mohist too.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Mohist 1.12.2-6339caa
https://github.com/Mohist-Community/Mohist

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.9
* Mohist version: 1.12.2-6339caa
* Java: OpenJDK 1.8.0_242
* Biome mod: Biomes O'Plenty 1.12.2-7.0.1.2441

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com/Bob74/d96904a5efa8f892abe8db556b99b9ea

## Additional context
Please check the issue here if you need any additional details:
https://github.com/magmafoundation/Magma/issues/108

**Comment by xknat** [comment]
We no longer support Mohist
