### ISSUE TITLE
PlaceholderApi & Skinsrestorer

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#258]
- [x] current skin name
- [ ] total skin count?

**Comment by AfkF24** [comment]
Sounds cool to have. Will the placeholders be available if the plugin is running in Bungee mode, but with SkinsRestorer installed on Spigot servers as well?

**Comment by aljaxus** [comment]
> but with SkinsRestorer installed on Spigot servers as well?

This is also one of the goals, yeah. PlaceholderAPI is usually used on subservers not on bungee :P

**Comment by xknat** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#internal-class
Bukkit.getPluginManager().isPluginEnabled("PlaceholderAPI")

**Comment by xknat** [comment]
https://api.extendedclip.com/expansions/skinsrestorer/ created. 
it should work if your using bukkit only.
If there are any more we need to add let us know.
