### ISSUE TITLE
Plugin causing lag.

### ISSUE THREAD

**Issue by ImHumbug** [SkinsRestorer/SkinsRestorerX#259]
It's simple, SkinsRestorer::Task: skinsrestorer.bukkit.skinfactory.UniversalSkinFactory$$Lambda$4899/0x00000008019e9c40 (Single) cause tiny spikes. https://timings.aikar.co/?id=19ab5b533b724c6e8f614e354da97d2d

**Comment by xknat** [comment]
> it's simple, 
how about AuctionHouse? 
![image](https://user-images.githubusercontent.com/10220139/82478468-3ec28800-9ad1-11ea-9028-ba8f4e3505aa.png)
seems fine right for just your usual auction plugin xd

**Comment by xknat** [comment]
If you want support. join our discord.
if you want it fixed, create a pr or help us out on discord
