### ISSUE TITLE
Player Lost Skin When Changing UUID

### ISSUE THREAD

**Issue by Xuwznln** [SkinsRestorer/SkinsRestorerX#260]
I write a login system for my server which is running on BungeeCord side. After the player login success, my plugin will change his UUID to a specific one, using relfection. But I got a problem: player can only see skins of other players but cant see himself after his uuid is changed on server side. I want to know the cause and try to solve that. Thanks guys.

**Comment by xknat** [comment]
Please join our disord for support so we dont spam this ticket.
We use github only for proven code issues.
So untill proven please join our discord.
