### ISSUE TITLE
Cancel message when blank in locale

### ISSUE THREAD

**Issue by AzonFR** [SkinsRestorer/SkinsRestorerX#261]
Hey, is it possible to add this feature:
https://i.gyazo.com/thumb/1200/a2d9a4e74813bc078dc000aee446b08a-png.jpg
When we don't set a message like in the screenshot, the message is cancelled.
With the latest version it send a blank message and i want to disable it and i think it's actually a good and simple feature to do :)
Thanks !

**Comment by xknat** [comment]
undecided as we would need to check this with https://github.com/aikar/commands
