### ISSUE TITLE
Custom skin file & skins GUI not working

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [SkinsRestorer/SkinsRestorerX#263]
## Describe the bug
The skin is a 1.7 skin and use many tool to convert to 1.8 get same final result...  
upload it to https://riflowth.github.io/SkinFile-Generator/  
and set skin name as "nnn3_520_offline"

When load it use `/skins` menu, it show as a default steve skin  
after set, still a Steve

Many other skin can work normally.

## How can we reproduce what you got?
![nnn3_520](https://user-images.githubusercontent.com/10773245/83157018-b4fc6580-a135-11ea-8908-5e5abeb442de.png)

This is the skin, seems GitHub will not compress it to jpg.

**Screenshots**
![image](https://user-images.githubusercontent.com/10773245/83157111-ce9dad00-a135-11ea-8f61-358557bd0866.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Spigot

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.9
* Spigot version:

```
[INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```

* Java: 8

## Logs
https://hastebin.app/5ecfd12c044135001c5e9fa1

**Comment by mhtvsSFrpHdE** [comment]
My player default skin is Alex, as extra information

**Comment by xknat** [comment]
@mhtvsSFrpHdE can you try with a legit minecraft username as skin name
for example: "skin1"

**Comment by mhtvsSFrpHdE** [comment]
@xknat Will test when I got free time.  
I use it to let player set skin who doesn't own a Minecraft account,  
so their file will name as a not exist MOJANG Minecraft player name to avoid conflict.

Didn't realize `nnn3_520_offline` can be so wrong, if that was indeed the problem.

**Comment by mhtvsSFrpHdE** [comment]
@xknat 

![image](https://user-images.githubusercontent.com/10773245/83333164-dbef9e80-a2d1-11ea-8aa6-9b92adfa9a8d.png)
skin1 name reporduced same result

**Comment by xknat** [comment]
@mhtvsSFrpHdE done in https://github.com/SkinsRestorer/SkinsRestorerX/commit/80bec1908fbde93c40fe1488cb125a272b4c7d83
