### ISSUE TITLE
Skins not showing client side on 1.16.1

### ISSUE THREAD

**Issue by BackgroundPony** [SkinsRestorer/SkinsRestorerX#266]
Skins are not being shown on the client when new skins are set. Guessing its to do with protocol changes? Players can still see/set skins just fine but are only shown to other users.

**Comment by xknat** [comment]
the fact that you do mention protocol changes makes me wonder if you know how to use our plugin as we not require any additional plugin.

Also, 1.16.1 is not on the compatibility list. its on your own risk to test it out
