### ISSUE TITLE
adding 1.16.1 compatibility 

### ISSUE THREAD

**Issue by D3nHD** [SkinsRestorer/SkinsRestorerX#267]
Upon joining the server console throws an error and players load in without skin, also running the command /skin doesn't give them their skin back.

Console error
![unknown-75](https://user-images.githubusercontent.com/67413819/85690527-f6037d80-b6d3-11ea-958c-ebfe2916b1b9.png)

Using Spigot 1.16.1

**Comment by xknat** [comment]
we dont support 1.16.1 yet 🤦
