### ISSUE TITLE
[1.16.1] /skin gives an exception

### ISSUE THREAD

**Issue by Insane96** [SkinsRestorer/SkinsRestorerX#268]
## Describe the bug
Running the /skin command gives an exception

## How can we reproduce what you got?
1. Run the command from a player in game
2. Check server console

**Expected behavior**
To open a GUI

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Spigot

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.7.9
* Spigot version: 1.16.1-2708
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
This includes even another error when I've joined the game
https://gist.github.com/Insane96/21074334b5ff6592238f1294198292c0

**Comment by xknat** [comment]
see #269
