### ISSUE TITLE
Spam error console

### ISSUE THREAD

**Issue by Zeuly** [SkinsRestorer/SkinsRestorerX#270]
Hello, 

I noticed for some time an error coming from skinrestorer in my console without paying attention until now. I would like to know if you would have a solution to this error which is displayed a lot of times
This error only appears when connecting certain players

https://pastebin.com/raw/LwLVgHf4

## Server information
-Spongeforge-1.12.2-2838-7.2.1
-SkinsRestorer: 1.12.2
-Waterfall

**Comment by xknat** [comment]
@Zeuly we do not support forge
