### ISSUE TITLE
[1.16] Skins are not working

### ISSUE THREAD

**Issue by x9nico** [SkinsRestorer/SkinsRestorerX#276]
## Describe the bug
My skin are not loaded.
I tried to update my skin with /skin, I'm still with Alex skin.

## How can we reproduce what you got?
1. Update your server in 1.16.1
2. Connect to your server

**Expected behavior**

My  default skin.

**Screenshots**

https://i.gyazo.com/2b92ca11d01a2ee8f6348686d99152bf.jpg
My skin are not loaded.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper 1.16.1 build 27.

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.0
* PaperSpigot version: Build 27 in 1.16.1
* Bungeecord version: Not used
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
No errors.

**Comment by xknat** [comment]
Please list your plugins and show your /sr status.
Support is normally given on discord, so we highly recommend going to discord for (faster) support.

**Comment by x9nico** [comment]
My plugins:
https://i.gyazo.com/1d5fa166a46db6a15777da938ae16eef.png
The cmd: https://i.gyazo.com/02d1889282d403c13f716d3655fd6d05.png
Sorry if I'm sending it there, I don't have the time actually.

**Comment by xknat** [comment]
For fast login, please set forwardSkin: false in config.yml

**Comment by x9nico** [comment]
I tried, but it don't work.

**Comment by xknat** [comment]
your connecting from atleast 1.8.8?

**Comment by x9nico** [comment]
It affect only 1.16.1 servers.
>= to 1.15.2 servers, it works perfectly.

**Comment by xknat** [comment]
> from 1.8 to 1.15.2 servers, it works perfectly.
you mean when they join on those versions? or when you host the server on those versions?

**Comment by x9nico** [comment]
When I'm hosting a 1.8-1.15.2 with 1.16.x clients, it works.
But when I'm host 1.16.1 servers with 1.16.1 players, it don't work.

**Comment by saiyzh** [comment]
not work in my spigot 1.16.1 server ,it doesn't create the folder.
![image](https://user-images.githubusercontent.com/40679184/86312552-90743b80-bc55-11ea-94b7-1ecd67a2c2ce.png)

**Comment by x9nico** [comment]
For me, the folder is working.

**Comment by xknat** [comment]
@saiyzh update and if you use bungee, upload it to also bungeecord.

**Comment by x9nico** [comment]
@xknat Do you have any solutions for my problem ?

**Comment by xknat** [comment]
@x9nico issue comes from #277 .
keep an eye on the issue.

**Comment by x9nico** [comment]
@xknat I done a test without ViaVersion & ViaBackwards, I have still the problem.
It don't comes from them.

**Comment by xknat** [comment]
join our discord and we take a look at it.
