### ISSUE TITLE
MC1.16 & Protocolhack incompatibility 

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#277]
1.16 refresher is separated from the other versions. and thus not backward compatible.???
-> more research needed.

**Comment by McLive** [comment]
https://github.com/ViaVersion/ViaVersion/issues

**Comment by xknat** [comment]
Seems that The old refresher works with via backwards, but not with the paper refresher.

**Comment by NickAcPT** [comment]
I've been also hitting this issue, so here's what I know.
Paper's way of refreshing the player is on [this patch file](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0202-Player.setPlayerProfile-API.patch). It was partially done by me. I basically looked at how SkinsRestorer and other plugins did it at the time, and made sure to implement it at the NMS level.

I guess that, with time, more work needs to be done to be sure that it works with external plugins like Via.
Maybe someone could PR changes to that patch and make it do the same actions that the old refresher took.

**Comment by xknat** [comment]
Seems to be that the OldSkinRefresher is now also giving issues making this not only paper issue....
More info is needed on which SR and which ViaVersion was compatible to spot changes. 

could be a 1.16 thing but just making sure.

**Comment by xknat** [comment]
Hey there @NickAcPT 
Sadly i was not able to make it work.
The way we import virtual method and use "invoke" goes way over my skill level.
1.15.2 with SR & viabackwards works, but not on 1.16.2.

A PR would be rly rly appreciated as i doubt i will be able to fix the paper refresher any time soon...
same goes for oldSkinRefresher, but that seems less technical.
If you need me i am on the discord.

**Comment by NickAcPT** [comment]
@xknat Oh, I see. Thanks a lot for attempting to do this fix though. If I have the time, I'll attempt to give this a look.

**Comment by xknat** [comment]
Hey @NickAcPT,
I know it's been over a month and i keep on walking to a death end.
Let me know if this is even something we can do on our side. Maybe all other skin plugins have the same issue?

**Comment by xknat** [comment]
Seems to be an issue with https://github.com/ViaVersion/ViaVersion
https://github.com/ProtocolSupport/ProtocolSupport works just fine on 1.16.3!

Viaversion should definitely try to fix this issue...
other plugins are having the same, hence they should fix it or switch to ProtocolSupport

**Comment by Logics4** [comment]
ProtocolSupport had worked around this issue, that's why SkinsRestorer worked with it and not with ViaVersion/ViaBackwards.

Anyway, this incompatibility has been fixed by @DoctorMacc in PR #345 .
