### ISSUE TITLE
Leak of world seed in 1.16

### ISSUE THREAD

**Issue by games647** [SkinsRestorer/SkinsRestorerX#281]
Hey,

Someone referenced your refresh code on the `ChangeSkin`. For `ChangeSkin` I took a deep dive on how the `respawn` packet is implemented using Paper's code and wiki.vg. I noticed that your approach is only slightly different in comparison what we choose. Nevertheless your code seems to use the original world seed on skin change instead of hashing it. 

https://github.com/SkinsRestorer/SkinsRestorerX/blob/40fa15768ecde41c61c02f1692cd7c83974fa07a/src/main/java/skinsrestorer/bukkit/skinfactory/LegacySkinRefresher_v1_16_R1.java#L74

I didn't invest more time into it. Maybe I just read it wrong. If so, I'm sorry and will edit the title. If not, I'm happy to help.

EDIT: This could be used for offline XRay.

**Comment by McLive** [comment]
Yes you're right, it should only cover the first 8 bytes of the hashed seed. Thanks for pointing that out!
