### ISSUE TITLE
DisabledSkins not working

### ISSUE THREAD

**Issue by disqetow** [SkinsRestorer/SkinsRestorerX#285]
## Describe the bug
DisabledSkins not working with lastet SkinsRestorerX
(Bungeecord and Spigot)

## How can we reproduce what you got?
Put SkinsRestorerX to plugin, and set config, open DisabledSkins 

**Expected behavior**
I am not op

**Screenshots**
https://imgur.com/a/43vtPXr

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)** Bungeecord and Spigot

**What version? Do NOT answer LATEST**
* SkinsRestorer: LATEST
* Spigot version: 1.12.2
* Bungeecord version:  LATEST
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
There is nothing about this at console

## Additional context
No

**Comment by xknat** [comment]
1. Github is only used for coding issues. This is a user problem. For user support. Please go to our discord.
2. I notice your making the essential mistake of not reading our "how to install".
I would like to inform you that by reading "how to install bungee", your question/problem would be resolved
