### ISSUE TITLE
/skin causes desync when mounted

### ISSUE THREAD

**Issue by theconezone** [SkinsRestorer/SkinsRestorerX#289]
## Describe the bug
Using /skin update or /skin set while mounted/sitting causes the client to desync. I have not been able to reproduce it, but one player informed me they were able to duplicate a shulker using this desync.

## How can we reproduce what you got?
1. Mount a horse
2. Type /skin update
3. You can now roam around and place/break blocks and interact with containers while the server and other players still see you as mounted.

**Expected behavior**
The player not be desynchronized.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.2
* Spigot version: Paper 125
* Java: 8

## Additional context
The fix to this is simple, dismount (using Player.getVehicle().eject()) the player right before setting the skin. This fixes the issue for both sitting and any type of mounting. I have been able to emulate this fix by using an alias to teleport a player to themselves (which dismounts them) right before running the skin command, but it's unreliable.

**Comment by xknat** [comment]
Already known and confirmed

**Comment by xknat** [comment]
brainstorm: reloading the chunk might be needed when perform such task, but this might be an issue with xray etc for some servers.

**Comment by theconezone** [comment]
I believe the solution would be to dismount the player synchronously (using the bukkit scheduler) after all the heavy/laggy work is done in the asynchronous task, but before applying the player skin.

I have been using an alias that simply runs: /tp player player -- which dismounts the player. This works great for using the skin command with a player name, but because using /skin with an image URL is so much slower, it doesn't work so well (they just mount up again before it completes).

I thought about writing up a pull request, but I have been busy. If you'd like, I can see what I can come up with.

**Comment by xknat** [comment]
> I thought about writing up a pull request, but I have been busy. If you'd like, I can see what I can come up with.
sure! but i can prob also come up with something. 
if you say dismount work, i will try that out

**Comment by theconezone** [comment]
> 
> 
> > I thought about writing up a pull request, but I have been busy. If you'd like, I can see what I can come up with.
> > sure! but i can prob also come up with something.
> > if you say dismount work, i will try that out

I wouldn't be able to work on it until my weekend anyway. I'll let you handle it. Let me know if you need help testing or something. I've been reproducing this on and off testing.
