### ISSUE TITLE
/sr reload wont work for SkinsWithoutPerms

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#290]
this is annoying and users do not understand a restart is needed.
A. fix this by making reload work
B. make it more clear in the config that a full server restart is required.

**Comment by aljaxus** [comment]
> 
> 
> this is annoying and users do not understand a restart is needed.
> A. fix this by making reload work
> B. make it more clear in the config that a full server restart is required.

Option B until A is developed (or straight up A if it's easy enough to put out in the next plugin release)

**Comment by xknat** [comment]
Update: This is due to the fact that the command replacement maps we use are both static and ImmutableMap.
This should increase performance vs the effect of sr reload by having the values cached??
Would need to do some performance testing on this as having to restart for small changes is not ideal.

**Comment by xknat** [comment]
Resolved
