### ISSUE TITLE
Server hangs while checking skin

### ISSUE THREAD

**Issue by Bloodlex** [SkinsRestorer/SkinsRestorerX#291]
## Describe the bug
The server has severe lags and hangs for a couple of seconds everytime a command regarding skins is issued. Problem is with such plugins like [CustomHeads](https://www.spigotmc.org/resources/custom-heads-1-8-1-16.29057/) for instance.

## How can we reproduce what you got?
1. Install CustomHeads
2. Use command /heads
3. Server hangs for a couple of seconds

It doesn't happen everytime. I don't know why it happens for some players and other don't. Maybe it's related to Minecraft premium or not, we play in Offline-Mode.

**Expected behavior**
It should not hang the server.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
SkinsRestorer: 13.8.2
Spigot version: Paper-384 (MC 1.15.2)
Java: 8

## Logs
https://pastebin.com/b9ncFavN

## Additional context
Happens with different commands accessing skins.

**Comment by xknat** [comment]
Your using mysql?
how big is your server?
how many skins are in your database?

**Comment by Bloodlex** [comment]
> Your using mysql?
> how big is your server?
> how many skins are in your database?

I'm not using mySQL, server is not so big I have 28 skins in my database. Please help 😢

**Comment by xknat** [comment]
can you catch it by running a timings report?

**Comment by Bloodlex** [comment]
> can you catch it by running a timings report?

hmm... I tried it now with one of my player but it didn't happen for him now, but it's quite often

**Comment by Bloodlex** [comment]
> can you catch it by running a timings report?

Okay, I have it 👍 

[https://timings.aikar.co/?id=b22746647aa540f9ba64e31051c41897](https://timings.aikar.co/?id=b22746647aa540f9ba64e31051c41897)

Console:

[https://pastebin.com/GVeqe8tA](https://pastebin.com/GVeqe8tA)

**Comment by xknat** [comment]
![Screenshot_20200805-113225](https://user-images.githubusercontent.com/10220139/89396854-5fcd6900-d70f-11ea-8a11-494187529374.png)
Think its custom hats
