### ISSUE TITLE
add mysql 8 compatability

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#292]
mysql 8 gives "Connection Java-MySql : Public Key Retrieval is not allowed"
having "allowPublicKeyRetrieval=true" in the mysql url should be optional and true (by default??)

**Comment by MaksymSemenykhin** [comment]
> mysql 8 gives "Connection Java-MySql : Public Key Retrieval is not allowed"
> having "allowPublicKeyRetrieval=true" in the mysql url should be optional and true (by default??)

or connection string should be more customizeble

**Comment by xknat** [comment]
@MaksymSemenykhin done in https://github.com/SkinsRestorer/SkinsRestorerX/commit/33d1f171ddd9231bdb795d17f36353fe87d43027
