### ISSUE TITLE
improved Updatechecker

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#298]
Why? so players have the option to **delay** updates.
dev notes: https://stackoverflow.com/questions/11874919/parsing-json-string-in-java?answertab=votes#tab-top
https://stackoverflow.com/questions/15871309/convert-jsonarray-to-string-array?answertab=votes#tab-top
https://stackoverflow.com/questions/1568762/accessing-members-of-items-in-a-jsonarray-with-java?answertab=votes#tab-top
https://stackoverflow.com/questions/17037340/converting-jsonarray-to-arraylist?answertab=votes#tab-top

todo:

- [x] use https://api.github.com/repos/SkinsRestorer/SkinsRestorerX/releases as a single request to get both (latest & current version behind)
- [x] deal with -snapshot downgrading by 1 so they also update to full version when it comes out.
- [x] upgradeneeded?
  - [x] include config option to delay
  - [x] "-snapshot" increase version age by 1
- [ ] reuse the api to download version latest file
  - [x] asset url gained. 
  - [ ] download method?
  - [ ] have a long download time
  - [ ] Cancel when server is stopped before finish.
- [ ] send message when jar has been updated. 
- [ ] own method for download the jar and replacing it. 
  - [ ] check api latest file size and compare with downloaded (must have margin)

**Comment by xknat** [comment]
this issue does replace https://github.com/SkinsRestorer/SkinsRestorerX/issues/298

**Comment by molor** [comment]
Maybe you can just disable updater completely until this issue is resolved? Please.

**Comment by xknat** [comment]
> Maybe you can just disable updater completely until this issue is resolved? Please.

no, we don't want a repeat of what happen when mojang started blocking servers or changing the api.
We will allow delay of the update.
If you want to disable the updater you can always create a fork and remove it.

**Comment by molor** [comment]
If anyone else wants to disable updates as well (bukkit):

1. `git clone` this repository
2. go to [SkinsRestorer.java#L201-L203](https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/SkinsRestorer.java#L201-L203) and CTLR+X & CTRL+V these lines after [SkinsRestorer.java#L81](https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/SkinsRestorer.java#L81)
3. run `mvn clean package`

Now `Updater.Enabled` = `false` in configuration will work.
Why developer decided to read setting from the config file first and only then load entire config from disk, I don't know.

**Comment by xknat** [comment]
in 5dd20c43c3d878d81f77e4818cb8d57b2e9330af you can now disable the updatechecker.
We found that having the update delayed will still cause issues for instances when there is no internet to github or when server owner do not want to update due to circumstances.

It is not on us to mitigate the risk of server not updating by enforcing updates that can not be disabled.
Starting with v14. you can now disable the updater.
