### ISSUE TITLE
Change of skin on server change

### ISSUE THREAD

**Issue by Bart0o** [SkinsRestorer/SkinsRestorerX#321]
About:
- skin change at server change (obviously bungeecord)

Currently when you change the skin you have to exit and re-enter to actually change the skin. It would be very convenient and nice to refresh the skin on server change (if the player doesn't have his own skin).

**Comment by xknat** [comment]
User issue, read installation.

**Comment by Bart0o** [comment]
How? I meant without adding the plugin even in spigot servers

**Comment by xknat** [comment]
go to discord for user support
