### ISSUE TITLE
replace all static patch with getdatafolder

### ISSUE THREAD

**Issue by TOWUK** [SkinsRestorer/SkinsRestorerX#324]
= DEV =
![image](https://user-images.githubusercontent.com/28830162/94365930-7378c880-00dd-11eb-88a4-bf22ed38cfa6.png)

## Describe the bug
Patch config folder not correctly!

## How can we reproduce what you got?
i use startup parameters in start.bat

**Screenshots**
![image](https://user-images.githubusercontent.com/28830162/94363491-1ffd7f00-00cb-11eb-8a23-632bc07715a8.png)
is startup paper

![image](https://user-images.githubusercontent.com/28830162/94363502-360b3f80-00cb-11eb-944a-dad2fb893fdc.png)
![image](https://user-images.githubusercontent.com/28830162/94363505-3c012080-00cb-11eb-8251-1f140f7bb0bb.png)
![image](https://user-images.githubusercontent.com/28830162/94363511-44f1f200-00cb-11eb-91f9-e89734ff387c.png)
![image](https://user-images.githubusercontent.com/28830162/94363612-0c064d00-00cc-11eb-9b3a-3bd80398e82c.png)

---

![image](https://user-images.githubusercontent.com/28830162/94363514-4d4a2d00-00cb-11eb-89d2-690b80527d31.png)
![image](https://user-images.githubusercontent.com/28830162/94363617-13c5f180-00cc-11eb-8bd8-c1df7cf5b500.png)

lol, what is? my folder plugins is SERVER/PLUGINS

## Server information
* SkinsRestorer: 13.8.4
This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
* Java: 15
* MinecraftLauncher?: TL

**Comment by xknat** [comment]
Please post start.bat script.

**Comment by TOWUK** [comment]
> Please post start.bat script. (non screenshot)

```
@echo off
chcp 1251
cls
title %USERNAME% - %CD%
IF EXIST "eula.txt" (
    @echo EULA founded...
) ELSE (
    @echo EULA not founded! Create eula.txt...
    @echo eula=true>eula.txt
)
:server
@echo Start paper...
java -Xms1G -Xmx10G -XX:+UseG1GC -jar paper.jar -org.spigotmc.netty.disabled=true -C SERVER/commands.yml -P SERVER/PLUGINS -S SERVER/spigot.yml -W SERVER/WORLDS -b SERVER/bukkit.yml -c SERVER.cfg -p 25001 --paper SERVER/paper.yml --server-name PAPER1 --nogui
@echo Reloading paper...
goto server
```

**Comment by TOWUK** [comment]
> Please post start.bat script. (non screenshot)

just copy code from folder (Player and Skins) to config.yml... :)

**Comment by xknat** [comment]
seems that we use static config path on bukkit.
let me check for you

**Comment by TOWUK** [comment]
> seems that we use static config path on bukkit.
> let me check for you

yes static patch folder 😁 good work! i wait new fixed release, thanks!

**Comment by xknat** [comment]
done :)

**Comment by TOWUK** [comment]
skins restorer still creates an empty folder in the static plugin path
![image](https://user-images.githubusercontent.com/28830162/94365219-a9b34980-00d7-11eb-8df4-dc02ffac006b.png)

**Comment by xknat** [comment]
@TOWUK try last commit, try with that one

**Comment by TOWUK** [comment]
> @TOWUK try last commit, try with that one [3da4e65](https://github.com/SkinsRestorer/SkinsRestorerX/commit/3da4e6594208fce5ebf4d05567409e2a8752fd85)

i use latest commit from actions

**Comment by TOWUK** [comment]
> @TOWUK try last commit, try with that one [3da4e65](https://github.com/SkinsRestorer/SkinsRestorerX/commit/3da4e6594208fce5ebf4d05567409e2a8752fd85)

i test it, worked. thanks

**Comment by TOWUK** [comment]
![image](https://user-images.githubusercontent.com/28830162/94365930-7378c880-00dd-11eb-88a4-bf22ed38cfa6.png)
hmmm, fix all static patch? :)

**Comment by xknat** [comment]
I did notice that we do mess up getConfigPath() with getDataFolder() ??
Are these 2 the same or should we define both configPath & dataPath differently?

**Comment by Logics4** [comment]
There is a getConfigPath() in Bukkit?
Judging by the name it should return the exact path to config.yml. getDataFolder() returns the `plugins/SkinsRestorer/` folder (and it's the method I see being used the most).

**Comment by xknat** [comment]
This seems to have been done in the recent commits.
It also does break compatibility with older versions that do not have getdatafolder.
