### ISSUE TITLE
skin set <player> <skin> & floodgate wont work

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#329]

**Comment by xknat** [comment]
duplicate of 357

**Comment by AlexProgrammerDE** [comment]
> 
> 
> duplicate of #357

But #357 was after this issue? So #357 is a duplicate of this?

**Comment by xknat** [comment]
Ah yeah, think #357 is the result issue of this one, or this one has already been resolved and #357 is the new issue
