### ISSUE TITLE
Block on top vehicle makes you clip through ground.

### ISSUE THREAD

**Issue by MithrandirCraft** [SkinsRestorer/SkinsRestorerX#330]
## Describe the bug
When on top of a block, and on top of that block also a minecart (or probably any other mountable vehicle), you can glitch through the floor after updating your skin.

## How can we reproduce what you got?
1. Create a 1 block thick surface on top of which to place a minecart (with or without a rail beneath it).
2. Mount the minecart.
3. Use /skin update or /skin clear.
4. By now you should have (visually) glitched through the floor, but you cannot interact with anything or anyone, the rest of the players will still see you on top of the minecart (because you actually are still on the minecart for the server, but not for the client).

**Expected behavior**
I mean, you certainly shouldn't glitch through the floor for doing this, even though it's visual. And it's certainly very confusing.

## Server information

* Paper: 174
* Waterfall: 379
* SkinsRestorer: 13.8.4
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8
* plugin list bungee & spigot: 
Spigot plugins (47): 40ServidoresMC, AdvancedPortals, AntiXrayHeuristics, AuthMe, AutoMessage*, BetterChair, BottledExp, BungeeTabListPlus, ChatControl, ClearLag, CoreProtect, CrazyCrates, DisableSuffocation, DiscordSRV, ElytraBalance, EnjinMinecraftPlugin, Essentials, EssentialsSpawn,  (WorldEdit)FastAsyncWorldEdit, FastLogin, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HolographicScoreboard*, LibsDisguises, LuckPerms, MarriageMaster, MiniaturePets*, MythicMobs, NerfVillages, NoCheatPlus, PlaceholderAPI, PlayerHeads, PremiumVanish, ProtocolLib, Shopkeepers, SkinsRestorer, Spawner, SSX-Connector*, StatsPvP*, TradeSystem, Vault, ViewDistanceTweaks, VoidSpawn, Votifier, VotingPlugin, Wild
Waterfall plugins (12): ViaVersion, SkinsRestorer, ServerListPlus, NuVotifier, LuckPerms-Bungee, FastLoginBungee, BungeeTabListPlus, BungeeControl, BungeeAliases, AuthMeBungee, AntiBot, AdvancedBan
* MinecraftLauncher?: Vanilla Java Oficial Client

**Comment by xknat** [comment]
Related to #280

**Comment by Grizzly90** [comment]
Similar happens with the sit command from cmi.

Take place on stairs. Change skin. Your client thinks that you stand up, while the server and other clients still see you siting. On pressing sneak you will be teleported back to the original siting position.

**Comment by xknat** [comment]
Yeah dismount would be needed.

**Comment by MithrandirCraft** [comment]
"players riding any vehicle often get dismounted from it in mid travel" This is no longer reproduceable, so I'm removing it from the report.

So currently the only way to reproduce this bug is executing the command while riding, which isn't that bad.

**Comment by xknat** [comment]
@MithrandirCraft are you using the dev build with the (#342) fix?

**Comment by MithrandirCraft** [comment]
Yeah I think this is fixed, else I'll reopen.
