### ISSUE TITLE
Limit SKINSGUI to page 999

### ISSUE THREAD

**Issue by Cyberyisus2g** [SkinsRestorer/SkinsRestorerX#333]
=DEV=
SKINSGUI page should be limited by 999 to avoid exceptions & attacks etc.

-----------

It's really easy, it took me a while to realize how my players were crashing my server, but finally I found the problem.

First, you need to use the command /skins

Then click "next page" A LOT.

That's it, the server crashes, I don't know if this happens in every server, but in mine does.

**Comment by xknat** [comment]
Do you know the amount of time it took to cause the crash? also is there an crash / javastack report?

**Comment by xknat** [comment]
@Cyberyisus2g any update on this?

**Comment by xknat** [comment]
Fixed by # 02d631ef
