### ISSUE TITLE
java.lang.NullPointerException: null whilist passing event FMLInitializationEvent to an Event Listener

### ISSUE THREAD

**Issue by alsoGAMER** [SkinsRestorer/SkinsRestorerX#334]
## Describe the bug
java.lang.NullPointerException: null whilist passing event FMLInitializationEvent to an Event Listener

## How can we reproduce what you got?
1. Download Forge 1.12.2-2838, Spongeforge 1.12.2-2838-7.3.0 and Skinsrestorer 13.8.4
2. Put the spongeforge and skinsrestorer jars into the mods folder
3. Start the forge server jar
4. Wait for sponge to load the plugin
5. See error

**Expected behavior**
Skinsrestorer would start without this exception

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.4
* SpongeForge version: 1.12.2-2838-7.3.0
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://hastebin.app/5f8efd46946001001d04ac2e

**Comment by xknat** [comment]
> Download Forge 1.12.2-2838
We don't give support for forge.
It works as it is and no support will be given.
