### ISSUE TITLE
SkinsRestorer breaks server resource pack prompting

### ISSUE THREAD

**Issue by amalon** [SkinsRestorer/SkinsRestorerX#335]
## Describe the bug
When SkinsRestorer is enabled, server resource packs do not get prompted to be enabled on the client when the player joins.
Sometimes the prompt is shown but only for a fraction of a second.
It works fine without SkinsRestorer or with DisableOnJoinSkins: true (shows prompt).
It works fine if the client has already enabled server resource packs for the server in question (no prompt, but resource pack loads).

## How can we reproduce what you got?
1. New papermc 1.16.3 server **with** SkinsRestorer
2. In server.properties, set resource-pack to URL of a resource pack ZIP, e.g.
```
resource-pack=https\://www.dropbox.com/s/th8ei3crc01bfx2/TrainCarts_Demo_TP_v3.zip?dl\=1
```
3. Start server
4. Add/edit server in vanilla 1.16.3 client, and ensure Server Resource Packs: **Prompt**
5. Join server

There is **no** prompt to download the resource pack
There is **no** downloading / reloading resource pack progress bar
Options -> Resource Packs shows **no** "World Specific Resources"

**Expected behavior**
This is what happens **without** SkinsRestorer installed, or with DisableOnJoinSkins: true in the SkinsRestorer config:
...
5. Join server
```
Prompt says "This server recommends the use of a custom resource pack.
Would you like to download and install it automagically?
```
6. Click Yes and the progress bar shows file downloading
7. Options -> Resource Packs shows "World Specific Resources"

To reset:
8. optionally clear ~/.minecraft/server-resource-packs, and edit server, change Server Resource Packs back to Prompt

When server resource packs is set to enabled, it works fine, the resource pack is downloaded and enabled without prompts

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

papermc on Arch Linux

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.4
* Papermc version: 1.16.3+b211-1
* Java: 8 ("System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.265-b01)")
* plugin list paper: none other than SkinsRestorer
* MinecraftLauncher?: The official one (minecraft-launcher AUR package)

## Logs
https://gist.github.com/amalon/73b75a30063945f15d92cec3f2cfeafb

**Comment by xknat** [comment]
@amalon work around i found:
Using https://www.spigotmc.org/resources/resource-pack-downloader.6262/ & ProtocolLib (devbuild)
have the users run /rp after login (can be done from authme)

**Comment by AlvarZ4** [comment]
I have exactly the same problem

**Comment by Ashesh3** [comment]
Having similar issues, SkinRestorer uses packet magic to toggle inventory or something which results in cancelling of the prompt or any other plugins which try to open inventory on player login (Ex. PinPrompt). Only when `DisableOnJoinSkins` is False. Any fixes?

**Comment by Th3Tr0LLeR** [comment]
I canfix the resource pack prompt, but not compatibility with other plugins

**Comment by xknat** [comment]
@Ashesh3 @AlvarZ4 @amalon 9c50ae2 should be sufficient, i know that there are some plugins that do handle resource pack prompt, and run a command when completed.
When using latest dev build with `DisableOnJoinSkins: true`
The resource pack plugin should run /sr applyskin %p where %p = player

Let me know if this resolved your issue!

**Comment by Bde13rian** [comment]
@xknat I was thinking if the problem was UserLogin plugin, but no. Then I read this and put the 'DisableOnJoinSkins' on true, and it works perfectly. Thanks bro.
