### ISSUE TITLE
Online-Mode server using cached skin instead of updated one.

### ISSUE THREAD

**Issue by ITZVGcGPmO** [SkinsRestorer/SkinsRestorerX#336]
New2PC#0001 (361685841732567054) in Voice Support VC @ discord states:

## Describe the bug
After a player updates their skin via mojang, the cached version of their skin is still shown. (skin not updated)
- Players do not have any permissions for skinsrestorer or /skin reload command.

## How can we reproduce what you got?
1. Join a bungeecord server with online authentication enabled and the plugin installed.
2. Apply a new skin to minecraft.net
3. Relog
4. Look at your old skin in shame.

**Expected behavior**
After applying skin to mojang, relogging should apply updated skin

**Comment by xknat** [comment]
option for players: /skin update (fixed in 8131fc37d2f4f685e81118b08c6deda79433c03e) so new release for that soon.
For server owners: skinsexpireafter: 0
