### ISSUE TITLE
Bungee with geyser not working

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#340]
floodgate is being used.

**Comment by Artoriun** [comment]
This issue was found on my Geyser-BungeeCord/Floodgate server network. I learned that the skin updates if I connect to a different server on my network using /server [server-name] after using the /set skin command. It doesn't update immediately when using the /set skin command though.

**Comment by xknat** [comment]
seems to be instaskin issue (skin refresher) & floodgate when using bungee.

**Comment by xknat** [comment]
Should be resolved with d29c2758b10e2a0c035230338821d4074e85ad1e & 0dbd235b477c7ca1dd88756c0aa807cfe473dd9e

**Comment by RidaThe94** [comment]
what about not having the original skin from geyser? can that be fixed?

**Comment by xknat** [comment]
That would be a feature request which i think is already requested
