### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by Darutan92** [SkinsRestorer/SkinsRestorerX#341]
Can you enter the display of skins on a Dynmap? The only plugin that supported this was [ChangeSkin](https://www.spigotmc.org/resources/changeskin.21469/), but it hasn't been updated for a long time.
![image](https://user-images.githubusercontent.com/60871654/98718429-de3d4500-23a7-11eb-9cc9-efee00198c26.png)
Now the skin is visible only to players with a license, the rest are Steve, although their skins have been changed.

**Comment by xknat** [comment]
I think that Dynmap already hooks into us.
would need to check.

**Comment by theconezone** [comment]
Dynmap is working fine on my offline mode server with SkinRestorerX, though occasionally a player head will revert back to steve.

**Comment by Darutan92** [comment]
I checked, yes, now the skins are visible on the Dinmap. My information was relevant for the spring of 2020, it looks like you have moved forward during this time.
