### ISSUE TITLE
/skins menu drag&drop

### ISSUE THREAD

**Issue by NyanGuyMF** [SkinsRestorer/SkinsRestorerX#349]
```
===========================================
= WARNING! Github is only for code issue. =
= For user support, go to our discord!    =
= http://skinsrestorer.net/discord        =
===========================================
```
## Describe the bug
I can drag&drop any item from /skins menu.

## How can we reproduce what you got?
1. Enter /skins command
2. Click on any item in menu
3. Drag and drop it into your inventory

**Expected behavior**
I think the plugin shouldn't allow players to take any item — head and glass in this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/43143315/101528344-045b0280-39b1-11eb-8488-f66795a64ad8.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.5.
* Spigot version: git-Paper-288 (MC: 1.16.4)
* Bungeecord version: no bungee
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 64-Bit Server VM 1.8.0_241
* plugin list bungee & spigot: Plugins (47): AuthMe, AuthMeTitle, AutoRestart*, AutoSaveWorld*, BanManager*, Chatty, Citizens, ClearLag, CoreProtect, DiscordSRV, DonateMessage*, EntityTrackerFixer, Essentials, EssentialsSpawn, FarmLimiter, Freeze*, GSit, HolographicDisplays, InventoryRollback, LeaderHeadsRevamped, LogBlock, Logger, LoginQuitMessage, LuckPerms, Matrix, MiniMOTD, NpcArmorTracker, OpenInv, PlaceholderAPI, PlugMan, PrizeParkour, ProtocolLib, ServerListPlus*, ServerUtils*, SetSpawn*, Shopkeepers, SkinsRestorer, TAB, Vault, VillagerOptimiser, VoidPointerFramework*, WeekReward, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldSpawn*
* MinecraftLauncher?: license, official launcher
* if multiverse, (censored) worlds file:

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
Spigot: https://hastebin.com/ibagamakiz.sql

**Comment by NyanGuyMF** [comment]
Looked through the code of SkinsGUI.java, guess the problem is related to Locale.SKINSMENU_TITLE_NEW.
I'll check it tomorrow with a debugger

**Comment by xknat** [comment]
Think it does not match it or something

**Comment by xknat** [comment]
https://github.com/SkinsRestorer/SkinsRestorerX/blob/bdd62c2c741cfca2e11000d4621a29379142e677/src/main/java/skinsrestorer/bukkit/SkinsGUI.java#L201

**Comment by xknat** [comment]
Think that should be OR instead of AND

**Comment by xknat** [comment]
fixed in 22011f3

**Comment by xknat** [comment]
8dac9b7

**Comment by xknat** [comment]
@NyanGuyMF think it should work now, please test and let me know :)

**Comment by NyanGuyMF** [comment]
Well, looks like I'm still able to move items
![image](https://user-images.githubusercontent.com/43143315/101676334-da6f1200-3a7c-11eb-8122-3cfd7d589398.png)

**Comment by xknat** [comment]
using latest dev build

**Comment by NyanGuyMF** [comment]
Yeah, I cloned and compiled

**Comment by NyanGuyMF** [comment]
Seems like the previous condition was right, debugging it right now

**Comment by NyanGuyMF** [comment]
Oh, I found the problem 😄
Going to pr
