### ISSUE TITLE
I Need 1.7.10 Support, Please Add It.

### ISSUE THREAD

**Issue by mtgsquad** [SkinsRestorer/SkinsRestorerX#353]
## How can we reproduce what you got?

**Expected behavior**

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.
* Spigot version:
* Bungeecord version: 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

**Comment by xknat** [comment]
Why be 1.17.10?

**Comment by Logics4** [comment]
SkinsRestorer has not supported 1.7.10 for a long time already (since around 2016?). Due to skin format differences between 1.7.x and 1.8+ this is not something in our priorities list nor something we actually want to support again.
