### ISSUE TITLE
Error WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Schmigy** [SkinsRestorer/SkinsRestorerX#355]
I expected clean server console - however it works without issues.

**Steps to reproduce the behavior**
1. Run server
2. Get warning during startup, but it doesnt show in logs
3. ???
4. Still works.

**Expected behavior**
Expected clean console. Get warning. Tried both offline and online mode.

**Screenshots**
![warning](https://user-images.githubusercontent.com/76057648/102237018-77560300-3ef4-11eb-87c5-9966a21566a2.png)

## Server information

Dell Optiplex 7010, SFF; used as a server only, accessed via remote desktop
Windows 7
Intel Core i5-3570
16GB DDR3

run.bat
@ECHO OFF
java -Xms8192M -jar paper.jar -nogui
del .console_history
@PAUSE

* SkinsRestorer: 13.8.6
* Paper version git-Paper-325 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
* System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.9.1+1) Host: Windows 7 6.1 (amd64)
* Plugins: all updated regularly
SkinsRestorer 13.8.6,
AngelChest 2.19.2,
Harbor 1.6.3,
PlaceholderAPI,
Universes 4.2.2 (without Spawnify stuff)
* No issues with launchers - using both Shiginima and official

## Logs
[latest.log](https://github.com/SkinsRestorer/SkinsRestorerX/files/5696922/latest.log)

## Additional context
My only suspicious is I'm using paper not spigot.

**Comment by Logics4** [comment]
This is normal if you're using a Java version that is higher than 8. There's nothing to worry about. The plugin will still work.

**Comment by Logics4** [comment]
I'm going to close this issue, but if you find a problem that comes from this, the issue can be reopened or a new one can be made.
