### ISSUE TITLE
acf-core.invalid_syntax locale can't be blank

### ISSUE THREAD

**Issue by Axer22** [SkinsRestorer/SkinsRestorerX#356]
## Describe the bug
"/skin set" command shows message two times.

## How can we reproduce what you got?
1. Install SkinsRestorer on Bungeecord server and connected Bukkit server.
2. Type "/skin set" command on Bukkit server.
3. See two messages.

**Expected behavior**
The first message should't be visible.

**Screenshots**
https://cdn.discordapp.com/attachments/186794372468178944/790931452246097920/unknown.png

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.6
* Spigot version: git-Paper-319
* Bungeecord version: git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:40370a3:388
* IF bungee, did you put the plugin on all servers: Yes
* Java: 14.0.2
* plugin list bungee & spigot: doesn't matter
* MinecraftLauncher?: lol
* if multiverse, (censored) worlds file: nope

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com/Axer22/c0d42726b02080180aed714246e09ec3
https://gist.github.com/Axer22/0847bfd36b3d725a99855fee3a22b604

## Additional context
*nothing*

**Comment by xknat** [comment]
`acf-core.invalid_syntax =` return empty line

**Comment by AfkF24** [comment]
Hi, any progress on this? Has been an issue for a while now. The same thing would apply for `/skin url` as well.

![Image](https://i.imgur.com/YVSHT6Q.png)

Setting `acf-core.invalid_syntax = ` (blank) disables both messages, which is rather annoying too.
Cheers

**Comment by xknat** [comment]
The first message is a indication in the command and hoe it should be performed.

This title can't be removed and also should not be removed afaik

**Comment by xknat** [comment]
@AfkF24 This should be fixed in https://github.com/SkinsRestorer/SkinsRestorerX/pull/496
![image](https://user-images.githubusercontent.com/10220139/116790837-d2108580-aab6-11eb-8ae4-c0de5ffaf53d.png)

**Comment by AfkF24** [comment]
@xknat Thanks! 👀
