### ISSUE TITLE
Dont work /skin set [nick]

### ISSUE THREAD

**Issue by ArkQuark** [SkinsRestorer/SkinsRestorerX#358]
## How can we reproduce what you got?
1. add plugin in server
2. add mods in server
3. /skin set ArkQuark
4. See error in console

**Expected behavior**
my skin must been changed
**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.5 (in any version work this bug)
* Spigot version: Magma on Bukkit 1.12.2-0.1-SNAPSHOT
* Bungeecord version: -
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot: Plugins (30): AntiAfkFishing, antiRedstoneClock, AuthMe, Brewery, ClearLag, CoreProtect, dynmap, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, Grand-Economy-Vault-Integration, MOTD, PermissionsEx, PexTabCompleter, PluginManager, ProtocolLib, PvPManager, ScoreBoard, SimpleSit, SkinsRestorer, TAB, Towny, TownyChat, TownyNameUpdater, Vault, WorldBorder, WorldEdit.
* MinecraftLauncher?: any
* if multiverse, (censored) worlds file: ?

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

## Additional context
https://pastebin.com/CQpbfaRg

**Comment by xknat** [comment]
We support forge as is

**Comment by Logics4** [comment]
Just to add to the previous comment:
- You might find a higher success of using SkinsRestorer in a Forge-based server if you don't use Forge mods that alter the player's skin in some way;

- Magma is a Forge+Bukkit hack. As the two platforms were never made to work with each other, all sorts of issues can happen. If you want to use plugins in a Forge server, you should be using SpongeForge instead ~~(we still won't be offering official support for it but from personal experience the plugin has been working just fine up to now)~~.
