### ISSUE TITLE
Bungee MySQL Error

### ISSUE THREAD

**Issue by LucidAPs** [SkinsRestorer/SkinsRestorerX#359]
Waterfall #389
Java 8
SkinsRestorer #236
Backend Servers: Tuinity 1.16.4 #177 , ViaVersion 3.2.2 #493 , SkinsRestorer #236
https://mcpaste.io/c8c102bd6b456e5f

**Comment by Logics4** [comment]
Are you sure this is an issue with the plugin's code? Did you make a brand new database or this happened in an existing one? Are you able to fix it by manually editing the database to remove the duplicate entry? This probably should've gone through our support discord server first.

**Comment by xknat** [comment]
Fixed in v14 by 4b2c5bd1a23f2a2cf6e2e13166f99b22b663ac9c
