### ISSUE TITLE
Self Skin not working with generator uuid Character system.

### ISSUE THREAD

**Issue by chocolatecraft** [SkinsRestorer/SkinsRestorerX#360]
I used this plugin. skin wont show on self client but other player saw it normally.

https://www.spigotmc.org/resources/character-slots-user-profiles.76289/

Can you fix this. Or problem from client. Thank you.

**Comment by chocolatecraft** [comment]
https://i.ibb.co/fQ3fvfV/skin.png

but other player saw my skin. I didnt see my skin.

**Comment by xknat** [comment]
@chocolatecraft github is for issues related to code or confirmed bugs.
If you want support, join our discord. But if you still feel like this is a coding issue, then please fill in our bug report:
https://raw.githubusercontent.com/SkinsRestorer/SkinsRestorerX/master/.github/ISSUE_TEMPLATE/bug-report.md
