### ISSUE TITLE
Skin menu GUI can't be detected correctly if the title contains acii special chars

### ISSUE THREAD

**Issue by pianwan** [SkinsRestorer/SkinsRestorerX#361]
## Describe the bug
Skin menu GUI can't be detected correctly if the title contains something.
## How can we reproduce what you got?
1. Go to 'messages.yml'
2. Set SKINSMENU_TITLE_NEW to '&d➤ &1&lSkin Change &7[&9/skins&7] (&9%page&7)'
3. /sr reload
4. /skins 
5. The GUI is broken and the items inside canbe take out.

**Expected behavior**
GUI is detected correctly and works well.
**Screenshots**
none
## Server information
none
**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Spigot
**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.6
* Spigot version: 1.16.4
* Bungeecord version:  none
* IF bungee, did you put the plugin on all servers: none
* Java: 11
* plugin list bungee & spigot: not needed
* MinecraftLauncher?: vanilla
* if multiverse, (censored) worlds file: not needed

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
not needed

## Additional context
none

**Comment by xknat** [comment]
Possible fix: https://github.com/SkinsRestorer/SkinsRestorerX/commit/daa38030a240d2462b2a51ca71da73f0a2b253e2#r45123382

**Comment by kn-km** [comment]
> Possible fix from comment on: [daa3803#r45123382](https://github.com/SkinsRestorer/SkinsRestorerX/commit/daa38030a240d2462b2a51ca71da73f0a2b253e2#r45123382)

I tried the latest dev build, still not work.

**Comment by xknat** [comment]
> I tried the latest dev build, still not work.

i know, see it as a personal note.

**Comment by xknat** [comment]
resolved by 74c6f667955e2a6eb95b3456eb538441f93315ff
