### ISSUE TITLE
Illegal reflective access warning when using java 9+

### ISSUE THREAD

**Issue by PappoYT** [SkinsRestorer/SkinsRestorerX#362]
== DEV ==
* [x] added warning
* [ ] fixed issue (TODO)

== Original ==
I get this error during startup of the server:

> 08.01 16:31:38 [Server] INFO Enabling SkinsRestorer v13.8.6
> 08.01 16:31:38 [Server] INFO WARNING: An illegal reflective access operation has occurred
> 08.01 16:31:38 [Server] INFO WARNING: Illegal reflective access by skinsrestorer.bukkit.skinfactory.PaperSkinRefresher (file:/plugins/SkinsRestorer-13.8.6.jar) to field java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP
> 08.01 16:31:38 [Server] INFO WARNING: Please consider reporting this to the maintainers of skinsrestorer.bukkit.skinfactory.PaperSkinRefresher
> 08.01 16:31:38 [Server] INFO WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> 08.01 16:31:38 [Server] INFO WARNING: All illegal access operations will be denied in a future release

This server is running Paper version git-Paper-311 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Server log: [https://pastebin.com/TrKHxpT3](https://pastebin.com/TrKHxpT3)

**Comment by Logics4** [comment]
This is normal if you use Java 11. The plugin will work fine.

**Comment by xknat** [comment]
Pushed e292e53ef845de2b34471eb49c1c0a0f5cfc6d0e in a effort to reduce spam regarding this in support.
This is lower priority issue.

**Comment by xknat** [comment]
should be resolved now, thanks
