### ISSUE TITLE
BungeeCord update configuration isn't working on Spigot sub servers

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [SkinsRestorer/SkinsRestorerX#371]
Server Information:
Newest BungeeCord and paper
All paper servers and bungeecord server are using the newest release of SkinsRestorer

Bug:
I set update to false on BungeeCord but my spigot servers are still downloading the newest release

**Comment by xknat** [comment]
Updates are mandatory for now.
We will add a feature to delay updates. please see #298
