### ISSUE TITLE
velocity Premium player with that name does not exist

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#376]
debug false:
![image](https://user-images.githubusercontent.com/10220139/105892999-d2f6ce80-6012-11eb-8209-414b7cd4cf49.png)
`Hey, it is possible to remove this exception message in console? I get it every time when non-premium player join my server. I'm using Velocity, on Bungeecord I do not have that issue. If I set a blank text in messages.yml at "NOT_PREMIUM" it will show that exception anyway. (Latest version of SR and Velocity)`

**Comment by Logics4** [comment]
I fixed this issue a while ago in Sponge. Find the commit and see what I did

**Comment by Logics4** [comment]
dc4ad8596f82784dae70b8ca1b8813c657f7fb75
