### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by mirikyoutube** [SkinsRestorer/SkinsRestorerX#381]
00:36:26 [SEVERE] java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
00:36:26 [SEVERE]     at skinsrestorer.bungee.listeners.LoginListener$2.applySkin(LoginListener.java:71)
00:36:26 [SEVERE]     at skinsrestorer.shared.format.SkinProfile.applySkin(SkinProfile.java:80)
00:36:26 [SEVERE]     at skinsrestorer.bungee.listeners.LoginListener.onPostLogin(LoginListener.java:63)
00:36:26 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:36:26 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
00:36:26 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
00:36:26 [SEVERE]     at java.lang.reflect.Method.invoke(Unknown Source)
00:36:26 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
00:36:26 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
00:36:26 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
00:36:26 [SEVERE]     at net.md_5.bungee.connection.InitialHandler.finnalyFinishLogin(InitialHandler.java:585)
00:36:26 [SEVERE]     at net.md_5.bungee.connection.InitialHandler.access$1100(InitialHandler.java:75)
00:36:26 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$6.lambda$done$0(InitialHandler.java:570)
00:36:26 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
00:36:26 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
00:36:26 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
00:36:26 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
00:36:26 [SEVERE]     at java.lang.Thread.run(Unknown Source)

**Comment by xknat** [comment]
@mirikyoutube what is your /sr status

**Comment by xknat** [comment]
And also, what is your bungee version

**Comment by mirikyoutube** [comment]
i am using BungeCord BotFilter 1.8.x-1.13.x by vk.com/Leymooo_s

**Comment by mirikyoutube** [comment]
> @mirikyoutube what is your /sr status

command not found

**Comment by xknat** [comment]
Can you check what version of SR is loading?

**Comment by mirikyoutube** [comment]
> Can you check what version of SR is loading?

23:13:58 [INFO] [SkinsRestorer]     You are running v10.4.2

**Comment by xknat** [comment]
??????????????????????????????????????

**Comment by mirikyoutube** [comment]
skinrestorer ver 10.4.2

**Comment by xknat** [comment]
10.4.2 is around 2015 (launch date of windows 10)
you should update lol
