### ISSUE TITLE
Player can't join the server

### ISSUE THREAD

**Issue by MAX-XiaoKui** [SkinsRestorer/SkinsRestorerX#383]
## Describe the bug
Player can't join the server(BungeeCord).

**Screenshots**
![image](https://user-images.githubusercontent.com/53287753/106365513-1f267380-6371-11eb-85e4-7c3db6113c16.png)

## Server information

BungeeCord

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.8 & 13.8.7
* Bungeecord version: build 1543
* IF bungee, did you put the plugin on all servers: No (My servers are fabric servers)
* Java: 8
* plugin list bungee & spigot: SkinsRestorer
* MinecraftLauncher?:HMCL

## Logs
https://hastebin.app/6015ae97edaf44001c838fac

## Additional context
It works well 4 days ago.

**Comment by Logics4** [comment]
Your BungeeCord is two versions behind, and one of them seems to update the network library so try updating your BungeeCord version.

Additionally, we don't test the plugin when it's only installed in the proxy. When the server uses BungeeCord, the plugin is expected to be installed in both the proxy and the backend servers, and we don't offer support for Fabric servers. If it worked flawlessly until 4 days ago then that's probably a miracle.

**Comment by xknat** [comment]
"It works well 4 days ago." with or without skinsrestorer?

**Comment by MAX-XiaoKui** [comment]
> "It works well 4 days ago." with or without skinsrestorer?

with

**Comment by MAX-XiaoKui** [comment]
> ‎您的 BungeeCord 是两个版本，其中一个似乎更新了网络库，因此请尝试更新您的 BungeeCord 版本。‎
> 
> ‎此外，当插件仅安装在代理中时，我们不会测试它。当服务器使用 BungeeCord 时，该插件预计将同时安装在代理服务器和后端服务器中，并且我们不为 Fabric 服务器提供支持。如果它工作完美无瑕， 直到 4 天前， 那么这可能是一个奇迹。‎

I tried BungeeCord build 1545, and the error still occurs.

**Comment by xknat** [comment]
@MAX-XiaoKui can you check if working on 13.8.6

**Comment by MAX-XiaoKui** [comment]
> @MAX-XiaoKui can you check if working on 13.8.6

No, it doesn't work.

**Comment by xknat** [comment]
then i stand behind Logics comment
