### ISSUE TITLE
OnJoinSkins task is slowing things down

### ISSUE THREAD

**Issue by Dum4G** [SkinsRestorer/SkinsRestorerX#384]
## Describe the bug
When the DisableOnJoinSkins is set to false my server literally hangs out for a few seconds during each login attempt and then reports TPS drops. As soon as I disable that feature authentification process gets faster.
My evidence is https://timings.spigotmc.org/?url=dulivujomi

**Expected behavior**
OnJoinSkins won't cause deadlocks

## Server information

**I'm running Arclight**

* SkinsRestorer: 13.8.8
* Arclight version: 1.16.5-1.0.12-SNAPSHOT-1c0136c
* Java: 8
* plugin list: LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl
* MinecraftLauncher?: TLauncher

## Logs
https://gist.github.com/Dum4G/e09d7caddb0fe7a95b8d9419ca99a03c

## Additional context
Arclight is a server that is compatible with Spigot and Forge APIs simultaneously

**Comment by xknat** [comment]
Could be an Arclight thing. would need to check.
Maybe they dont support async

**Comment by Logics4** [comment]
As you said, Arclight is a Forge+Bukkit server, which we don't offer official support for.

Anyway, how about you try to install SpongeForge in it and put SkinsRestorer as a Sponge plugin? Maybe it works... maybe it won't. ¯\_(ツ)_/¯
