### ISSUE TITLE
Custom skins issues

### ISSUE THREAD

**Issue by PrzemoVi** [SkinsRestorer/SkinsRestorerX#385]
So 4 years ago I have written a Java program that was setting skins players wanted to my Premium account, extracting Value, Signature from it, injecting it into SkinsRestorer database as CUSTOM_randomchars skin, and setting that skin for player. 
Then the program was executing rcon command "skin update {NICK}".
And it worked perfectly fine, until now.

When I type "skin update {NICK}" I'm getting "Error: Skin can't be updated because of its custom.".
Why custom skin cannot be updated? Just instead of re-extracking player val&sig it should just reload info from db.
Because of this palyers have to rejoin server for skin to update.

So I wanted to implement this new "skin set <URL>" command and delete my boilerplate, but I'm getting:
"ERROR: Invalid or not allowed URL or format. Reminder that we only accept image uploaders which have been allowed by the server owner! See skinsrestorer.net/skinurl for more info."

It's telling me that "the server owner is capable of changing the skin URL whitelist", but there is no such option in the config.

So could someone:
1. Allow updating of custom skins
2. Expose wkin whitelist to the config

I wanted to workaround this by hooking into SkinsRestorer API, but i don't want to write another plugin with another ServerSocket...

Sorry for my eng, im not Native.
Thanks for your time.

**Comment by xknat** [comment]
> Why custom skin cannot be updated?
Custom skins are not bound by mojang username.
Since the skin is not a username bound mojang name. there is no source we can update the skin from.
Thus the skin can't be updates.
You should apply skin and not skin update if you wish to apply a skin from api

>So could someone:
> Allow updating of custom skins
we won't because i think your misunderstanding skin update for this reason.

> Expose wkin whitelist to the config
We have no "wkin" nor "whitelist" 

I think this is not a coding issue, only coding issues should be reported to github.
if you want support, please join our discord (advertised on many places)

Also, Please check our current issues while your at it, so you know that we are working on it.

**Comment by PrzemoVi** [comment]
I mean SKIN URL WHITELIST coz SR is telling me that im the one that should be able to add/remove image uploaders, but I'm not.

**Comment by PrzemoVi** [comment]
And about update - I know how Mojang api works and "update" command should UPDATE skin for example, after changing data in the database, and If skin is NOT CUSTOM it should UPDATE database and then UPDATE skin as it was in the older versions.

**Comment by xknat** [comment]
> I mean CUSTOM SKIN URL WHITELIST coz SR is telling me that im the one that should be able to add/remove image uploaders, but I'm not.

@PrzemoVi Did you read out latest update release notes?

> UPDATE skin for example

You mean "applyskin" which is not yet a command but a api.
Update skin will try and update the skin, but if it cant update. it wont put in resources and lagg to again apply the same skin.

**Comment by xknat** [comment]
but yet again, this is not a coding issue -> join discord or dm us on spigotmc
