### ISSUE TITLE
V14 MySQL Error

### ISSUE THREAD

**Issue by LucidAPs** [SkinsRestorer/SkinsRestorerX#386]
When using the latest dev versions from Jenkins I am getting these errors and the plugin doesn't work. However the latest version from the spigot page works just fine.

Console Error
https://nekobin.com/liqasucoti

**Comment by xknat** [comment]
@LucidAPs [08:57:04 INFO]: [SkinsRestorer] MySQL.ConnectionOptions is missing in config.yml! Using default value.

**Comment by xknat** [comment]
try to update config,yml

**Comment by LucidAPs** [comment]
I generated a new config and it works with the default values but if I enable mysql there is the same problem.

**Comment by xknat** [comment]
@LucidAPs can you try 13.8.8

**Comment by LucidAPs** [comment]
> @LucidAPs can you try 13.8.8

I tried the build #255 and it had the same error.

**Comment by xknat** [comment]
> > @LucidAPs can you try 13.8.8
> 
> I tried the build #255 and it had the same error.
@LucidAPs i know, i want you to try a stable release like https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest

**Comment by xknat** [comment]
https://hastebin.app/602e40961bef4c001c12e1b4
