### ISSUE TITLE
SkinsRestorer

### ISSUE THREAD

**Issue by uRyanxD** [SkinsRestorer/SkinsRestorerX#388]
## How can we reproduce what you got?
1. Download & put in the server
2. Start the server

**Screenshots**
https://prnt.sc/y6xadc

## Server information

**On what platform does your server run? (Spigot)

* SkinsRestorer: RELEASE
* Spigot version: 1.8
* Java: 8
* MinecraftLauncher?: Mojang

**Comment by xknat** [comment]
-> https://discord.me/skinsrestorer
