### ISSUE TITLE
Can't change skin without Imgur, even with AllowedUrls correctly set

### ISSUE THREAD

**Issue by HerrCraziDev** [SkinsRestorer/SkinsRestorerX#399]
## Description
Using `/skin set <player> <url>` or `/skin set <url>` fails to set the skin and asks for the use of Imgur.com, even though I have configured the `AllowedUrls` setting in `config.yml` to accept our domain. We're running the latest version of SkinRestorer on Paper 1.16.4. We used to use a file server on our local network to host the skins, and the file server works perfectly (both through HTTP and HTTPS). I personally dislike Imgur, and prefer relying on as little external dependencies as possible for the services I administrate, henceforth this issue is to us rather annoying. Forcing people to use Imgur is a terrible move. 

Using our own file server, everything could be managed from the command line and via scripts, which is no longer possible since SR is now locked behind Imgur. 

## Steps to reproduce

- Have a simple HTTP server running on your local network, serving a few skins, with a domain name pointing to the server (eg: files.myserver.com) 
- Log on the Minecraft server (as a regular player, an admin, an OP, it does not matters)
- Issue the `/skin set http://files.<myserver.com>/<myskin>.png` command, replacing the placeholders with their actual names
- SR will complain about you not using Imgur and won't let you change the skin unless you upload it to Imgur.

We would greatly appreciate if the former behaviour of not enforcing the use of Imgur could be restored.
Thanks for your time and attention.

F.E.

**Comment by xknat** [comment]
@HerrCraziDev the skin also must be a valid skin, can you send the image as example?

**Comment by xknat** [comment]
> We would greatly appreciate if the former behaviour of not enforcing the use of Imgur could be restored.

Its already replaced in v14 (devbuilds)

**Comment by HerrCraziDev** [comment]
> @HerrCraziDev the skin also must be a valid skin, can you send the image as example?

Sorry for the long waiting time. The skin are perfectly valid (I use it on another server and as my main Minecraft skin with no issues). 
[Here on NameMC](https://fr.namemc.com/skin/b0a10cae17e91392) | [Personal (auxiliary) fileserver](http://files.herrcrazi.tk/thorfinn.png)
![thorfinn.png](http://files.herrcrazi.tk/thorfinn.png)

**Comment by xknat** [comment]
@HerrCraziDev did you add `http://files.herrcrazi.tk/` to the allow list of the new config option in 13.8.8 as shown below:

https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/resources/config.yml#L118-L121

If this is not present, please add the following to your config and add your domain: (as shown below)
```yaml
RestrictSkinUrls:
  Enabled: false
  List:
  - http://files.herrcrazi.tk
```

**Comment by xknat** [comment]
@HerrCraziDev issue closed?

**Comment by HerrCraziDev** [comment]
Sorry for the delay, we had an issue with the server. I have been able to restore it and apply the changes you indicated. Everything works ! 

Thanks for your help ! ;)
