### ISSUE TITLE
older bungee versions throw error on getdatafolder

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#424]
confirmed issue on https://ci.md-5.net/job/BungeeCord/1036/
Issue is present on 13.8.8

**Comment by Logics4** [comment]
The build number 1036 of BungeeCord was released in June 2015. It only has support for 1.7.10 and 1.8 backend servers. There's no reason why we should even be minding it when the latest builds support 1.8 to 1.16.5 and people who still need 1.7 for whatever reason can use Travertine. No one should still be running builds from 2015.

**Comment by AlexProgrammerDE** [comment]
There is 0 reason to use a bugged old bungeecord version. We don't support 1.7.10 either way so why bother having support for an old version that didn't drop 1.7.10 already. As this is kinda a bugged official API by bungeecord it shouldn't be our problem. Everyone interested in fixing this just has to update his bungeecord. (which has 0 downturns) Well, imma close this issue now.
