### ISSUE TITLE
[Suggestion] Use links as default skins.

### ISSUE THREAD

**Issue by Marcelektro** [SkinsRestorer/SkinsRestorerX#444]
Hello,
I'd like to suggest ability of adding URL skins as default players.
That could give us ability to design skins for the non players (non premium without skin) making the server look nicer!
It seems very easy to do myself, but I thought about suggesting it there so others would also be able to do it!
Regards
Marcelektro

**Comment by xknat** [comment]
Can already be done for spigot.
For bungee, create a custom skin and set the 3rd line to 0. (if using v14)
