### ISSUE TITLE
NOT WORKING ON 1.16.5

### ISSUE THREAD

**Issue by uRyanxD** [SkinsRestorer/SkinsRestorerX#451]
## Describe the bug
Dont' loading the plugin.

## How can we reproduce what you got?
1. Start server

## Server information

**On what platform does your server run? Paper

**What version? Do NOT answer LATEST**
* SkinsRestorer: Build #310 (Fri Mar 19 09:58:22 UTC 2021)
* Spigot version: 1.16.5
* Java: 11
* plugin list  spigot: SkinsRestorer only
* MinecraftLauncher?: Original

## Logs
https://hastebin.app/6054f27a0f36b5001ca0d39a

**Comment by xknat** [comment]
@uRyanxD Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
jar seems to be corrupt. Please download again from releases here https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest
