### ISSUE TITLE
Feature request: Different skins for different players

### ISSUE THREAD

**Issue by Farbmond** [SkinsRestorer/SkinsRestorerX#466]
Hi!

It would be fine, there is an option, so that every player have its own skin-set in gui (and not: every player see all available skins).
(Sorry, English is not my first language.)

I asked this on Discord and was asked to post here.

**Comment by xknat** [comment]
You would need to build a custom gui for this.

**Comment by xknat** [comment]
We do plan on #1047 & #1261
