### ISSUE TITLE
v14.0.2 on Velocity can't connect to MySQL

### ISSUE THREAD

**Issue by Lerbiq** [SkinsRestorer/SkinsRestorerX#483]
## Describe the bug
I recently started encountering issue with SkinsRestorer on 14.0.2 version running on Velocity. The plugin can't connect to the mysql database. The error message is just `Can't connect to MySQL! Disabling SkinsRestorer`.
After downgrading to 13.8.8 the plugin connects to the database without any issues and works as expected.
## How can we reproduce what you got?
1. Make a Velocity proxy server (v1.1.4, not sure if this matters).
2. Install SkinsRestorer 14.0.2
3. Configure it to connect to a mysql database and restart.
4. The error should pop up and plugin should disable itself.

**Expected behavior**
The plugin boots up like normal and works without any issues.

## Server information

Velocity 1.1.4

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.0.2
* Paper version: 1.8.8 (Shouldn't matter since the issue is on the proxy)
* Velocity version: 1.1.4
* IF Velocity, did you put the plugin on all servers: Yes
* Java: 15
* plugin list bungee & paper: 
Velocity: 
BotSentry (8.8.1), LuckPerms (5.2.90), Nuvotifier (2.7.2), SkinsRestorer (14.0.2), TCPShield (2.4)
Spigot:
Mapcha, PlugMan, SkinsRestorer, ViaVersion, ProtocolLib, LuckPerms, AuthMe

* MinecraftLauncher?: Any

## Logs
Replace the links below by a paste of your startup logs
Velocity:
https://pastebin.com/STudW5dD
Paper:
https://pastebin.com/SEP1xmL1

**Comment by xknat** [comment]
Will be handled on discord
