### ISSUE TITLE
Feature request: add config entry to set BungeeCord mode manually

### ISSUE THREAD

**Issue by nicknickeryt** [SkinsRestorer/SkinsRestorerX#494]
SkinsRestorer detects if a BungeeCord is used. For Spigot it is done by checking `settings.bungeecord: true`.

However, I want to force SkinsRestorer to use BungeeCord mode because my `settings.bungeecord` is set to `false`. The purpose of doing it that (unsafe) way is to change `If you wish to use IP forwarding...` BungeeCord message to a custom message using additional plugin so that I don't have to recompile server jar to change that message. However, I have to set `settings.bungeecord` to `false` which partially breaks SkinsRestorer and forces players to re-log to see their updated skin after they change it.

The idea is simple: add a config entry to SkinsRestorer `config.yml` which would overwrite BungeeCord mode checks.

**Comment by xknat** [comment]
This is done by override files.
Config is NOT loaded for backend.
see bukkit/skinsrestorer.java for the list
