### ISSUE TITLE
/skin clear does not work on bedrock players with * prefix

### ISSUE THREAD

**Issue by bejoeled** [SkinsRestorer/SkinsRestorerX#497]
We have GeyserMC in our server and we're using * as prefix. /skin clear does not work on players with * and shows error "Error: *PlayerName is not a valid username or url".
![image](https://user-images.githubusercontent.com/10220139/116813805-fc655000-ab55-11eb-9551-d13d1651c262.png)

**Comment by AlexProgrammerDE** [comment]
Fixed by v15
