### ISSUE TITLE
SkinsRestorer incompatible with latest ViaVersion dev builds

### ISSUE THREAD

**Issue by x9nico** [SkinsRestorer/SkinsRestorerX#504]
## Describe the bug

Error when Player join with ViaVersion v4.0.0 (dev build).

## How can we reproduce what you got?
1. Use latest dev build of ViaVersion (4.x)
2. Start your server
3. Join your server

**Screenshots**

N/A

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)** Paper 1.16.5

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.0.2
* Spigot version: Paper 1.16.5
* Bungeecord version: I'm not on Bungee.
* IF bungee, did you put the plugin on all servers: Yes / No: I'm not on Bungee.
* Java: 16.0.1+9-24
* plugin list bungee & spigot: AuthMe, ClearLag, FastAsyncWorldEdit (WorldEdit), FastLogin, OldCombatMechanics, ProtocolLib, ProtocolSupport, PvPBox (a custom plugin created by me), SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, WorldGuard
* MinecraftLauncher?: Official from Mojang
* if multiverse, (censored) worlds file: N/A

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)

https://hastebin.app/609ffc8a706e45001dfb0237

## Additional context

N/A

**Comment by xknat** [comment]
@x9nico are you using the dev build of viaversion?

**Comment by xknat** [comment]
> Use latest dev build of ViaVersion (4.x)
We dont support their dev build.

**Comment by x9nico** [comment]
Before the latest builds works with ViaVersion.
I must use the dev builds to run ViaVersion with Java 16.

**Comment by xknat** [comment]
ask them to release it faster.

**Comment by x9nico** [comment]
> ask them to release it faster.

I think it will be released when 1.17 will be released.

**Comment by x9nico** [comment]
> > Use latest dev build of ViaVersion (4.x)
> 
> We dont support their dev build.

Hello, the 4.0.0 of ViaVersion has been released. Can you do an update to fix the error please ?

**Comment by x9nico** [comment]
> Hey there!
> Thank you for letting us know.

Thanks for your fast answer. I hope that the fix will be released fast :)
