### ISSUE TITLE
Velocity 3.0.0 Support

### ISSUE THREAD

**Issue by 4drian3d** [SkinsRestorer/SkinsRestorerX#511]
## Describe the bug
SkinsRestorer is not compatible with Velocity 3.0.0, which is a successor version of Velocity 1.1.x with few changes that may break compatibility.
In this case, due to https://github.com/VelocityPowered/Velocity/commit/977300cc66af91cdf88bff38f487a8e3207e33d7 it breaks compatibility, as it removes apis that were deprecated a long time ago.

## How can we reproduce what you got?
1. Setting up a Velocity 3.0.0 proxy https://velocitypowered.com/downloads/
2. Installing SkinsRestorer as the only plugin
3. It will throw an error in console and the proxy will not finish starting. 

**Expected behavior**
That the plugin works correctly in Velocity 3.0.0 as the change being made that breaks its compatibility is minor and affecting:
https://github.com/SkinsRestorer/SkinsRestorerX/blob/c3dabd28761d0f2e21e7d5ec94f514bf0ae743d6/src/main/java/net/skinsrestorer/velocity/command/SkinCommand.java
https://github.com/SkinsRestorer/SkinsRestorerX/blob/c3dabd28761d0f2e21e7d5ec94f514bf0ae743d6/src/main/java/net/skinsrestorer/velocity/command/SrCommand.java
https://github.com/SkinsRestorer/SkinsRestorerX/blob/c3dabd28761d0f2e21e7d5ec94f514bf0ae743d6/src/main/java/net/skinsrestorer/velocity/SkinsRestorer.java

## Server information

**On what platform does your server run? (Bungeecord/Velocity/Spigot/Bukkit)**
Velocity 3.0.0
**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.1.1
* Velocity version: 3.0.0
* IF bungee/velocity, did you put the plugin on all servers: No
* Java: 11.0.10
* plugin list velocity: SkinsRestorer

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord/Velocity** server, please send startup logs from **Bungeecord/Velocity *AND* Spigot/Bukkit**)
https://pastebin.com/AWHyb6Ds *reproducible bug without the need for a backend server*

## Additional context
- Velocity 3.0.0 has just been released a few hours ago and is the main version as of now.

**Comment by xknat** [comment]
Planned, we will wait till it comes out officially

**Comment by 4drian3d** [comment]
Velocity 3.0.0 has just been released a few hours ago. https://forums.velocitypowered.com/t/velocity-3-0-0-and-1-1-9-released/821

**Comment by xknat** [comment]
We know thanks https://github.com/SkinsRestorer/SkinsRestorerX/pull/581

**Comment by AlexProgrammerDE** [comment]
Will be included in next update.
