### ISSUE TITLE
Replace Java 11 with Java 16!

### ISSUE THREAD

**Issue by uRyanxD** [SkinsRestorer/SkinsRestorerX#512]
With new dependence on Java 16+ as of Minecraft 1.17 

https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

**Comment by xknat** [comment]
@uRyanxD did you even test it working?
Please do not create issues if there are no confirmed issues as this issue is based on the assumption that its not gonna work.

**Comment by Logics4** [comment]
Just to add upon this: Newer versions of Java are able to run older version's code with (mostly) no problems.

The only potential problems we could face are with certain types of reflection (like changing `final` fields) that got forbidden in Java 16. I don't recall us doing any of that, though?

Either way, please come back with a console log when you find any issues.
