### ISSUE TITLE
ViaVersion 4.0.0 support

### ISSUE THREAD

**Issue by x9nico** [SkinsRestorer/SkinsRestorerX#515]
Describe the bug

Error when Player join with ViaVersion v4.0.0.

How can we reproduce what you got?

Use latest build of ViaVersion (4.x)
Start your server
Join your server
See error
Screenshots

N/A

Server information
On what platform does your server run? (Bungeecord/Spigot/Bukkit) Paper 1.16.5

What version? Do NOT answer LATEST

SkinsRestorer: 14.0.2
Spigot version: Paper 1.16.5
Bungeecord version: I'm not on Bungee.
IF bungee, did you put the plugin on all servers: Yes / No: I'm not on Bungee.
Java: 16.0.1+9-24
plugin list bungee & spigot: AuthMe, ClearLag, FastAsyncWorldEdit (WorldEdit), FastLogin, OldCombatMechanics, ProtocolLib, ProtocolSupport, PvPBox (a custom plugin created by me), SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, WorldGuard
MinecraftLauncher?: Official from Mojang
if multiverse, (censored) worlds file: N/A
Logs
Replace the links below by a paste of your startup logs (if you run a Bungeecord server, please send startup logs from Bungeecord AND Spigot/Bukkit)

https://hastebin.app/609ffc8a706e45001dfb0237

Additional context

N/A

**Comment by xknat** [comment]
There was no need to close the past ticket and create a new one.
i work ascending on date.

**Comment by xknat** [comment]
#517 should resolve this issue, you can download this dev build from https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

**Comment by x9nico** [comment]
> #517 should resolve this issue, you can download this dev build from https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar

It works. Thanks !
