### ISSUE TITLE
Not working on Spigot 1.17

### ISSUE THREAD

**Issue by matteoturini** [SkinsRestorer/SkinsRestorerX#524]
## Describe the bug
Error on the console

## How can we reproduce what you got?
Use SkinsRestorer on Spigot 1.17.

**Expected behavior**
It works.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.0.2
* Spigot version: 1.17 R-0.1
* Bungeecord version: N/A
* IF bungee, did you put the plugin on all servers: N/A
* Java: 16
* plugin list bungee & spigot: SkinsRestorer, NoItemFrameBreaking (second one is just an event listener on HangingItemBreak that always cancels)
* MinecraftLauncher?: N/A
* if multiverse, (censored) worlds file: N/A

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://hastebin.app/60c3799f706e45001dfb025b

**Comment by AlexProgrammerDE** [comment]
We are aware of the issue and are gonna  look into it soon. Spigot 1.17 just released and we have to check and test everything first. Imma pin this issue.

**Comment by xknat** [comment]
cosed by https://github.com/SkinsRestorer/SkinsRestorerX/pull/530
