### ISSUE TITLE
How to get SkinStorage in bungeecord

### ISSUE THREAD

**Issue by hank9999** [SkinsRestorer/SkinsRestorerX#534]
Hi, I am developing a plugin to set skin from skin website via SkinsRestorer  
But I have some trouble getting SkinStorage API  

In old version, i do this
```java
SkinsRestorer skinsRestorer = SkinsRestorer.getInstance();
SkinStorage skinStorage = skinsRestorer.getSkinStorage();
```
But now I can find any way to get it.
Is there a way to get it?
Thanks a lot.

**Comment by AlexProgrammerDE** [comment]
SkinStorage was never intended to be used by devs. Please use our API instead: https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/net/skinsrestorer/api/SkinsRestorerAPI.java
It wraps around the most important parts of what SkinStorage can do.

**Comment by hank9999** [comment]
> SkinStorage was never intended to be used by devs. Please use our API instead: https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/net/skinsrestorer/api/SkinsRestorerAPI.java
> It wraps around the most important parts of what SkinStorage can do.

So, is there any way to use MineSkinApi returned skin data in bungeecord?
Thanks a lot.

**Comment by xknat** [comment]
> > SkinStorage was never intended to be used by devs. Please use our API instead: https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/net/skinsrestorer/api/SkinsRestorerAPI.java
> > It wraps around the most important parts of what SkinStorage can do.
> 
> So, is there any way to use MineSkinApi returned skin data in bungeecord?
> Thanks a lot.

Currently not, but it's planned.
We added a MineskinAPIKey feature in #533 which could allow us to open API without being at risk of abusing the API.

**Comment by hank9999** [comment]
Ok, thanks.
