### ISSUE TITLE
[Bug] [Spigot 1.17] Error when Player join

### ISSUE THREAD

**Issue by x9nico** [SkinsRestorer/SkinsRestorerX#544]
## Describe the bug

Hello, when a Player join the server, it does error in logs.

## How can we reproduce what you got?
1. Set the plugin on your server
2. Start your server
3. Join your server
4. See your logs (you can see the errors in the pastebin link)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.1.0-SNAPSHOT
* Spigot version: 1.17
* Bungeecord version:  N/A
* IF bungee, did you put the plugin on all servers: No
* Java: 16
* plugin list bungee & spigot: AuthMe, ClearLag, FastLogin, OldCombatMechanics, ProtocolLib, ProtocolSupport, PvPBox (a custom plugin created by me), SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, WorldGuard
* MinecraftLauncher?: Official from Mojang
* if multiverse, (censored) worlds file: N/A

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)

https://pastebin.com/aTswjGq7

**Comment by xknat** [comment]
@x9nico Hey there!
Thank you for taking your time, could you tell us what your build number is and also test it on build number 51d72a315deeeec313887e24c530daa466326afe with the jar https://github.com/SkinsRestorer/SkinsRestorerX/suites/3031387861/artifacts/68766377

**Comment by x9nico** [comment]
> @x9nico Hey there!
> Thank you for taking your time, could you tell us what your build number is and also test it on build number [8f396b1](https://github.com/SkinsRestorer/SkinsRestorerX/commit/8f396b199e633baf7611478c570e4c7612c8104e) with the jar https://github.com/SkinsRestorer/SkinsRestorerX/suites/3032317953/artifacts/68794428

I don't remember the number of build, it contains the PR #517 when I reported the error for 1.17 players with ViaVersion 4.0.0.
It looks like I don't have the error in this build. Thanks!
