### ISSUE TITLE
SkinsRestorer isn't working

### ISSUE THREAD

**Issue by PhoeNicZz** [SkinsRestorer/SkinsRestorerX#563]
I have installed SkinsRestorer onto my server, which is running Fabric and Spigot on 1.16.5. I have installed the latest version, however none of the commands seem to actually do anything. When I add a custom skin nothing happens and the skins folder in the plugin's folder stays empty, as well as the players folder.  Am I missing something?

**Comment by xknat** [comment]
1. you did not use the template
2. github is for coding issues and not support, for support use discord
3. Fabric is not one of the listed supported implementations. so no support will be given here or on discord1
