### ISSUE TITLE
SkinsRestorer 14.1.1 Error

### ISSUE THREAD

**Issue by KevstaRU** [SkinsRestorer/SkinsRestorerX#586]
1. I'm launching the Velocity proxy server
2. I connect and write a command /skin
3. error in the console and nothing happens

## Server information
On what platform does your server run? (Proxy -> Velocity + tuinity)

* SkinsRestorer: 14.1.1
* Spigot version: minecraft 1.16.5
* Velocity version: 3.0.0
* IF bungee, did you put the plugin on all servers: Yes
* Java: 16
* plugin list bungee & spigot: 
![image](https://user-images.githubusercontent.com/73141732/124677593-7a810280-dec9-11eb-9b6b-d96079d243f2.png)

## Logs
![image](https://user-images.githubusercontent.com/73141732/124677421-1b22f280-dec9-11eb-9743-a11b85db81e8.png)
![image](https://user-images.githubusercontent.com/73141732/124677451-30981c80-dec9-11eb-9b3d-7336d765c0af.png)

**Comment by xknat** [comment]
We don't yet support Velocity version: 3.0.0.
Please follow the status of https://github.com/SkinsRestorer/SkinsRestorerX/issues/511
