### ISSUE TITLE
SkinsRestorer - help message is not configurable

### ISSUE THREAD

**Issue by VojtaG** [SkinsRestorer/SkinsRestorerX#599]
**Screenshots**

![unknown](https://user-images.githubusercontent.com/56306485/127027965-72e04fa7-76db-4e8a-8ef4-c51013b976d3.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.1.1
* Spigot version: 1.16-1.17
* Bungeecord version: 1.17
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8

## Additional context
If you change SKINRESTORER PREFIX in messages.yml it doesn't change the help command (prefix) on any of all the servers.

**Comment by xknat** [comment]
Not a coding issue.
for support, pls join our discord.
tip: we have a wiki page covering locale / translating ;)

**Comment by EkonC** [comment]
Yeah, this is a coding issue @xknat.
There is no place where this message can be changed in messages.yml I think.

**Comment by xknat** [comment]
> Yeah, this is a coding issue @xknat.
> There is no place where this message can be changed in messages.yml I think.

did you read the wiki?
this is definitely not a coding issue.
make sure you look into acf file also.
join our discord for support, make sure you read our wiki first

**Comment by xknat** [comment]
like guys, cmon man.
even doing a simple search shows where it is..........
![image](https://user-images.githubusercontent.com/10220139/127185081-e2e7cbf2-6b19-44ee-bbc0-7cafd2e8e599.png)
