### ISSUE TITLE
[plugin incompatibility] oraxen 

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#600]
Update: Should be fixed in their 1.158.0 version.
----
We seem to not support oraxen gesture option.

---

oxagen is a paid plugin that allows custom items by using custom texutrepack that will convert unique mushroom stems

Skinsrestorer does currently not go well with texture packs causing compatibility issues.  

https://github.com/oraxen/oraxen
https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-oraxen-%C2%BB-custom-items-blocks-emojis-guis-and-more.72448/

**Comment by ShadowJaypeeBeast** [comment]
will support be added soon?

**Comment by xknat** [comment]
Support will likely to have been added on their side.
There is not a lot we can do as we use the same way paper does it...

**Comment by xknat** [comment]
Should be fixed in their 1.158.0 version
