### ISSUE TITLE
I would like to change the "[help] " in this line /skin help or completely remove it in the config.

### ISSUE THREAD

**Issue by Gignik** [SkinsRestorer/SkinsRestorerX#603]
Unfortunately, after changing all the lines in the plugin to another language, the line "/skin help " remains, where "[help] " cannot be changed to another language. Please allow me to change the line "[help] " to other languages, because it looks very strange and does not correspond to the translated text in another language and stands out very much (see the screenshot). In general, I think that the command " /skin help "is meaningless, because when you enter /skin," help "is already output and for some reason the command"/skin help " is written there. What is the point of leaving this command in the help for help? It would be even better if it was possible to completely remove it from there in the configuration, because this is pointless.

**Comment by Gignik** [comment]
![image](https://user-images.githubusercontent.com/51925511/127753917-bd92741a-92b1-406a-a66c-f162df4f0caa.png)

**Comment by xknat** [comment]
after looking at acf docs, this cant be done afaik, would need to ask to be sure

**Comment by xknat** [comment]
done, please try it with  latest dev build --> https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV
