### ISSUE TITLE
Velocity 3.0.0 not supported

### ISSUE THREAD

**Issue by ChiAkuma** [SkinsRestorer/SkinsRestorerX#607]
## Describe the bug
I use Velocity 3.0.0 and it says every time:

Couldn't pass ProxyInitializeEvent to skinsrestorer
java.lang.NoClassDefFoundError: net/kyori/text/format/TextColor

And i didnt found any velocity 3.0.0 detection in the code so i assume its not supported yet

## How can we reproduce what you got?
Use Velocity 3.0.0 and Skinsrestorer 14.1.1 and start the server.

**Expected behavior**
Should detect Velocity 3.0.0 and use it with no bugs in the terminal

**Screenshots**
![grafik](https://user-images.githubusercontent.com/37050667/128638961-5dbf917d-6c17-4941-8f99-ff9f7aba93ad.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Velocity 3.0.0

**What version? Do NOT answer LATEST**
* SkinsRestorer: 14.1.1
* Velocity version:  3.0.0
* IF bungee, did you put the plugin on all servers: Yes
* Java: 16
* plugin list velocity: Luckperms, Viaversion, viabackwards, Floodgate, GeyserMc

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://hastebin.app/611007fe831ba8001e320b9a

**Comment by AlexProgrammerDE** [comment]
Please use one of our dev builds: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastBuild/artifact/target/SkinsRestorer.jar
We will be releasing our dev branch soon. (velocity 3.0.0 support)
