### ISSUE TITLE
Invalid discord invite

### ISSUE THREAD

**Issue by NibiruGamer** [SkinsRestorer/SkinsRestorerX#618]
discord invite http://skinsrestorer.net/discord and https://discord.me/skinsrestorer is invalid, please fix it

**Comment by xknat** [comment]
works for me.
you sure your not banned?

**Comment by NibiruGamer** [comment]
I don't understand why anyone should ban me .... and I don't even remember being on that discord server ...

**Comment by NibiruGamer** [comment]
If i really banned, is exist unban form or something like this?

**Comment by xknat** [comment]
https://discord.gg/cXVZdJJc
try this link, will expire after 7 days
