### ISSUE TITLE
Is possible to add this?

### ISSUE THREAD

**Issue by NibiruGamer** [SkinsRestorer/SkinsRestorerX#619]
Is possible to add permissions from servers pex config separatelly (doesn't allow to change skin on gungame but allow on lobby) 
on skinsrestorer bungee mode? because using bungee pex is not good and compatible with sexypex pex fork ,,, and i want to add allow to change skin only for premium user and i don't want to manual adding permission in bungee config ....

**Comment by xknat** [comment]
use luckperms per server permissions

**Comment by NibiruGamer** [comment]
luckperms is shit and still not fixing my problem, I'm tested it ....

**Comment by TheAmazingZote** [comment]
> 
> 
> luckperms is shit and still not fixing my problem, I'm tested it ....

LuckPerms is pretty good and handy, probably you didnt configurate it correctly

**Comment by xknat** [comment]
i mean,,,, if you can't permissions, maybe consider watching a tutorial.
Its not we are running a playground

**Comment by xknat** [comment]
PS, github is for bugs, use discord for support!
