### ISSUE TITLE
Errors on the magma server

### ISSUE THREAD

**Issue by Herobrine-Minecraft-YouT** [SkinsRestorer/SkinsRestorerX#622]
When I was making the server on the magma, the errors shown in the screenshot appeared.

1. Download Magma
2. Make server
3. Download SkinsRestorer and put it to plugins folder
4. Start server and See error

**Expected behavior**
I thought it would work because I was doing a server on magma 1.12.2 before and everything worked.

**Screenshots**
https://cdn.discordapp.com/attachments/186794372468178944/875983866966442065/unknown.png

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Magma

**What version?
* SkinsRestorer: v14.1.3
* Magma version: v275780b
* Java: 8
* plugin list bungee & spigot: AuctionHouse, SkinsRestorer, DiscordSRV, HolographicDisplays, WorldEdit, WorldGuard, LuckPerms, MVdWPlaceholderAPI, OldCombatMechanics, Parties, PlaceholderAPI, ServerListPlus
* MinecraftLauncher?: Minecraft Premium Launcher (It wasn't turned on, it's a bug in the console)

## Logs
https://hastebin.app/6117681a831ba8001e320ba4

**Comment by xknat** [comment]
unsupported implementation
