### ISSUE TITLE
Update SpigotMC page

### ISSUE THREAD

**Issue by aljaxus** [SkinsRestorer/SkinsRestorerX#666]
* https://www.spigotmc.org/resources/skinsrestorer.2124/

### What to do

Replace
```best to just use "shiginima launcher" as its modless```
with
```best to just use "MultiMC-cracked" as its modless```

### Why?

Because shiginima launcher is no longer maintained and we are already recommending MultiMC for some time now via the support channels.

**Comment by xknat** [comment]
done
