### ISSUE TITLE
Players able to steal heads from /skins GUI

### ISSUE THREAD

**Issue by antibitcoin** [SkinsRestorer/SkinsRestorerX#683]
Simple as that, players are able to somehow steal heads from the GUI manipulating clicks etc.
it's a survival server.
here is the full info you will need such as version, plugins etc.
https://paste.md-5.net/orubodepun

Regards

**Comment by xknat** [comment]
Plz give us your censored config of skinsrestorer

**Comment by xknat** [comment]
@antibitcoin any update?
resolved with latest dev build?

**Comment by xknat** [comment]
No updated from issuer

**Comment by antibitcoin** [comment]
> No updated from issuer

I have uninstalled it, just here to close the issue, the issue is when you install skin restorer on bungee, all heads can be picked up easily.

Regards
