### ISSUE TITLE
Running SELECT 1; before every SQL connection?

### ISSUE THREAD

**Issue by aljaxus** [SkinsRestorer/SkinsRestorerX#695]
Ref; https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L80

Are we actually running an additional query every time we are querying the database for some record?
Because every time [`execute()`](https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L115) is called, the [`getConnection()`](https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L70) is called to get the connection object which, before returning the connection object, [runs the `SELECT 1;` query](https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L80).

Every time.
![image](https://user-images.githubusercontent.com/24414483/134505737-ebdf28eb-9881-4d38-9cb2-4d9aafc7ed3e.png)

I think that this should be addressed because it might have a - even if small - performance improvement, especially for large server networks.

**Comment by aljaxus** [comment]
Only now I realize that all those calls from `SkinApplierSponge.java`, `SkinsRestorer.java`, `SkinCommand.java` and  `SrCommand.java` are not references to the `execute()` method I was talking about but apparently GitHub only looks at the method names instead of actual references.

Nevertheless my point still stands.

**Comment by xknat** [comment]
resolved in 49c8e01b5f4b6d307ab53c976162b18411e75597
