### ISSUE TITLE
Remove countdown

### ISSUE THREAD

**Issue by LuigiImVector** [SkinsRestorer/SkinsRestorerX#703]
There is a way to remove/edit the countdown between commands?

![image](https://user-images.githubusercontent.com/59611597/136705166-0a4c207b-9936-412a-917a-0448ba75987b.png)

**Comment by xknat** [comment]
use bypass permission or set value to 0

**Comment by LuigiImVector** [comment]
> use bypass permission or set value to 0

where should I set the value to 0?

**Comment by xknat** [comment]
> where should I set the value to 0?

on cooldown in config

**Comment by xknat** [comment]
our github is NOT for player support, if you need help, join our discord
