### ISSUE TITLE
Firewall problem

### ISSUE THREAD

**Issue by Lewnadovsky** [SkinsRestorer/SkinsRestorerX#708]
## Describe the bug

Hi! I have a problem with the plugin. Despite adding rules to the firewall, the plugin refuses to connect to the API. After typing /sr status shows no connection to the Mojang and other APIs. Im using actually ufw firewall

**Screenshots**

## Server information

**BungeeCord**

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.5
* Spigot version: 1.17
* Bungeecord version: git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:bda1605:1598
* IF bungee, did you put the plugin on all servers: Yes
* Java: openjdk version "16.0.1" 2021-04-20
* plugin list bungee & spigot:
* Bungee: AuthMeBungee, AutoReconnect, BungeeAliases, BungeTeleport, Canela Anti-PluginSteal, LobbyAFK, LuckPerms - Bungee, SpigotBridge, TAB, VentureChat, ViaBackwards, ViaVersion
* MinecraftLauncher?: Idk what i can type here.
* if multiverse, (censored) worlds file: none

## Logs

https://hastebin.app/617818f1692a4d001d93dd10

**Comment by Lewnadovsky** [comment]
nvm fixed.

**Comment by xknat** [comment]
@MrKatrioPL our GitHub is not for support.
Please join our discord for help
