### ISSUE TITLE
SkinsRestorer bugged behavior on plugin's CustomWorlds on Mohist (Hybrid Forge + Bukkit)

### ISSUE THREAD

**Issue by EverNife** [SkinsRestorer/SkinsRestorerX#713]
## Describe the bug

Related to this https://github.com/MohistMC/Mohist/issues/1818

The part of the code bellow is not getting the correct DimensionID on Mohist. That causes the world to go entirely blue on the skin update.

https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/bukkit/src/main/java/net/skinsrestorer/bukkit/skinrefresher/SpigotSkinRefresher.java#L133-L137

## How can we reproduce what you got?

 1. Install mohist and set the server to OfflineMode
 2. Add SkinsRestorer to the plugins folder
 3. Add a WorldManager plugin (like Multiverse-Core or WorldMania)
 4. Create a custom world with the plugin
 5a. Move to this new world and logoff
 6a. Login again, you will notice all world will be like this.
 
![image](https://user-images.githubusercontent.com/11357801/139578120-4cbc7cb5-11ed-4bc5-9616-43657987987a.png)

 The Issue can be replicated with these other steps

 5b. Move to this new world and use /skin update

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)** 
Mohist (Spigot + Forge)

**What version? Do NOT answer LATEST**
Commit 68e9f6ff36b1505bb7aba3f5471b92f97b317b1d (30/out/2021)

* SkinsRestorer: 68e9f6ff36b1505bb7aba3f5471b92f97b317b1d
* Spigot version: 1.12.2
* Java: 8

## How to fix?

Use reflection to get the correct DimensionID for the dimension. 

I haven't opened a pull request because i have no idea how you will want to manage this, if its better to create a new "HybridSkinRefresher" of if it will just edit the SpigotSkinRefresher.

**Comment by EverNife** [comment]
To help out with the fix on 1.12.2 forge hybrid should be something like this

![image](https://user-images.githubusercontent.com/11357801/139600263-5ab3d19f-8886-4aad-856b-b8646d61032b.png)

```
try {
    Class.forName("net.minecraftforge.fml.common.Loader");  //Change this to a boolean "IF forge is present"
   
    Object worldServer = ReflectionUtil.invokeMethod(player.getWorld(), "getHandle");
    Object provider = ReflectionUtil.getObject(worldServer, "field_73011_w");//"provider" field
    Object dimensionID = ReflectionUtil.invokeMethod(provider, "getDimension");
    dimension = (int) dimensionID;
} catch (Exception ignored){
}
respawn = ReflectionUtil.invokeConstructor(playOutRespawn, dimension, difficulty, worldType, enumGamemode);
```

**Comment by xknat** [comment]
sr v13.8.9 works for mohist on 1.12.2

**Comment by EverNife** [comment]
Tested **[v13.8.9]** on latest mohist 304

![image](https://user-images.githubusercontent.com/11357801/152368403-38f71598-772f-47ec-bfd9-d74fb55065c4.png)

**Comment by EverNife** [comment]
The problem on latest version is the same as i stated before. Its a logical problem!

On Mohist/Magma or any other modded platform the code

**int dimension = player.getWorld().getEnvironment().getId();**

**Will not** return the correct dimension id, it will return the EnvironmentID, that is usually the correct one, but not on custom worlds created by plugins.

I will fix this and open a pull request.

Thinking straight this problem should be fixed on their side! There is no way to get the WorldID from bukkit on these platform.
