### ISSUE TITLE
Error: Invalid skin url or format

### ISSUE THREAD

**Issue by opiums9** [SkinsRestorer/SkinsRestorerX#723]
Hello, please tell me, what is the difference between this url: https://i.ibb.co/8YdFbKG/dima2.png and this url: https://minecraft.opiums.eu/skin/dima2.png?
The first one is downloaded and installed, the second gives an error, these are completely the same images, what is wrong with downloading images from my site?
![image](https://user-images.githubusercontent.com/25082773/140291889-b6240fe3-0b51-4b7d-9311-e5fc887492fa.png)

**Comment by xknat** [comment]
For support, please join our discord or dm srteam on spigotmc.
Only confirmed bugs and coding issues are allowed here.
