### ISSUE TITLE
When I sit on a block using the Gsit plugin and change the skin I go through the block below, if they have a way to solve this, it's very annoying

### ISSUE THREAD

**Issue by thiagogebrimm** [SkinsRestorer/SkinsRestorerX#728]
## Describe the bug

When I sit on a block using the Gsit plugin and change the skin I go through the block below, if they have a way to solve this, it's very annoying

## How can we reproduce what you got?

I sit with "/sit" and skin change

**Expected behavior**
Shouldn't cross the block

## Server information

Purpur

**What version? Do NOT answer LATEST**

* SkinsRestorer: Version 14.1.6 
* Spigot version: Purpur 1423
* Bungeecord version: Waterfall 452
* IF bungee, did you put the plugin on all servers: Yes
* Java: 16
* plugin list bungee & spigot: Gsit and SkinRestorer
* MinecraftLauncher?: Vanilla

**Comment by xknat** [comment]
github is not for user support. join discord or dm srteam on spigot.
