### ISSUE TITLE
If we join the server after starting, the skins doesn't restore automatically

### ISSUE THREAD

**Issue by TISnoob** [SkinsRestorer/SkinsRestorerX#761]
## How can we reproduce what you got?

**Expected behavior**

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer:
* Spigot version:
* Bungeecord version:
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

## Additional context

Hello. I am spigot 1.18 player.
In my server , the skin don't automatically restore. We have to restore it by commands. In previous versions the skin restore fully automatically

**Comment by AlexProgrammerDE** [comment]
Could you please fill out the form? We didn't make it for nothing...

**Comment by xknat** [comment]
should be resolved with https://github.com/SkinsRestorer/SkinsRestorerX/releases
if not, please join our discord for support.
