### ISSUE TITLE
Issues with SkinRestorer while using Cardboard for Fabric 1.18

### ISSUE THREAD

**Issue by Zhenrio** [SkinsRestorer/SkinsRestorerX#762]
When i upload the plugin, he's detected but he can't load normally. i don't know if it's because of cardboard but with Cardboard we're supposed to be able to use spiggot and bukkit plugins. 
In server log i can read this : 

i joined server's log on this request
[log.txt](https://github.com/SkinsRestorer/SkinsRestorerX/files/7669301/log.txt)

**Comment by xknat** [comment]
what is cardboard?
we cant support everything in the world...
cardboard is not on our supported implementation list and works as is.

**Comment by Zhenrio** [comment]
i was expecting this answer... thanks anyway.

**Comment by AlexProgrammerDE** [comment]
Well I'm gonna assign this one to myself. It should not be hard to fix this.
