### ISSUE TITLE
Spigot 1.18, SkinRestorer not loading skins on login 

### ISSUE THREAD

**Issue by FireLion137** [SkinsRestorer/SkinsRestorerX#764]
## Describe the bug

SkinRestorer don't load skins on login. 

## How can we reproduce what you got?

1. Connect into the Server (Spigot 1.18);
2. You can see you have no skin, do "/sr applyskin", "/skin update" or "/skin set";
3. Disconnect and reconnect;
4. You can see there is no skin.

**Expected behavior**
SkinRestorer don't load skins on login. I can set the skin by using "/sr applyskin", "/skin update" and "/skin set", files in directories are created (by using this commands, by loggin only not) but not uploaded on the player when I enter in the server.

**Screenshots**
I add a video: https://user-images.githubusercontent.com/55352707/145062241-036c2c5e-2c78-4ef0-9494-0b096588a0e8.mp4
Dont pay attention to the "[Skin Restorer]" written several times after using the commands, it is just a consequence of having deleted the folders and reloaded the plugin several times. This bug happens always.

## Server information

Spigot 1.18

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.7
* Spigot version: 1.18
* Bungeecord version: NO
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot: SkinRestorer, ProtocolLib, LoginSecurity-3.1, Harbor-1.6.3, FastLoginBukkit.
* MinecraftLauncher?: 
* if multiverse, (censored) worlds file:

## Logs

https://hastebin.app/61af82853e1287001cc18ab1

**Comment by xknat** [comment]
For user support, please join our discord
