### ISSUE TITLE
Skin not applying automatically after relog

### ISSUE THREAD

**Issue by ghost** [SkinsRestorer/SkinsRestorerX#767]
## Describe the bug

When First logging on the server the Skin is applied but if if i leave no matter the times i come back my skin won't apply automatically. 

## How can we reproduce what you got?

1. Go into Server
2. The Skin is the right one
3. Leave Server
4. Relog into Server
5. Skin is now alex

**Expected behavior**
Every time i relog, my skin should apply automatically. even without a restart
**Screenshots**

## Server information

Spigot

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.7 (DEV version does this too)
* Spigot version: CraftBukkit version 3355-Spigot-dbf4938-3c2af1b (MC: 1.18)
* Java: 17
* plugin list bungee & spigot:
* ![2021-12-07_20 15 09](https://user-images.githubusercontent.com/74419824/145093949-4a90147d-9f2c-426f-a4ec-2d50244090da.png)

## Logs

https://hastebin.app/61afb6c73e1287001cc18ab4

**Comment by xknat** [comment]
Should be resolved with https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest
if not, join our discord for support
