### ISSUE TITLE
SkinsRestorer v14.1.8 not working with ProtocolLib v4.8.0-SNAPSHOT-b538

### ISSUE THREAD

**Issue by KygekDev** [SkinsRestorer/SkinsRestorerX#771]
## Describe the bug

I got an `Segmentation error` error with VMState `0x00040000` after the message `[SkinsRestorer] Hooking into ProtocolLib for instant skins on join!` whenever my server is starting.

## How can we reproduce what you got?

1. Download and install the latest version of IBM Semeru JDK 17 from GitHub and add to PATH (https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.1%2B12_openj9-0.30.0-m1)
2. Create a new directory for Minecraft server
3. Download the latest version of PaperMC (https://papermc.io/downloads)
4. Start the server for the first time and accept the EULA
5. Download the latest build of ProtocolLib (https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)
6. Download SkinsRestorer v14.1.8 from GitHub (https://github.com/SkinsRestorer/SkinsRestorerX/releases/tag/14.1.8)
7. Restart the server and you should see an error

**Expected behavior**

The server should start successfully without any errors or crashes.

## Server information

**On what platform does your server run? PaperMC**

**What version? git-Paper-59 (MC: 1.18)**

* SkinsRestorer: v14.1.8
* Spigot version: Paper version git-Paper-59 (MC: 1.18)
* Bungeecord version: -
* Java: Java 17 (Eclipse OpenJ9 VM openj9-0.29.1-m1) Host: Windows 10 10.0 (amd64)
* plugin list bungee & spigot: SkinsRestorer & ProtocolLib
* MinecraftLauncher?: -

## Logs

https://hastebin.app/61b092cb3e1287001cc18ab6

**Comment by xknat** [comment]
confirmed issue with openj9
pls join our discord for support.
