### ISSUE TITLE
Is it possible to download a skin that has been used on the plugin?

### ISSUE THREAD

**Issue by GoddessSans** [SkinsRestorer/SkinsRestorerX#773]
This is in no way a bug or enhancement suggestion, it is only that I dont know if I can get my hands through the files on the skins that have been applied on a specific server...
I guess that probably not, and also I'm sorry if this is not the kind of Issue that should be opened, but thanks anyways and in advance!

**Comment by AlexProgrammerDE** [comment]
Yes it is possible, but please join our discord server and ask the question there. Github is for code issue tracking for us at least. I will explain it to you once you've joined the discord server.
