### ISSUE TITLE
Bungeemode not working properly on Spigot forks where spigot.yml is renamed

### ISSUE THREAD

**Issue by Dennoquellovero** [SkinsRestorer/SkinsRestorerX#789]
The plugin doesn't work properly on one of my sub-servers that runs SportPaper, starting in Standalone Mode instead of Bungee. It does work properly on the other sub-servers that run PaperMC.

I believe it might be because the configuration file for the server is called sportpaper.yml, instead of the default spigot.yml.

I'm using a PaperMC fork called SportPaper, running in a Velocity proxy.

===== info from discord ============
I've realized this might be because my server configuration file is called sportpaper.yml instead of spigot.yml

**Comment by xknat** [comment]
No such generic api available. Guess we should point out the override files.

**Comment by AlexProgrammerDE** [comment]
The Bukkit.spigot().getConfig() should normally work just fine as a replacement, and we are using that as our API.

**Comment by AlexProgrammerDE** [comment]
SpigotConfigUtil.getSpigotConfig(server) calls the spigot config in memory, so this is not an issue anymore
