### ISSUE TITLE
Wrong permission in the wiki

### ISSUE THREAD

**Issue by mhmatthewhugley** [SkinsRestorer/SkinsRestorerX#813]
On the wiki "https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms#admin-commands" in the admin commands section.

This permission is listed twice "skinsrestorer.admincommand.applyskin"

The second time it is listed it should say "skinsrestorer.admincommand.createcustom"

**Comment by xknat** [comment]
thanks

**Comment by mhmatthewhugley** [comment]
Also This permission "skinsrestorer.admincommand.reload" Is missing from this part of the perm list on the wiki "https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms#permlist"

**Comment by mhmatthewhugley** [comment]
It should be put right below the .props one

**Comment by xknat** [comment]
> It should be put right below the .props one

✔️
