### ISSUE TITLE
improve locale for translators

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#817]
- [ ] timed out --> interruption
- [ ] player or skin --> beter define that there is a switch statement in data removal 
- [ ] encapsulate variables with `<>`

**Comment by PaBox** [comment]
- [ ] Remove double entries, for example `Completions_Skin/COMPLETIONS_SKIN`, `Completions_SkinName/COMPLETIONS_SKINNAME` and `Completions_SkinUrl/COMPLETIONS_SKINURL`

**Comment by xknat** [comment]
> * [ ]  Remove double entries, for example `Completions_Skin/COMPLETIONS_SKIN`, `Completions_SkinName/COMPLETIONS_SKINNAME` and `Completions_SkinUrl/COMPLETIONS_SKINURL`

cant be done in crowdin as they are not the same string and i wont change locale at the cost of customization

**Comment by PaBox** [comment]
Why is there a doubled definition of the same thing?

**Comment by xknat** [comment]
> Why is there a doubled definition of the same thing?

for the sake of customization...

**Comment by xknat** [comment]
> Why is there a doubled definition of the same thing?

Maybe if you put in some reference we would be able to figure out what your pointing to

**Comment by PaBox** [comment]
> * [ ]  Remove double entries, for example `Completions_Skin/COMPLETIONS_SKIN`, `Completions_SkinName/COMPLETIONS_SKINNAME` and `Completions_SkinUrl/COMPLETIONS_SKINURL`

Those are the double entries I found, each Version exists in Caps and in the normal format. One set in the middle, one at the end of the lang file. If you press `ctrl`+`f` you can search the entries and each exists only one time (6x1), I don`t know how I could be more specific - please tell me what else I could send to prove this.

**Comment by xknat** [comment]
> > * [ ]   Remove double entries, for example `Completions_Skin/COMPLETIONS_SKIN`, `Completions_SkinName/COMPLETIONS_SKINNAME` and `Completions_SkinUrl/COMPLETIONS_SKINURL`
> 
> Those are the double entries I found, each Version exists in Caps and in the normal format. One set in the middle, one at the end of the lang file. If you press `ctrl`+`f` you can search the entries and each exists only one time (6x1), I don`t know how I could be more specific - please tell me what else I could send to prove this.

https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/shared/src/main/java/net/skinsrestorer/shared/storage/Locale.java#L62-L64

where are the duplicates?

**Comment by xknat** [comment]
@PaBox ah, i think where your going...
No, the translations are not yet ready
This is only the new format.
you should not use the new format yet since it's still in development and not connected to new langue system so obvious there is conflict.

Never told you could could use the translations now being translated, we are translating them ahead of time.
The syntax is not the same, so it will put in lines from locale..... 
Please do not discus this further as this is still wip and not ready for testing in any way or kind.
We will inform testers to test when it's ready to test thank you.
