### ISSUE TITLE
Conflict with MOD Curios API

### ISSUE THREAD

**Issue by zoe-may** [SkinsRestorer/SkinsRestorerX#829]
When the plugin is used with the MOD Curios API, the GUI interface of the MOD (Curios API) will not open (as shown)

![image](https://user-images.githubusercontent.com/71170887/151712836-902a6aa9-b8e3-44d0-a58f-3e122ffa022a.png)
This is normal situation

![image](https://user-images.githubusercontent.com/71170887/151712885-3390345e-c1ba-4601-b09d-e7c102cbe418.png)
This is not normal situation

I saw that the mod author couldn't do anything about this bug, so I came to seek your help, thank you very much!

(Also, because my English is not very good, this paragraph was translated using a translator, so please forgive me if there are grammatical errors)

**Comment by xknat** [comment]
We don't support mod... definitely not client side mods.

**Comment by zoe-may** [comment]
By the way, this is the Github link address of the MOD
https://github.com/TheIllusiveC4/Curios

**Comment by xknat** [comment]
We dont support forge, please use a supported implementation and try again.

**Comment by zoe-may** [comment]
Yes I know, but this mod is important to many other mods, and it's obvious that this is caused by the SkinsRestorerX plugin. This problem only exists in multiplayer servers

**Comment by zoe-may** [comment]
> 我们不支持 forge，请使用受支持的实现，然后重试。

I really hope this problem can be solved
