### ISSUE TITLE
Conflict issues with mod Curios API

### ISSUE THREAD

**Issue by zoe-may** [SkinsRestorer/SkinsRestorerX#830]
I'm sorry to bother you againI know it's a server plugin, but it conflicts with the MOD Curios API，Curios API is the front mod for many other mods, and I'm pretty sure it's the SkinsRestorerX plugin that's causing the problem，So this bug is very unfriendly to the forge server.I really like the SkinsRestorerX plugin and I'd be sorry if I couldn't use it.
Please forgive me if I cause you any trouble.

Attach pictures：
![image](https://user-images.githubusercontent.com/71170887/151713918-ed979d42-10d5-4642-be32-9de0449d8d06.png)
![image](https://user-images.githubusercontent.com/71170887/151713922-4cdb219a-232c-4252-aaf4-1884855431c2.png)

**Comment by xknat** [comment]
We don't support forge, if we are unfriendly to forge, then solution: DONT USE FORGE
We dont support forge,
dont use forge for skinsrestorer

use what we support
dont use what we do not support

If mods complain about us not supporting them
we do not test what we do not support

Not gonna test how well my car can fly if it's not planned to fly....

**Comment by zoe-may** [comment]
> We don't support forge, if we are unfriendly to forge, then solution: DONT USE FORGE We dont support forge, dont use forge for skinsrestorer
> 
> use what we support dont use what we do not support
> 
> If mods complain about us not supporting them we do not test what we do not support
> 
> Not gonna test how well my car can fly if it's not planned to fly....

I am very sorry to bother you, thank you for your reply
