### ISSUE TITLE
add dot in removeForbiddenChars

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#844]
https://github.com/SkinsRestorer/SkinsRestorerX/blob/fbba4cf14316e7460f896f49aabd1ff2c7db3dec/shared/src/main/java/net/skinsrestorer/shared/storage/SkinStorage.java#L660

- [ ] add dot
- [ ] cache regex

**Comment by iGabyTM** [comment]
And also cache the regex, I see that it is used on multiple places.

**Comment by xknat** [comment]
> And also cache the regex, I see that it is used on multiple places.

Full skin storage rewrite is on the way. Will add it to the issue thanks @iGabyTM

**Comment by xknat** [comment]
> And also cache the regex, I see that it is used on multiple places.

@iGabyTM done, thanks for the tip
