### ISSUE TITLE
[Velocity] I cant use SR commands on paper console

### ISSUE THREAD

**Issue by Scrulius** [SkinsRestorer/SkinsRestorerX#857]
Hello! I have a problem

I am using SkinsRestorer in velocity and paper, the problem is that when I use a SkinsRestorer command in the paper console nothing happens, it doesn't change the skin but it doesn't give error either

To reproduce:

- Install bungee/waterfall/velocity
- try to change a player skin using the paper console
- Nothings happens.

Only works if the player use the command or you type the command in the bungee console.

Minecraft version: 1.18.1
Using Purpur 1565
Using velocity 3.1.1
Using SkinsRestorer 14.1.10

**Comment by xknat** [comment]
github is not for support, contact us on discord.
