### ISSUE TITLE
1.18.2 compability

### ISSUE THREAD

**Issue by sphings79** [SkinsRestorer/SkinsRestorerX#864]
## Describe the bug

Plugin won't load on 1.18.2

## How can we reproduce what you got?

upgrade your server to 1.18.2
restart the server

**Expected behavior**
Plugin should load

**Screenshots**
-

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper version git-Paper-220 (MC: 1.18.2)

**What version? Do NOT answer LATEST**

* SkinsRestorer: SkinsRestorer version 14.1.10
* Spigot version: Paper version git-Paper-220 (MC: 1.18.2)
* Bungeecord version:
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 17
* plugin list bungee & spigot:
* MinecraftLauncher?: GD Launcher
* if multiverse, (censored) worlds file:

## Logs

https://mclo.gs/aqgLSNG

**Comment by xknat** [comment]
thanks for letting us know paper is out
