### ISSUE TITLE
Plugin SkinsRestorer v14.1.13 generated an exception while executing task 30133

### ISSUE THREAD

**Issue by PappoYT** [SkinsRestorer/SkinsRestorerX#877]
## Describe the bug

When a player login the server I get this error in console:
`[Craft Scheduler Thread - 140 - SkinsRestorer/WARN]: [SkinsRestorer] Plugin SkinsRestorer v14.1.13 generated an exception while executing task 30133
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: plugins/SkinsRestorer/Players/?paladinodeimari.player
	at sun.nio.fs.UnixPath.encode(UnixPath.java:121) ~[?:?]
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:68) ~[?:?]
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279) ~[?:?]
	at java.io.File.toPath(File.java:2387) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorage.getSkinName(SkinStorage.java:185) ~[SkinsRestorer-14.1.13.jar:?]
	at net.skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:51) ~[SkinsRestorer-14.1.13.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-235]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-235]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

## How can we reproduce what you got?

1. Login server
2. see console

**Expected behavior**
no error

**Screenshots**
n/a

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper 1.18.2 build 235

**What version? Do NOT answer LATEST**

* SkinsRestorer: SkinsRestorer-14.1.13
* Spigot version: Paper 1.18.2 build 235
* Bungeecord version: n/a
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 17
* plugin list bungee & spigot:
* MinecraftLauncher?: bedrock 1.18.12
* if multiverse, (censored) worlds file:

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com/PappoYT/af9b03ce8223423b3d2639b35e3dde9b
https://hastebin.app/6227103a7c6b36001b89aeef

## Additional context

n/a

**Comment by xknat** [comment]
> ## Describe the bug
> When a player login the server I get this error in console: `[Craft Scheduler Thread - 140 - SkinsRestorer/WARN]: [SkinsRestorer] Plugin SkinsRestorer v14.1.13 generated an exception while executing task 30133 java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: plugins/SkinsRestorer/Players/?paladinodeimari.player at sun.nio.fs.UnixPath.encode(UnixPath.java:121) ~[?:?] at sun.nio.fs.UnixPath.<init>(UnixPath.java:68) ~[?:?] at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279) ~[?:?] at java.io.File.toPath(File.java:2387) ~[?:?] at net.skinsrestorer.shared.storage.SkinStorage.getSkinName(SkinStorage.java:185) ~[SkinsRestorer-14.1.13.jar:?] at net.skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:51) ~[SkinsRestorer-14.1.13.jar:?] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-235] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-235] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-235] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> ## How can we reproduce what you got?
> Steps to reproduce the behavior:
> 
> 1. Login server
> 2. see console
> 
> **Expected behavior** no error
> 
> **Screenshots** n/a
> 
> ## Server information
> **On what platform does your server run? (Bungeecord/Spigot/Bukkit)** Paper 1.18.2 build 235
> 
> **What version? Do NOT answer LATEST**
> 
> * SkinsRestorer: SkinsRestorer-14.1.13
> * Spigot version: Paper 1.18.2 build 235
> * Bungeecord version: n/a
> * IF bungee, did you put the plugin on all servers: Yes / No
> * Java: 17
> * plugin list bungee & spigot:
> * MinecraftLauncher?: bedrock 1.18.12
> * if multiverse, (censored) worlds file:
> 
> ## Logs
> Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord _AND_ Spigot/Bukkit**) https://gist.github.com/PappoYT/af9b03ce8223423b3d2639b35e3dde9b https://hastebin.app/6227103a7c6b36001b89aeef
> 
> ## Additional context
> n/a

You have a question mark "?" As prefix

Think we don't support that

**Comment by PappoYT** [comment]
The prefix is a dot "." not a question mark "?" (see image).
![Cattura](https://user-images.githubusercontent.com/74958346/157276767-3c38f36f-11ab-4b2f-9622-25b18785eb8f.PNG)

The dot is added by floodgate/geyser.

**Comment by xknat** [comment]
pls join our discord for support.

**Comment by PappoYT** [comment]
@xknat could you give me the invitation link to Discord? I cannot find it on SpigotMC neither here...

**Comment by xknat** [comment]
> @xknat could you give me the invitation link to Discord? I cannot find it on SpigotMC neither here...

https://github.com/SkinsRestorer/SkinsRestorerX#link-links
