### ISSUE TITLE
Bungee online mode refresher stopped working

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#883]
changing skin when using bungee in online mode stopped working.
Seems to be the case for latest release of bungee / paper & spigot
issue also on `14.1.10`
ref: `ticket-1646994316`

todo: 
- [ ] test local

**Comment by DearFox** [comment]
It also doesn't seem to work on purpur-1.20.1-2050 with online-mode = true

**Comment by DearFox** [comment]
> It also doesn't seem to work on purpur-1.20.1-2050 with online-mode = true

in online-mode = false on the same server everything works fine.

**Comment by xknat** [comment]
> stopped working

as in it stopped working (worked in the past)
or recent dev builds resulted in this functionality no longer working?
or you are new and never worked

**Comment by DearFox** [comment]
> > stopped working
> 
> as in it stopped working (worked in the past) or recent dev builds resulted in this functionality no longer working? or you are new and never worked

I have known about this plugin for a long time, but I installed it on the server `online-mode = true` for the first time
And it doesn't seem to work now.

**Comment by xknat** [comment]
Resolved some time back
