### ISSUE TITLE
Floodgate causing InvalidPathException: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#886]
Dev note
Illegal character name is not escaped in https://github.com/SkinsRestorer/SkinsRestorerX/blob/18aaff388de4b44c8475c8d725bbd16760df4e8b/shared/src/main/java/net/skinsrestorer/shared/commands/ISkinCommand.java#L229

Confirming:
- [x] Working in windows
- [x] Working in ubuntu 20 --> https://i.imgur.com/iARuE8J.png
- [ ] working in docker

**Comment by emongev** [comment]
I had this exact issue when having a period (".") as the prefix , i switched it to underscore to fix it, but it would be ideal to go back to period afterwards

**Comment by xknat** [comment]
may already have been resolved

**Comment by xknat** [comment]
should be resolved https://github.com/SkinsRestorer/SkinsRestorerX/blob/745eedc744cc21e618ac804f73521a2c86e4aaea/shared/src/main/java/net/skinsrestorer/shared/storage/SkinStorage.java#L259
