### ISSUE TITLE
MYSQL mysql_native_password CRASH

### ISSUE THREAD

**Issue by Catzy44** [SkinsRestorer/SkinsRestorerX#889]
Hello,
I'm using MySQL 8.0.28-0ubuntu0.20.04.3

Here's the error: https://pastebin.com/raw/W0BETWvZ

**Comment by xknat** [comment]
> Hello, I'm using MySQL 8.0.28-0ubuntu0.20.04.3
> 
> Here's the error: https://pastebin.com/raw/W0BETWvZ

Hello,

Pls read the notes.
![image](https://user-images.githubusercontent.com/10220139/158561128-3c698411-2c14-4f8b-9850-3dbccb40de0e.png)
