### ISSUE TITLE
Change the skin except the head

### ISSUE THREAD

**Issue by Rossi-56** [SkinsRestorer/SkinsRestorerX#907]
Hello,

Is it possible to change the skin except the head?
Is there a way to generate a new skin for each player where only head changes?

**Comment by AlexProgrammerDE** [comment]
GitHub is only for proven bug reports and coding stuff. Please join our discord next time https://discord.gg/sAhVsyU
I swear we have been asked that same question 2 days ago. The answer is still no. You will have to manually replace the lower skin data with some image editor. You could then apply that skin with skinsrestorer.

**Comment by Rossi-56** [comment]
sorry
