### ISSUE TITLE
Add placeholders

### ISSUE THREAD

**Issue by spikehidden** [SkinsRestorer/SkinsRestorerX#908]
- Adding of placeholders for uuid and player (or adding placeholderAPI support) for the use in default skin urls. - This would make it possible to use the following API and auto add the original Skin of Bedrock Players when using GeyserMC.
- API: https://tydiumcraft.net/docs/skinapi

**Comment by xknat** [comment]
wrong plugin, you should be at https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion
