### ISSUE TITLE
Skin reset for premium players - Velocity

### ISSUE THREAD

**Issue by vincenzopio** [SkinsRestorer/SkinsRestorerX#912]
!! This bug happens on Velocity when a player connection is in online mode.

When a premium player changes his skin using /skin set command and then rejoins the network the player's skin resets.
I looked up the /sr props properties and SkinsRestorer, I don't know how and why, automatically clears the skin and sets the premium player his own skin even if changed by command.

**Comment by xknat** [comment]
join our discord for support
