### ISSUE TITLE
Steal skulls from skins gui

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#927]
Seems like you can steal skulls from GUI. oops...
To disable skins GUI:
Turn off skinswithoutperms in sr config (bungee)
Then give perms in config.yml: (bungee)
```
- skinsrestorer.command
- skinsrestorer.command.set
- skinsrestorer.command.set.url
- skinsrestorer.command.clear
- skinsrestorer.command.update
```

Dev notes:

**Comment by xknat** [comment]
resolved with https://github.com/SkinsRestorer/SkinsRestorerX/commit/74c6f667955e2a6eb95b3456eb538441f93315ff

**Comment by radiant-ai** [comment]
It is still possible to steal skulls at Waterfall-Paper setup running with the dev build

**Comment by xknat** [comment]
> It is still possible to steal skulls at Waterfall-Paper setup running with the dev build

not true, your likely using release and not dev
dev builds: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV
