### ISSUE TITLE
Icons(playerhead) in GUI can be moved into inventory with Waterfall

### ISSUE THREAD

**Issue by JinOuYongGu** [SkinsRestorer/SkinsRestorerX#934]
## Describe the bug

When using Waterfall-484 and skinsrestorer 14.1.15, Icons(playerhead) in GUI can be moved into inventory with Waterfall. And the playerheads can be placed as normal blocks

## How can we reproduce what you got?

1. Install SR both in waterfall and purpur server
2. input /skins command to open the gui
3. drop the icons out

**Expected behavior**
No icons will be moved

**Screenshots**
![image](https://user-images.githubusercontent.com/45219386/165408345-10100d28-df15-46de-8059-5873d5f9e65e.png)
## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.15
* Purpur version: Current: git-Purpur-1566 (MC: 1.18.1)*
* Bungeecord version: Waterfall-484
* IF bungee, did you put the plugin on all servers: Yes
* Java: 17
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file: world

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app/62687f14d3810c001cf24ab1

**Comment by AlexProgrammerDE** [comment]
Please use a dev build. It is fixed in there. https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/317/artifact/build/libs/SkinsRestorer.jar
Next time please join our discord server instead. The bug fix will be released in the next update.
