### ISSUE TITLE
The plugin is not compatible with Velocity?

### ISSUE THREAD

**Issue by Flavelm** [SkinsRestorer/SkinsRestorerX#935]
## Describe the bug

I checked in all modes, don't work!

I installed according to the instructions for spigot, but the skins did not appear.
But the skins in the tab are displayed.
Spigot plugin not compatible with paper?

There are no errors in the console.

## How can we reproduce what you got?

1. wget https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.15/SkinsRestorer.jar
2. cd ..
3. java -jar Velocity.jar
4. cd ~/BukkitServer/plugins
5. wget https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.15/SkinsRestorer.jar
6. cd ..
7. nano spigot.yml --> "bungeecord: true"
8. java -jar server.jar

I was looking for a skin on the character, but it never appeared

[image hidden]

## Server information

* SkinsRestorer:  Last
* Paper version: 1.16.5 (last)
* Bungeecord version: (Velocity) 3.1.1 
* I put the plugin on the proxy and server for testing.
* Java: 16
* Paper plugins:
ProtocolLib
BungeeGuard
SkinsRestorer
CustomPayloadFixer
TAB-Bridge-2.0.1.jar
ViaBackwards
IPWhitelist
ViaVersion
LuckPerms
WorldEdit
PlaceholderAPI
WorldGuard

* Velocity plugins:
limboauth
skinsrestorer
limboapi
limbofilter
TAB

* Minecraft Launcher

**Comment by xknat** [comment]
Please join our discord for support, GitHub are for confirmed bugs only.
Likely your using their broken Dev build...
Or did you not install according to our velocity installation steps
