### ISSUE TITLE
Skin menu not working properly

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [SkinsRestorer/SkinsRestorerX#937]
## Describe the bug

When you open the skins menu, it immediately breaks and you can pick up anything from it

## How can we reproduce what you got?

1. have a bungee+paper server
2. Enter command /skins
3. click on an item

**Expected behavior**
I expected it to work as it should, like a regular menu

**Media**
https://youtu.be/aKvo7qn_RLQ

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.15
* Paper version: git-Paper-324
* Bungeecord version: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636
* IF bungee, did you put the plugin on all servers: Yes 
* Java: 17 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS)
* plugin list bungee & spigot: Bungee - floodgate-bungee, Geyser-Bungeecord, SkinsRestorer; Paper - PlugManX, SkinsRestorer, floodgate-spigot

## Logs

Bungee: https://hastebin.app/62775670b94bd5001c8fbadf
Paper: https://hastebin.app/627756e6b94bd5001c8fbae0

**Comment by xknat** [comment]
Already resolved #927
Use Dev build
