### ISSUE TITLE
MySQl Error

### ISSUE THREAD

**Issue by TheFloodDragon** [SkinsRestorer/SkinsRestorerX#943]
Server Version: Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486
Plugin Version: SkinsRestorer-14.2.0-SNAPSHOT

Server Enable Plugins: 
FastLoginBungee, PistonMOTD-Bungee-5.0.1, PlayerBalancer-2.3.2-SNAPSHOT, SkinsRestorer-14.2.0-SNAPSHOT, TrChat-2.0.0-PRE-8

Logs:
![Error Report-1](https://user-images.githubusercontent.com/75253383/169640713-10195c7c-55d6-4408-89f7-f634c752bd01.png)
 
please fix it now, thanks :)

**Comment by AlexProgrammerDE** [comment]
This was fixed already few hours ago: https://github.com/SkinsRestorer/SkinsRestorerX/commit/272f1dd49a9a0d049c3788267a2e3d8c768a76d9
Please use the latest dev build before reporting.
