### ISSUE TITLE
Skin GUI and SRPlaceholderAPIExpansion Questions

### ISSUE THREAD

**Issue by TheFloodDragon** [SkinsRestorer/SkinsRestorerX#944]
## Describe the bug

After entering the /skins command, only the information is displayed, and the GUI is not opened
Using all placeholders on SRPlaceholderAPIExpansion will give an error

**Expected behavior**
Fix

## Server information

**On what platform does your server run? Bungeecord and Spigot**

* SkinsRestorer: last build version
* Spigot version: spigot-1.13.2
* Bungeecord version: Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486
* IF bungee, did you put the plugin on all servers? Yes
* Java: 8

## Logs
![Error logs-3](https://user-images.githubusercontent.com/75253383/169650307-fda428cc-4082-41d6-b243-9ec35fb5d3ca.png)

**Comment by xknat** [comment]
> * SkinsRestorer: last build version

We only support latest dev build!
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastSuccessfulBuild/artifact/build/libs/SkinsRestorer.jar

**Comment by TheFloodDragon** [comment]
> > * SkinsRestorer：最后一个构建版本
> 
> 我们只支持最新的开发版本！ https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastSuccessfulBuild/artifact/build/libs/SkinsRestorer.jar

That's the problem with that version！

**Comment by xknat** [comment]
What version of [SRPlaceholderAPIExpansion](https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion) are you using? This issue should also not be here but moved to SRPlaceholderAPIExpansion

**Comment by TheFloodDragon** [comment]
> What version of [SRPlaceholderAPIExpansion](https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion) are you using? This issue should also not be here but moved to SRPlaceholderAPIExpansion

SRPlaceholderAPIExpansion-1.6
The latest version of SRPlaceholderAPIExpansion

**Comment by TheFloodDragon** [comment]
> What version of [SRPlaceholderAPIExpansion](https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion) are you using? This issue should also not be here but moved to SRPlaceholderAPIExpansion

So, what time did you fix the bugs?
