### ISSUE TITLE
SkinsRestorer-Bungee cannot be enabled in Waterfall

### ISSUE THREAD

**Issue by TheFloodDragon** [SkinsRestorer/SkinsRestorerX#960]
* SkinsRestorer: 14.2.0-SNAPSHOT dev 336
* Waterfall version: 1.19-493
* IF bungee, did you put the plugin on all servers: Yes
* Java: 17

## Logs

![Error Logs](https://user-images.githubusercontent.com/75253383/172884219-81588757-cd73-4e88-8182-e45abcdf3eed.png)

Please check this

**Comment by xknat** [comment]
1.19 is not yet supported for proxy
