### ISSUE TITLE
Not support Geyser skins

### ISSUE THREAD

**Issue by ghost** [SkinsRestorer/SkinsRestorerX#962]
## Describe the bug

Bedrock Edition can see the JAVA version of the skin but the Java version cannot see the Bedrock Edition skin

## How can we reproduce what you got?

1. Use bedrock and java join the game
2. Bedrock Edition can see the JAVA version of the skin but the Java version cannot see the Bedrock Edition skin

**Expected behavior**
Bedrock Edition can see the JAVA version of the skin but the Java version cannot see the Bedrock Edition skin

**Screenshots**
![QQ截图20220611020021](https://user-images.githubusercontent.com/78008410/173124583-f028a147-75fc-45cf-b07a-d35e7e9bb69c.png)
## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer:14.2.0-SNAPSHOT
* Spigot version: 1.18.2 purpur fork
* Bungeecord version: velocity-3.1.2-SNAPSHOT-153
* IF bungee, did you put the plugin on all servers: Yes
* Java: 17
* plugin list bungee & spigot: Geyser-Velocity floodgate-velocity geyserskinmanager-velocity
* MinecraftLauncher?: HMCL
* if multiverse, (censored) worlds file: no

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)

No logs

**Comment by ghost** [comment]
I give bedrock a skinsrestorer.bypassdisabled but not work
or use skin updata

**Comment by ExtremeFiretop** [comment]
Confirmed on 1.19 as well (Noticed your report was of 1.18.2)

Just wanted to mention before the plugin update for 1.19 that it did work with Bedrock clients/Geyser properly.
Since the dev build/update for 1.19 of this Plugin it no longer works for Geyser.

**Comment by srlss123** [comment]
> 在1.19上也确认了（注意到您的报告是1.18.2）
> 
> 只是想在1.19的插件更新之前提到它确实可以与Bedrock客户端/ Geyser正确配合使用。由于此插件的1.19的开发构建/更新，它不再适用于Geyser。

I try lasted version 14.1.15. It's still not work
So I try dev - version

**Comment by ghost** [comment]
> Confirmed on 1.19 as well (Noticed your report was of 1.18.2)
> 
> Just wanted to mention before the plugin update for 1.19 that it did work with Bedrock clients/Geyser properly. Since the dev build/update for 1.19 of this Plugin it no longer works for Geyser.

I try lasted version 14.1.15. It's still not work
So I try dev - version

**Comment by ghost** [comment]
It's because 14.1.15 doesn't support geyser properly, so I tried the latest dev version

**Comment by ExtremeFiretop** [comment]
> It's because 14.1.15 doesn't support geyser properly, so I tried the latest dev version

This is a Geyser issue. After updating Geyser and Floodgate I no longer have the offline skin issues.

This does not appear to be an issue with SkinRestorerX.

Please update Geyser and Floodgate to resolve the issues. (Worked for me.)

This can probably be closed. Thanks

**Comment by ifloppy** [comment]
都Geyser了，肯定要有Floodgate，至少在我这里，是正常的（1.18），也许1.19更新后需要更新插件呢

**Comment by xknat** [comment]
> > It's because 14.1.15 doesn't support geyser properly, so I tried the latest dev version
> 
> This is a Geyser issue. After updating Geyser and Floodgate I no longer have the offline skin issues.
> 
> This does not appear to be an issue with SkinRestorerX.
> 
> Please update Geyser and Floodgate to resolve the issues. (Worked for me.)
> 
> This can probably be closed. Thanks

See ^
We did not make any major changes with the skin refresher...
